### ISSUE TITLE
Release Service Bus Track 2 Library Preview 3 for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#10428]
Released package: https://search.maven.org/artifact/com.azure/azure-messaging-servicebus/7.0.0-beta.3/jar

This is a parent issue tracking the work planned for Service Bus to release the third preview following the [Java Azure SDK guidelines](https://azure.github.io/azure-sdk/java_introduction.html) 

Code complete date: June 5th, 2020

## Deliverables
- [x] Support for Transactions 
- [ ] Send via feature
- [ ] Design for supporting various AMQP data types for message body
- [x] UX Studies

## Stretch Goals
- [x] CRUD & list operations using connection string

## Java-specific
- [x] Should ServiceBusClientBuilder add `close` API
