### ISSUE TITLE
Form training client API consistency issues

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#10733]
- [x] Adopt to training namespace to align with .NET #11097
- [x] Add model for training file filter called TrainModelOptions  #11097
- [x] Rename training files param to trainingFilesUrl  #11097
- [x] Rename useLabels to useTrainingLabels.  #11097
- [x] Follow language precedence for Code / ErrorCode #10138
- [x] Rename AccountProperties count and limit to customModelCount and customModelLimit  #11097`
- [x]  Rename getCustomModelInfos to getCustomModels #11533
- [x] [More discussion needed]:  change models property name in CustomFormModel #11533
