### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 5 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#10960]
This tracks the work to release the Azure Cognitive Search Track2 Preview 5 Library for JAVA

### API Review
- [x] (P0)Final architecture board review (https://github.com/azure/azure-sdk/issues/1428)

### Features

- [ ] (P1) FieldBuilder, better to have, but additive changes. (https://github.com/azure/azure-sdk-for-java/issues/10647)
- [x] (P0) Search paging << API change (https://github.com/azure/azure-sdk-for-java/issues/12116, )
- [x] (P0) Change to type constructors << API change (https://github.com/azure/azure-sdk-for-java/issues/12112)
- [x] (P1) Strongly typed serialization for get document API << API addition (https://github.com/azure/azure-sdk-for-java/issues/12114)
- [x] (P0) Upgrade to autorest V4. (https://github.com/azure/azure-sdk-for-java/issues/12109, )
- [ ] (P1) SearchFilter helper (https://github.com/azure/azure-sdk-for-java/issues/12110)
- [ ] (P1) IndexParameters helper (https://github.com/azure/azure-sdk-for-java/issues/8908)

### Testing (P1)
(https://github.com/azure/azure-sdk-for-java/issues/11145, https://github.com/azure/azure-sdk-for-java/issues/9917)
### Docs (P0)

Note: Priority notes as P0, P1, P2 ordered by most important change to least important change.

**Comment by sima-zhu** [comment]
Move The remaining issues to GA+1
