### ISSUE TITLE
Azure Tables Sprint 1

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#10966]
## Tasks
- [ ] Familiarity with Azure
- [ ] Familiarity with Tables
- [ ] Service Documentation
- [ ] Review Existing SDKs
- [ ] Review existing samples
- [ ] Familiarity with Code Gen
- [ ] Make some service calls using generated code like insert

## Deliverables
- [ ] Auto-generated REST API code
- [ ] Arch Board: Introduction to Azure Tables service
- [ ] Stretch: Pseudo code for HERO scenarios

Related #10973
