### ISSUE TITLE
Azure Tables Sprint 2

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#10973]
## Tasks
- [ ] Use existing SDKs to design around the auto-generated code.
  - Consider pipeline policies required
  - Consider authentication
  - Consider child/parent hierarchy of types
  - Design for both asynchronous and synchronous API
- [ ] Migrate any applicable tests that fit into API surface area.

## Deliverables
- [ ] API View for the initial development
- [ ] Skeleton of API (nothing works or is hooked up).
- [ ] Migrate test **scenarios** from Track 1 that fit into Track 2
  - Don't port code as-is, think about how a user would accomplish the same scenario using Track 2 client library and create the test around it.

## Stretch Goal
- [ ] Implementation of the async client

Related #10966
