### ISSUE TITLE
Improve Cosmos SDK Java V4 APIs

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#11193]
This issue tracks improvements which need to be done for Java SDK V4 GA. 
This covers APIs, docs and java code samples

- [x] `CosmosClientBuilder` -> https://github.com/Azure/azure-sdk-for-java/issues/11189

- [x] `CosmosAsyncClient / CosmosClient` -> https://github.com/Azure/azure-sdk-for-java/issues/11219

- [x] `CosmosAsyncDatabase / CosmosDatabase` -> https://github.com/Azure/azure-sdk-for-java/issues/11190

- [x] `CosmosAsyncContainer / CosmosContainer` -> https://github.com/Azure/azure-sdk-for-java/issues/11191

- [x] `IncludedPath / ExcludedPath` -> https://github.com/Azure/azure-sdk-for-java/issues/11192

- [x] `CosmosClientException / CosmosError` -> https://github.com/Azure/azure-sdk-for-java/issues/11220

- [x] `AccessCondition / AccessConditionType` -> https://github.com/Azure/azure-sdk-for-java/issues/11221

- [x] `CosmosAsync*Response / Cosmos*Response` -> https://github.com/Azure/azure-sdk-for-java/issues/11223

- [x] `Remove *BridgeInternal from java docs` -> https://github.com/Azure/azure-sdk-for-java/issues/11259

- [x] `Wrap FeedResponseDiagnostics in CosmosDiagnostics` -> https://github.com/Azure/azure-sdk-for-java/issues/11257

- [x] `CosmosAsyncStoredProcedure / CosmosStoredProcedure` -> https://github.com/Azure/azure-sdk-for-java/issues/11260

- [x] `CosmosResponseDiagnostics -> CosmosDiagnostics` -> https://github.com/Azure/azure-sdk-for-java/issues/11261

- [x] `ConflictResolutionPolicy` -> https://github.com/Azure/azure-sdk-for-java/issues/11307

- [x] `CosmosKeyCredential -> AzureKeyCredential` -> https://github.com/Azure/azure-sdk-for-java/issues/11315

- [x] Export `ProxyOptions` through CosmosClientBuilder -> https://github.com/Azure/azure-sdk-for-java/issues/11316

- [x] Upsert APIs on parent types -> https://github.com/Azure/azure-sdk-for-java/issues/11438

- [x] OffsetDateTime -> Instant type -> https://github.com/Azure/azure-sdk-for-java/issues/11439

- [x] `OperationKind` enum-> https://github.com/Azure/azure-sdk-for-java/issues/11440

- [x] Check if match ETag APIs are present on all properties types - https://github.com/Azure/azure-sdk-for-java/issues/11436

- [x] getRequestCharge() / Properties types / getResourceId() APIs -> https://github.com/Azure/azure-sdk-for-java/issues/11483

- [x] DatabaseAccountLocation -> https://github.com/Azure/azure-sdk-for-java/issues/11524

- [x] Rename `DataType` to `GeoJSON` -> https://github.com/Azure/azure-sdk-for-java/issues/11525

- [x] FeedOptions API / docs -> https://github.com/Azure/azure-sdk-for-java/issues/11526

- [x] SerializationFormattingPolicy -> https://github.com/Azure/azure-sdk-for-java/issues/11527

- [x] getETag() and getTimestamp() API docs -> https://github.com/Azure/azure-sdk-for-java/issues/11528

- [x] ThroughputProperties docs -> https://github.com/Azure/azure-sdk-for-java/issues/11529

- [x] UniqueKey and UniqueKeyPolicy API / docs -> https://github.com/Azure/azure-sdk-for-java/issues/11530

- [x] DirectConnectionConfig / GatewayConnectionConfig APIs / docs -> https://github.com/Azure/azure-sdk-for-java/issues/11531

- [x] Add SDK version info in CosmosException -> https://github.com/Azure/azure-sdk-for-java/issues/11586

- [x] new line improvement in SDK toString -> https://github.com/Azure/azure-sdk-for-java/issues/11594

- [x] Fix azure-cosmos README -> https://github.com/Azure/azure-sdk-for-java/issues/11643

- [x] Fix azure-cosmos changelog -> https://github.com/Azure/azure-sdk-for-java/issues/11644

- [x] CosmosPermissionProperties API changes -> https://github.com/Azure/azure-sdk-for-java/issues/11647

- [x] ChangeFeedProcessor improvements -> https://github.com/Azure/azure-sdk-for-java/issues/11648

- [x] Error details in Client side 503 -> https://github.com/Azure/azure-sdk-for-java/issues/11674

**Comment by kushagraThapar** [comment]
This is done :)
