### ISSUE TITLE
Release Service Bus Track 2 Library Preview 4 for Java

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#11428]
Released as: https://search.maven.org/artifact/com.azure/azure-messaging-servicebus/7.0.0-beta.4/jar

This is a parent issue tracking the work planned for Service Bus to release the fourth preview following the [Java Azure SDK guidelines](https://azure.github.io/azure-sdk/java_introduction.html) 

Code complete date: July 5th, 2020

## Deliverables
- [x] Send via feature
- [x] Dead letter Receiver
- [ ] Various timeout 
- [x] Management operations
  - [x] Subscriptions
  - [x] Namespace calls
  - [ ] Authorization rules

## Java-specific
- [x] Test debt
   - [ ] Fix Bugs 
- [x] UX Feedback
  - [x] Remove MessageLockToken
  - [x] Connection sharing: Single ServiceBusClient or multiple builders
