### ISSUE TITLE
Release Service Bus Track 2 Library Preview 4 for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#11895]
This is a parent issue tracking the work planned for Service Bus to release the fourth preview following the [Java Azure SDK guidelines](https://azure.github.io/azure-sdk/java_introduction.html) 

Code complete date: June 5th, 2020

## Deliverables
- [ ] Send via feature
- [ ] Design for supporting various AMQP data types for message body

- [ ] Management operations
  - [ ] Subscriptions
  - [ ] Namespace calls
  - [ ] Authorization rules

## Java-specific
- [ ] Test debt
- [ ] UX Feedback
  - [ ] Remove MessageLockToken
  - [ ] Connection sharing: Single ServiceBusClient or multiple builders?

**Comment by conniey** [comment]
Closed in favour of #11428
