### ISSUE TITLE
Event Grid Sprint 2

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#12376]
## Tasks
- [x] Use existing SDKs to design around the auto-generated code.
  - Consider pipeline policies required
  - Consider authentication
  - Consider child/parent hierarchy of types
  - Design for both asynchronous and synchronous API
- [x] Migrate any applicable tests that fit into API surface area.

## Deliverables
- [x] API View for the initial development
- [x] Skeleton of API (nothing works or is hooked up).
- [x] Migrate test **scenarios** from Track 1 that fit into Track 2
  - Don't port code as-is, think about how a user would accomplish the same scenario using Track 2 client library and create the test around it.

## Stretch Goal
- [x] Implementation of the async client

Related #12375
