### ISSUE TITLE
Event Grid Sprint 1

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-sdk-for-java#12375]
## Tasks
#12377
- [x] Familiarity with Azure
- [x] Familiarity with Event Grid
- [x] Read service documentation
- [x] Review Azure Core libraries
- [x] Review existing Event Grid libraries
- [x] Review existing Event Grid samples
- [x] Make some basic service calls using generated code like create topic, create event subscription, publish event to topic

#12378
- [x] Review Event Grid REST API
- [x] Familiarity with Java code generation via AutoRest
- [x] Create Event Grid project skeleton in the Java repo

#12379 
- [x] Add unit and integration tests for generated code

## Deliverables
- [x] Auto-generated REST API code
- [ ] Arch Board: Introduction to Event Grid service
- [x] Stretch: Pseudo code for Champion scenarios

Related #12376

**Comment by YijunXieMS** [comment]
Thanks @Soreloser2 and @bsiegel for your wonderful work.
Close it now.
