### ISSUE TITLE
August release of Key Vault for Java

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#12935]
# Features
- [x] Support for 7.1 service version.
- [x] Add "import" to `KeyOperation`.
- [x] Add `RecoverableDays` to certificate, key, and secret properties.

# Other changes
- [x] Fixed checkstyle `EnforceFinalFieldsCheck` violations in Key Vault classes (#13323).
