### ISSUE TITLE
Opinion Mining Text Analytics Java Epic

### ISSUE THREAD

**Issue by iscai-msft** [Azure/azure-sdk-for-java#12979]
- [x] Regenerate v3.1-preview.1: https://github.com/Azure/azure-sdk-for-java/issues/12980
- [x] Clear final design with architect: https://github.com/Azure/azure-sdk-for-java/issues/12981
- [x] implement design: https://github.com/Azure/azure-sdk-for-java/issues/12982
- [x] tests: https://github.com/Azure/azure-sdk-for-java/issues/12983
- [x] samples: https://github.com/Azure/azure-sdk-for-java/issues/12984

**Comment by mssfang** [comment]
PR merged in https://github.com/Azure/azure-sdk-for-java/pull/13333
