### ISSUE TITLE
Azure Core Cobalt Semester

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#13206]
This contains all issues we plan to resolve by the end of the Cobalt semester (June 2021).

_Partner Requests_ (@alzimmermsft) 

- [x] GeoJSON models. (#13209)

_Reliability_ (@YijunXieMS, @anuchandy)

- [x] `RestProxy` reflection permission failure. (#12829)
- [x] Support cancellation tokens. (#8357) -- (@anuchandy) 

_Performance Enhancements_ (@g2vinay)

- [x] HttpPipeline performance benchmarking and enhancements. (#12656)
