### ISSUE TITLE
Azure Cognitive Search September Release

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#13877]
Parent issue for all issues we wish to complete for the September 2020 release.

_Partner and Customer Requests_

- [x] Release FieldBuilder functionality. (#13878)
- [x] Release pluggbale serialization functionality. (#13879)
- [x] Add auto document batching functionality. (#13880)
- [x] Regenerate code based on updated Swagger. (#13881)

_Reliability_

- [x] Add IndexingParameters helper class. (#8908)
- [ ] ~~Add odata filter expression helpers. (#12110)~~
- [x] Reduce Index thrashing during live tests. (#11145)
- [ ] ~~Enable Spotbugs on test code. (#9360)~~

_Performance Enhancements_

- [x] Create performance tests for champion scenarios. (#14308 )

_Supportability_

- [x] Create default log options. (#8686)
