### ISSUE TITLE
Release Service Bus Track 2 Library Preview 6 for Java

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#14184]
This is a parent issue tracking the work planned for Service Bus to release the GA following the java SDK Guidelines https://azure.github.io/azure-sdk/java_introduction.html

Code complete date: September 5th, 2020

## Deliverables

- [ ] Performance Analysis Improvements
- [ ] Expose application_id  in user agent to client
- [ ] Authorization Rule
- [ ] Changes in API which came out of API Review
- [ ] ScheduleMessage, cancelScheduleMessage overload for multiple messages
