### ISSUE TITLE
Azure SDKs Performance work Iron Semester

### ISSUE THREAD

**Issue by g2vinay** [Azure/azure-sdk-for-java#14316]
- [x] Add Performance Tests for Eventhubs SDK #14307 
- [x] Add Performance Tests for Search SDK #14308 
- [x] Add Performance Tests for Text Analytics SDK #14309 
- [x] Add Performance Tests for Form Recognizer SDK #14310 
- [x] Add Performance Tests for Identity SDK #14313 
- [x] Add Performance Tests for Service Bus SDK #9919
- [x] Add Performance tests for KV SDK. #5472
- [x] Expand Performance Test suite for App Config SDK #14311 
- [ ] Add Latency Support to Perf Test framework #14315
