### ISSUE TITLE
October Release of Key Vault for Java

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#14747]
### Features
 - [ ] ~~Secure Key Release design and implementation~~ **Postponed until after service changes are made.**
 - [ ] ~~Arch Board review for Secure Key Release~~ **Postponed until after service changes are made.**
 - [ ] API unification meeting
 - [ ] ~~Setup CI tests for Admin package~~ **Not happening in this cycle.**
 - [x] Address customer feedback
 - [ ] ~~[stretch] Move to ChallengeBasedAuth once it is in Core.~~ **Not happening in this cycle.**
 - [ ] [stretch] Parsing resource url into segments
