### ISSUE TITLE
Azure Cognitive Search October Release

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#14751]
Parent issue for all issues we wish to complete for the October 2020 release.

_Partner and Customer Requests_

- [ ] Release auto document batching functionality. (#14752)
- [ ] Release `IndexingParametersConfiguration` changes. (#14753)
- [ ] Spatial type support
- [ ] More samples 

_Reliability_

- [x] Add odata filter expression helpers. (#12110)
- [ ] Enable Spotbugs on test code. (#14755)

_Performance Enhancements_

- [ ] Investigate performance enhancements. (#14754)

_Supportability_
