### ISSUE TITLE
Release Form Recognizer 3.1.0-beta.1

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#14884]
- [x] Add support for business cards #14885

- [ ] Add support for selection marks field element #14886

- [x] Add support for compose model #14887

- [x] Support locale parameter for receipt and business cards #14888

- [ ] Validate Support for container local files #14982

- [x] Add support for optional display name on  models #14889

- [ ] Support ApplicationId in User agent telemetry support FR #15125

- [ ] Add perfomance testing for Form Recognizer #14310

- [x] Add support for invoice recognition API's #16285

**Comment by samvaity** [comment]
Released 3.1.0-beta.1
