### ISSUE TITLE
Event Grid post-beta1 release

### ISSUE THREAD

**Issue by Soreloser2** [Azure/azure-sdk-for-java#14927]
I've made a list of things to do and keep track of following the first preview of the Event Grid SDK
## To Do:
Things that we decided on but are not included in the initial preview

- [x] Make data a required constructor parameter in `EventGridEvent` (#14922)
- [x] Make the serializer in the `PublisherClientBuilder` take a `JsonSerializer` (#14926)
  - possible problems with this, see linked issue and section below about custom event schema for details
- [x] Distributed Tracing support (#14851)

## To Consider:
Things that are not decided on, talk with other languages to sync up on decisions

- [ ] Rename `CloudEvent` type field to be `eventType`
  - probably not worth diverging from spec unless there are other issues
- [x] Overload/option to send single event
  - implicit/fancy batching?
- [x] Generate Sas credential on client
  - replace or add additional way to generate? 
  - instance method since endpoint and key credential already known
  - failure if client was already authenticated using Sas credential, make that easy to understand
- [ ] Accepting `Iterable<Event>` on send events is slightly slow
  - we need to iterate twice to collect into list, then to serialize
  - possibly only take list instead, or change swagger/serialize as we iterate
- [x] Custom serialization for Custom Event Schema (addressed in #14926)
  - we don't know the type of object so we can't make a custom serializer module for it

## Possible Future Changes: 
Things that may change due to work by others  (mostly in core)

- `CloudEvent` may move to core package due to common usage across libraries in the future
  - shouldn't be too big of a deal, just make sure that we sync up with core
- `BinaryData` may replace `byte[]` in deserialized data field
  - dependent on release of `BinaryData` in core/resulting API shape
- Try to make agnostic dependency on a `JsonSerializer`
  - currently depend on Jackson and specifically call it to add modules like flattening and `OffsetDateTime` deserialization
  - may need to wait until default deserialization comes with certain modules or customization is possible
  - try to use `JsonSerializerProvider` class to load a dependency from the classpath

## To Work On:
Things that could use some extra work

- [ ] Testing
  - more scenarios (check for the correct errors in failure cases)
  - more unit/granular tests
  - different HTTP configurations
- [x] Samples
  - more customization examples 
  - full end to end code samples, possibly with other service integrations
  - put in Readme sample area if they are important/useful for beginners
- [x] Checkstyle
  - currently everything is suppressed in eng/code-quality-reports/.../checkstyle/checkstyle-suppressions (near the bottom)
  - can't really change swagger generated files so OK to keep suppressing those, but written files can be mostly fixed

**Comment by Soreloser2** [comment]
I have a PR open for the first issue: #15000

**Comment by YijunXieMS** [comment]
This is a umbrella issue so it doesn't have an estimation

**Comment by YijunXieMS** [comment]
All issues are addressed
