### ISSUE TITLE
Expose com.azure.core.util.ClientOptions via Builder for all the SDK 

### ISSUE THREAD

**Issue by hemanttanwar** [Azure/azure-sdk-for-java#15107]
SDK need to provide user to set following

1. A common way to provide applicationId in UserAgent. 
2. Allow users to set Headers on Http Request. 

Use ClientOption as a option bag to collect this information.

ClientOptions: https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/core/azure-core/src/main/java/com/azure/core/util/ClientOptions.java 

Introduced in : azure-core : 1.9.0

```java
public final class ClientOptions {
    private Iterable<Header> headers = new ArrayList<>();
    private String applicationId;
}
```
We should expose this via Builder https://github.com/Azure/azure-sdk-for-java/pull/13697/files#diff-860f082a6593b9a09fa1a4d4fd0b5cf7R105
 For example: 
```java
   public ServiceBusClientBuilder clientOptions(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        return this;
    }
```
**Ensure following is achieved**

 - [ ] User can set ClientOptions using Builder 
 - [ ] Take applicatin-Id from ClientOptions and set it in UserAgent
 - [ ] Take the Headers set by user in ClientOptions and set them on Http Request. We would have to make sure whatever the user passed in as Header, is not overwritten by the policies. So we should just add an AddHeadersPolicy after all other policies.
