### ISSUE TITLE
November relese of Key Vault for Java

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#15910]
# Features

- [ ] Secure key release
- [ ] Local cryptography (as many algorithms - including new - as possible)

# Testing

- [ ] RBAC
- [ ] Backup/restore
- [ ] Secure key release
- [ ] Local cryptography
