### ISSUE TITLE
Release Form Recognizer 3.1.0-beta.2

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#18481]
- [x] Implement design for supporting page range
- [x] Implement design for supporting appearance
- [ ] Regenerate Implementation Layer with Interface Scoping Changes
- [ ] Form Recognizer - Update Client Builders to Leverage HttpPipelinePosition
- [x] Validate Support for container local files
- [ ] Add Performance Tests for Form Recognizer SDK
- [ ] Enable Spotbugs check on All Track 2 SDK Samples and test code files.
- [x] https://github.com/Azure/azure-sdk-for-java/pull/17167#discussion_r517596897

**Comment by samvaity** [comment]
Released 3.1.0-beta.2
