### ISSUE TITLE
Release Metrics Advisor 1.0.0-beta.3 

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#18557]
- [x] Add support for for credential rotation on MetricsAdvisorKeyCredential https://github.com/Azure/azure-sdk-for-java/issues/18560
- [x] Support AAD authentication for Metrics Advisor https://github.com/Azure/azure-sdk-for-java/issues/18559
- [x] Support consistent Live test pipeline testing #18816
- [ ] ~~Transform ErrorCodeException to HttpResponseException https://github.com/Azure/azure-sdk-for-java/pull/17250~~
- [ ] Add more tests for update/patch scenarios
- [ ] ~~New features (APIs) updates?~~ Moved to March release.
- [ ] Update for Patch/update operations, should the swagger changes be rolled back (completely rely on autorest) ?
