### ISSUE TITLE
Azure Core AMQP Nickel+ Semester Reliability Improvements

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#18819]
### Reliability Improvements (bug fixes)

- [x] #20344
- [x] #20291
- [x] #20380
- [x] #22500
- [x] #21852
- [x] #20660
- [x] #18890
- [x] #16127
- [x] #20640
- [x] #19281
- [x] Fix retry handling on transient errors (we are not consistently re-creating the connection).
- [x] #20790

### Performance

- [x] #20841
- [ ] #20852
- [ ] #22866
- [ ] #22867
- [x] #20828
- [x] #20791

### Long-running Tests
- [x]  #20986
- [x] #20838
- [x] #20784
    - [x] #20826
- [x] #20834
    - [x] #22869
- [x] #20829 Event Hubs Service Stress Tests. The service team owns a set of service tests. Investigate failures in that.

### Diagnosability/Troubleshooting Improvements

- [ ] #23090
- [ ] #20835
- [ ] #20836
- [x] #20837
    - [ ] #3806

### Long-term Maintainability Features

- [x] #20825
- [x] #19221
    - [ ] Migrate Service Bus processors
    - [ ] Migrate Event Hubs processors
- [ ] #5478

**Comment by joshfree** [comment]
@conniey @anuchandy can this now be closed (with any unfinished work ported to the Copper epic)
