### ISSUE TITLE
March release of Key Vault for Java

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#18985]
## Features

- [ ] RBAC including custom role definitions
- [ ] Full/selective backup/restore
- [ ] AES key support
- [ ] Public exponent authoring for RSA keys

## Tasks

- [ ] Documentation
- [ ] Performance tests
- [ ] Archboard API review for upcoming GA

**Comment by vcolin7** [comment]
Custom Role Definitions will be included in the next (April) release.
