### ISSUE TITLE
Metrics Advisor Beta 4

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#19111]
- [x]  Support new data source type: Event Hubs #19092
- [x] Credential Entity #19088
- [x] Enable Spotbugs check on Samples and test code files. #19178
- [x]  Add Performance Tests for Metrics Advisor SDK #18989
- [ ]  Update Client Builders to Leverage HttpPipelinePosition (waiting on core PR - https://github.com/Azure/azure-sdk-for-java/pull/16613)
