### ISSUE TITLE
Form Recognizer Beta 3 (v2.1-preview.3)

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#19174]
- [ ] Known Form Recognizer service issues #18967
- [ ] Prebuilt models design #18857
- [x] Swagger update v2.1-preview.3 #19175
- [x] Regenerate Implementation Layer with Interface Scoping Changes
- [x] Add Performance Tests for Form Recognizer SDK #14310
- [x] Enable Spotbugs to check on Samples and test code files. #19177
- [ ]  Form Recognizer - Update Client Builders to Leverage HttpPipelinePosition (waiting on core PR - https://github.com/Azure/azure-sdk-for-java/pull/16613) 
- [ ] Support Form Recognizer testing in all azure clouds #19176

**Comment by samvaity** [comment]
Released
