### ISSUE TITLE
[TA-Epic] 2021 March Epic for Text Analytics

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#19179]
- [x] Update changes based on new swagger v3.1-preview.4 https://github.com/Azure/azure-sdk-for-java/issues/19180
- [x] Performance Matrix https://github.com/Azure/azure-sdk-for-java/issues/14309
   - [x] Based on Alan's discovery, the performance will increase near 30% without logging content.  
- [x] Restructure TextAnalyticsActionResult and its derive classes https://github.com/Azure/azure-sdk-for-java/issues/19053
- [ ] Fix service bugs:
  - -[x] https://github.com/Azure/azure-sdk-for-java/issues/17629
  - -[ ] https://github.com/Azure/azure-sdk-for-java/issues/17625
  - -[x] https://github.com/Azure/azure-sdk-for-java/issues/17564
  - -[ ] https://github.com/Azure/azure-sdk-for-java/issues/13841
- [ ] UX Study feedbacks: https://github.com/Azure/azure-sdk-for-java/issues/16694
- [x] Others:
  - -[x]  https://github.com/Azure/azure-sdk-for-java/issues/15640

**Comment by mssfang** [comment]
features related to 3.1v-preview.4 is merged. But rest of service bugs and other issues will be transfer done in March
