### ISSUE TITLE
azure-core Performance Improvements

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19282]
This issue tracks on-going, and completed/terminated, performance improvement work items for `azure-core`, and other Core libraries.

- [x] Investigate Support Additional Body Types in HttpRequest #19025
- [ ] Less Eagerly Request Upstream Emissions when Sending Request #18680
- [x] Investigate retaining buffers during subscription lifetime #8053
- [x] Investigate getBodyAsInputStream API for HttpResponse #16035
- [ ] Add a Flux<ByteBuffer> Backed Stream Implementations #11676
- [x] Investigate Leveraging Jackson AfterBurner/Blackbird #19284
- [x] Support Multi-Version JARs #19160
    - [x] Investigate Replacing Reflection with MethodHandles #18987 (Requires Java 9+) 
- [x] Investigate using MappedByteBuffer when Sending a File as a Request Body #19283
- [x] Review HttpRequest Body Reading in HttpPipelinePolicies #14917
- [x] Investigate Less Eager Requests when Sending Network Data #19010
- [ ] Investigate Zero Second Retry Delay Handling #18475
- [ ] [FEATURE REQ] Add sendFile API to HttpClient #13099
- [ ] Configurable chunk-size for azure-core-netty #8054
- [x] [Proposal] Add HttpHeaders Constructor with Initial Size #11472

**Comment by alzimmermsft** [comment]
Closing as this was a tracking issue which is now managed by a GitHub project
