### ISSUE TITLE
Create a Roadmap and Overview for azure-sdk-bom

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#19618]
Create a markdown file, or add to the README file, which outlines the following for `azure-sdk-bom`:

- [ ] Targeted release cadence
- [ ] Requirements for a release
- [ ] Requirements for included libraries
