### ISSUE TITLE
Form Recognizer Beta 4

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#20570]
- [x] Known Form Recognizer service issues #18967
- [x] Prebuilt models design #18857 [no longer an option]
- [ ] Support Form Recognizer testing in all azure clouds #19176 [WIP]
- [ ] Support code is written customization to minimize handwritten translation layers #20572 [WIP]
- [ ] Improvement to perf analysis and testing Form Recognizer #20708 
- [x] Updates for GA May 10th [Ref](https://teams.microsoft.com/l/message/19:88f2d9dea2344075b5d4bc34d82a3d1c@thread.skype/1618342349554?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1618342349554&teamName=Azure%20SDK&channelName=Service%20-%20Form%20Recognizer&createdTime=1618342349554)
- [x]  Form Recognizer - Update Client Builders to Leverage HttpPipelinePosition (waiting on core PR - https://github.com/Azure/azure-sdk-for-java/pull/16613) 
- [x] Expose com.azure.core.util.ClientOptions via Builder and implement applicationId in UserAgent for telemetry  #15125 
- [x] Update Form recognizer to use core util Byte buffer transforms #20364
- [x] Enable Disabled tests #20702

**Comment by mssfang** [comment]
Prebuild API design will not excluded. v-team decided to not having prebuild API design

**Comment by mssfang** [comment]
We don't do the beta 4 release but instead of directly GA v3.1 SDK with newer swagger v2.1 on Late of May (around 5/25?)
PR: https://github.com/Azure/azure-sdk-for-java/pull/21332

**Comment by mssfang** [comment]
move remaining issues to https://github.com/Azure/azure-sdk-for-java/issues/21687:

 Support Form Recognizer testing in all azure clouds #19176 [WIP]
 Support code is written customization to minimize handwritten translation layers #20572 [WIP]
 Improvement to perf analysis and testing Form Recognizer #20708
