### ISSUE TITLE
Azure Core Nickel Semester

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#20995]
This is a tracking issue for all `Azure.Core` and `EngSys` issues that are planned to be resolved by November 2021.

_Child Tracking Issues_

Children tracking issues contain no issues that aren't tracked by this issue but provide a separate view of the planned to be resolved issues.

- [x] Azure Core for Java (September 2021) (#21899)
- [x] Azure Core for Java (October 2021) (#21900)
- [ ] azure-core Performance Improvements (#19282)
- [ ] Dependency management and unification with Spring's bom and azure-sdk-bom (#21283)
- [ ] Tooling for Java (Nickel Semester) (#22216)

_Partner Requests_

- [x] [QUERY] AzureJacksonAdapter fails to serialize map with key of resource ID (#8372) [Management]
- [x] [FEATURE REQ] Share HttpClient if not customized (#21134) [Storage]
- [ ] [Design] Tracing story for LRO (#10969) [Internal/AutoRest]
- [ ] [FEATURE REQ] Create article about connection pools and related configuration (#22245) [Storage]
- [ ] Unhandled exceptions in Reactor Scheduler threads could cause hangs (#21693) [Storage]
- [x] [FEATURE REQ] Need a way to test scenarios that run with restricted resource settings (#20712) [Storage]
- [ ] Azure core poller flux to support context passing (#9762) [Internal/AutoRest]
- [ ] Support sending multipart/form-data in RestProxy (#8702) [AutoRest]
- [x] [FEATURE REQ] Support URL with multiple query param with same same (#13124) [AutoRest/Management]
- [ ] [FEATURE REQ] Fail build if deprecated api is used in samples. (#21349) [Storage]
- [x] Investigate Support Additional Body Types in HttpRequest (#19025) [LLC]

_Performance Enhancements_

- [ ] Investigate retaining buffers during subscription lifetime (#8053)
- [ ] Configurable chunk-size for azure-core-netty (#8054)
- [ ] [FEATURE REQ] Add sendFile API to HttpClient (#13099)
- [x] Investigate getBodyAsInputStream API for HttpResponse (#16035)
- [ ] Investigate Zero Second Retry Delay Handling (#18475)
- [ ] Less Eagerly Request Upstream Emissions when Sending Request (#18680)
- [x] Investigate Less Eager Requests when Sending Network Data (#19010)
- [ ] Investigate using MappedByteBuffer when Sending a File as a Request Body (#19283)
- [x] Investigate Leveraging Jackson AfterBurner/Blackbird (#19284)
- [ ] Investigate Optimizing JsonFlatten Serialization (#21505)
- [x] Investigate ClientBuilderBase (#22219)

_Reliability/Supportability_

- [ ] Resilient Jackson Multi-Version Support (#20998)
- [ ] Resilient Reactor Multi-Version Support (#22033)
- [ ] Onboarding to azure-sdk-bom (#22034)
- [ ] Increase cadence at which we ship azure-sdk-bom (#21308)
- [ ] Add Documentation on Resolving Dependency Conflicts (#12389)
- [ ] Investigate ways to decouple common conflicting dependencies (#21307)
- [ ] Create a Guideline on How Error Messages Should be Raised and Formatted (#22486)
- [ ] Add more details to key concept in azure-core readme (#13388)
- [ ] Document the Architecture of azure-core (#19142)
- [ ] Investigate Redacting Sensitive Information from Error Messages (#7896)
- [x] [BUG] Revisit ReactorNettyHttpResponse::close() (#10467)
- [ ] Update NO_PROXY Handling Based on Guideline Clarification (#7795)
- [ ] Additional Telemetry Metadata (#11685)
- [ ] Consider adding support for json.env files to Test Framework (#16014)
- [ ] [August 2021] Release azure-sdk-bom & publish the bom roadmap (blog update) (#20168)
- [ ] [BUG] Connection reset by peer is not handled well by retry policy (#21091)
- [ ] Investigate creating azure-sdk-dependencies (#21306)
- [ ] Logging: create logback policy to push log files to a data store (#21833)

_Tooling_

- [x] Add Artifact Validation in Release Pipeline  (#15894)
- [x] Support Multi-Version JARs (#19160)
- [x] Standardize Java Version Build Trigger for Module Based Builds (#19273)
- [x] Create Tooling to Automate Patch Release Branch Creation (#19400)
- [x] Weekly Multi-Version Dependency Test Runs (#20514)
- [x] Create Tooling to Generate SDK to Dependency Version Compatibility Chart (#21220)
- [x] Investigate Using Dependency Version Ranges (#22217)

**Comment by alzimmermsft** [comment]
Closing as this was a tracking issue and tracking has migrated to a new location
