### ISSUE TITLE
Dependency management and unification with Spring's bom and azure-sdk-bom

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#21283]
## Description

One of the problems we have is that there are dependency conflicts between the boms shipped from Spring and our azure-sdk bom. We need a way to resolve it.  

### Option 1

A layered approach where the boms use [azure-sdk-bom](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-sdk-bom).
1. [azure-spring-cloud-dependencies](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-spring-cloud-dependencies)
2. [azure-spring-boot-bom](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/boms/azure-spring-boot-bom)

### Option 2

We ship another `azure-sdk-dependencies` bom that `azure-spring-cloud-dependencies` and `azure-spring-boot-bom` use. Investigation work item #21306 

### General

- [ ] #21306: Investigate efforts to using Option 2
- [ ] #21307: Investigate ways to decouple common conflicting dependencies
    - [ ] #20998: Resilient Jackson Multi-Version Support
    - Possibly sub-issues will be created for implementing a solution
- [ ] #21308: Increase the cadence at which we ship the azure-sdk-bom
    - This is at the end so we don't have it lost amongst the work 

### Tooling

- [ ] #15512: Ability to ship multiple versions of the spring starters with our versions of Azure SDK.
    - The Spring team has to concurrently support multiple versions of Spring (ie. 2.2, 2.3, 2.4) with their starters. We need some way to be able to ship them with our versions of the Azure SDK.
    - Possible consideration is different artefact names.
    - What about the starters that we have shipped GA already, what would we use?
        - Relocation package? (https://maven.apache.org/guides/mini/guide-relocation.html)
- [ ] #21305: Tests that verify our versions shipped in azure-sdk work with the Spring versions they ship.
    - [ ] #20514: Weekly multi-version dependency runs.
- [ ] #21220: Tooling to Generate SDK to dependency version compatibility

## Notes

* Spring Boot dependencies: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/
* Spring Cloud dependencies: https://repo.maven.apache.org/maven2/org/springframework/cloud/spring-cloud-dependencies/
* Our Azure Spring's dependencies are updated via: [update_spring_managed_external_dependencies.py](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/scripts/update_spring_managed_external_dependencies.py)
  * Output [spring_managed_external_dependencies.txt](https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/scripts/spring_managed_external_dependencies.txt)

**Comment by joshfree** [comment]
Tagging @pallavit who is working on the azure-sdk-bom tooling and increasing the shipping cadence of the bom to monthly this semester

**Comment by saragluna** [comment]
FYI, the latest version of Spring Cloud Azure BOM has been renamed to [spring-cloud-azure-dependencies](https://search.maven.org/artifact/com.azure.spring/spring-cloud-azure-dependencies) and it shipped with the `azure-sdk-bom`.  Check the ref doc for more details https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html#bill-of-material-bom.

**Comment by stevenylai** [comment]
Hi, in our case, we want to use a specific version of Azure library and would like to find the most recent spring starter which works with it. The one we want is: `azure-schemaregistry-kafka-avro:1.0.0-beta.7` which depends on `azure-data-schemaregistry:1.1.1`. We also want to use `azure-sdk-bom` since we have other services such as CosmosDB in our projects. The 'schemaregistry' version we need is from `azure-sdk-bom:1.2.1`. But from [version table](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping) it's not clear if it's OK to upgrade our SpingBoot from 2.6.x to 2.7.x. We tried 2.7.4 but got the same 'NoSuchMethodError: reactor.core.publisher.MonoSink.contextView()' error as shown [here](https://github.com/Azure/azure-sdk-for-java/issues/17986#issuecomment-852695145).

It looks like the not found method was [introduced](https://github.com/reactor/reactor-core/blob/v3.4.18/reactor-core/src/main/java/reactor/core/publisher/MonoSink.java) in `reactor-core:3.4.18` and we are better off staying with no later than `spring-boot-starter-webflux:2.6.7`

It would be nice if the version table could also provide this kind of information

**Comment by saragluna** [comment]
@stevenylai you could find it from our changelog https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md, and the Spring Cloud Azure version compatible with `azure-sdk-bom` version `1.2.1` is https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/spring/CHANGELOG.md#410-2022-05-05.
