### ISSUE TITLE
[Epic] Make all Spring Cloud Azure libraries can work with spring-webflux

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#21290]
This is an epic issue used to track all tasks related to this topic.

### Context

Now Spring Cloud Azure libraries are developed with dependencies of [Spring Web MVC](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#spring-web).

### Problem
When customer use [Spring WebFlux](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html), Spring Cloud Azure libraries may not work well.

### Goal
 Make all Spring Cloud Azure libraries be able to work with [Spring WebFlux](https://docs.spring.io/spring-framework/docs/current/reference/html/web-reactive.html). 

### Tasks

 - [ ] https://github.com/Azure/azure-sdk-for-java/issues/26620
 - [ ] https://github.com/Azure/azure-sdk-for-java/issues/18270
 - [ ] Most of our health indicators should be org.springframework.boot.actuate.health.AbstractReactiveHealthIndicator to take advantage of Azure SDK's reactive support.

**Comment by saragluna** [comment]
Since the Spring Cloud Azure 4.0 beta has been released, we should make sure all our Spring Cloud Azure 4.0 starters can work with Web MVC and Web Flux.

**Comment by wanisfahmyDE** [comment]
Hey @chenrujun ,

I hope i'm in the right place asking this.
Is there updates on that topic or an ETA, to have support for webflux?

Thank you

**Comment by chenrujun** [comment]
Hi, @wanisfahmyDE 

Now we do not have ETA.

**Comment by wanisfahmyDE** [comment]
> 

thanks @chenrujun, is there a way to achieve this natively with spring boot security? if so, can you please share a documentation or example for that?
many thanks

**Comment by chenrujun** [comment]
@wanisfahmyDE .

Maybe you can use spring-security directly. Here is the link to related doc: https://docs.spring.io/spring-security/reference/reactive/oauth2/index.html

**Comment by stliu** [comment]
I'm change the priority to 3, means we don't consider webflux support in this semester , vote this issue if you need more team attention
