### ISSUE TITLE
Resolve day-1 experience related bugs

### ISSUE THREAD

**Issue by z1069867141** [Azure/azure-sdk-for-java#21497]
https://msazure.visualstudio.com/Unified%20Platform%20KPIs/_queries?tempQueryId=1399c6d3-39c4-4982-ba88-30a1a1705e47

- [ ] #21488: Resolve day-1 experience related bugs - Key Vault
- [x] #21480: <del>Resolve day-1 experience related bugs - gremlin
- [ ] #21479: Resolve day-1 experience related bugs - Event Hubs
- [ ] #21476: Resolve day-1 experience related bugs - App Config 
- [ ] #21478: Resolve day-1 experience related bugs - Misc
- [ ] #21477: Define solution for coordinating version numbers between "latest release" and "content on docs.microsoft.com"
- [x] #21475: <del> Resolve day-1 experience related bugs - GitHub

**Comment by saragluna** [comment]
Closing in favor of #21759
