### ISSUE TITLE
[TA] June Epic, road to GA

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#21653]
- Implementation
  - [x] Codegen based on the latest swagger. https://github.com/Azure/azure-rest-api-specs/blob/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.1-preview.5/TextAnalytics.json
  - [x] API Design issue: https://github.com/Azure/azure-sdk-for-net/issues/21174#issuecomment-844248932
- Service Bugs:
  - [x] https://github.com/Azure/azure-sdk-for-java/issues/21642
  - [ ] https://github.com/Azure/azure-sdk-for-java/issues/19672
  - [x] https://github.com/Azure/azure-sdk-for-java/issues/19568
  - [ ] https://github.com/Azure/azure-sdk-for-java/issues/13841
- Doc and Samples:
  - [x] https://github.com/Azure/azure-sdk-for-java/issues/21140
  - [x] https://github.com/Azure/azure-sdk-for-java/issues/16694
- Test and Performance Improvement
  - [ ] https://github.com/Azure/azure-sdk-for-java/issues/20265
  - [x] https://github.com/Azure/azure-sdk-for-java/issues/13943
