### ISSUE TITLE
[FR] July Epic after GA 2.1

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#21687]
No code complete date for FR this time. Only Design works.

- [ ] API design on the breaking changes 
```
Once 2.1 GA is out the door, we will need to go through the new API and make lists, by language, of items that can/can't be reconciled between the 2.x SDK API and the 3.0 REST API. This is going to take a bit of design work on all of our parts to figure out what we can push on the service team to change, what we can change in our clients, and where we can possibly meet in the middle, then open a discussion with the architects and the service team.
	This is the first time this kind of situation has been proposed, where we will have a breaking change between two Track 2 versions, and no straightforward way around it, so we will have to be creative, and it's possible that JS/Python (where our versioning scheme allows us to make breaking changes between major versions) will decide to go a different direction than .NET/Java in how we approach it.

It seems like we are approaching a decision that the Azure SDK org has more-or-less put off making for a while about how we approach this situation, whether we value inter-language consistency or language idiomaticity more, so FR may end up being a kind of forcing function for our org to make decisions in this respect.
```

- [ ] cause: "expected: <com.azure.core.exception.HttpResponseException> but was: <java.lang.RuntimeException>"
recognizeReceiptFromUrlWithEncodedBlankSpaceSourceUrl
recognizeContentFromUrlWithEncodedBlankSpaceSourceUrl
recognizeBusinessCardFromUrlWithEncodedBlankSpaceSourceUrl
recognizeInvoiceFromUrlWithEncodedBlankSpaceSourceUrl

- [ ] Support Form Recognizer testing in all azure clouds #19176 [WIP]
- [ ] Support code is written customization to minimize handwritten translation layers #20572 [WIP]
- [ ] Improvement to perf analysis and testing Form Recognizer #20708

- [x] https://github.com/Azure/azure-sdk-for-java/issues/21633

**Comment by samvaity** [comment]
> cause: "expected: <com.azure.core.exception.HttpResponseException> but was: <java.lang.RuntimeException>"
recognizeReceiptFromUrlWithEncodedBlankSpaceSourceUrl
recognizeContentFromUrlWithEncodedBlankSpaceSourceUrl
recognizeBusinessCardFromUrlWithEncodedBlankSpaceSourceUrl
recognizeInvoiceFromUrlWithEncodedBlankSpaceSourceUrl


<img width="658" alt="prebuilt_timeout" src="https://user-images.githubusercontent.com/16845631/124553097-2c94cd80-dde9-11eb-861b-5e7eb0704080.png">
