### ISSUE TITLE
[Epic] Spring samples

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21753]
This is an epic including all Spring samples related work:
- [x] #21745: Move all the Spring related samples to Azure Samples
- [x] #21501: Create new samples and revamp existing sample structure
- [x] #20718: List Spring sample README to the doc site
- [x] #21498: E2E sample demonstrating interaction with AAD, externalized configurations, secret management and data persistence layer with Azure data services
- [x] #21474: Create a Spring Boot/Spring MVC E2E sample to demonstrate usage of Spring Azure modules
- [x] #21473: E2E sample demonstrating interaction metrics/logging gathering and processing, messaging, ML and CI/CD

**Comment by stliu** [comment]
closing this one, we need to plan and design what should we do to improve samples
