### ISSUE TITLE
[Epic] Spring observability

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21761]
This is an epic including all Spring observability related work:

- [x] <del>#21543: Integrating Spring Sleuth and Zipkin with Azure Service Bus SDK
- [x] #21768: Define the scopes of Spring observability - Metrics
- [x] #23370
- [x] #21969: Define the scopes of Spring observability - Tracing

## Tracing 
- [ ] #21760: Enhance tracing for Azure Spring messaging components
  - [ ] Tracing is broken https://github.com/Azure/azure-sdk-for-java/issues/23035 
  - [ ] Bug: Fix context propagation issue in eventhub/servicebus binders 
- [ ] #21762: Enhance tracing for Azure Spring security components
- [ ] #21763: Enhance tracing for Azure Spring database/storage components
  - [x] https://github.com/Azure/azure-sdk-for-java/issues/23032
  - [ ] Storage queue: when receiving messages no span is created 

## Metrics
- [ ] #21764: Enhance metrics for Azure Spring messaging components
- [ ] #21765: Enhance metrics for Azure Spring security components
- [ ] #21766: Enhance metrics for Azure Spring database/storage components
  - [ ] Could not find any cosmos metrics reported despite being enabled when using app insights.

## Docs
- [x] #23621

**Comment by stliu** [comment]
with this PR https://github.com/Azure/azure-sdk-for-java/pull/29086, I think we can restart this issue
