### ISSUE TITLE
Nickel (2021.06 - 2021.12) feature list about Azure Spring Cloud Event Hubs / Service Bus libraries

### ISSUE THREAD

**Issue by yiliuTo** [Azure/azure-sdk-for-java#21806]
- [ ] [Event Hubs feature lists](https://github.com/Azure/azure-sdk-for-java/issues/21558)
   - [ ] #21547 : Support messaging replay of EH 
   - [x] #21549: Make Storage account optional 
   - [x] #21555: batch consumers
   - [x] #21556: More consumer properties 
   - [x] #21557: More producer properties 
   - [x] #16596: Set AmqpRetryOptions for EH connection 

- [ ] [Service Bus feature lists](https://github.com/Azure/azure-sdk-for-java/issues/21546)
   - [ ] #21540: Support DLQ receiver 
   - [x] #21542: More consumer/producer properites 
   - [ ] #21545: Batch consumers 
   - [ ] #21538: Sync/async client 
   - [x] #17421: Set receive mode 

- [ ] [Service Bus JMS starter feature lists](https://github.com/Azure/azure-sdk-for-java/issues/21535)
   - [ ] Support more connection properties.

**Comment by stliu** [comment]
close this one, we don't track Nickel anymore
