### ISSUE TITLE
[TaskList] Nickel (2021.06 - 2021.12) feature list about cosmosdb and storage

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#21813]
## Storage components related issues:
- [ ] #21766 Enhance metrics for Azure Spring database/storage components 
- [ ] #21763 Enhance tracing for Azure Spring database/storage components
- [ ] #21462 Spring Storage - Enable retry policy for storage
- [ ] 8️⃣#21461 Spring Storage - Support AppendBlobResource and PageableBlobResource in azure-spring-cloud-storage
- [x] #21486
- [x] #22707
- [x] #21460 ~Spring Storage - Enable authentication via app id and secret~
- [x] #21459 ~Spring Storage -Enable authentication via managed identity~ -- should be resolved by a consistency way

## DataBase
- [x] #21498 [it has related implementation] ~Spring - E2E sample demonstrating interaction with AAD, externalized configurations, secret management and data persistence layer with Azure data services~
- [ ] #21493 Spring Database - Create JDBC starters for credential-less connections

## **Cosmos DB**

- [ ] 🅿️#21440 Spring Cosmos - Support change feed 
- [ ] 🅿️#21442 Spring Cosmos - Support bulk exeutor
- [ ] #21432 Spring Cosmos - Support Spring data REST access 
- [x] #21434 Spring Cosmos - Support Spring actuator
- [ ] #21448 Spring Cosmos - Support metrics

## [ SQL Server R2dbc](https://github.com/Azure/azure-sdk-for-java/issues/21607)
- Improve SQL server r2dbc library related
> R2DBC stands for Reactive Relational Database Connectivity, a specification to integrate SQL databases using reactive drivers. 

- [x]  #21602 Support SQL Variant 
- [x]  #21603 Support XML data types
- [x]  #21604 Support user defined types 
- [x]  #21605 Support call stored procedure
- [x] #21454  Sketch approach for credential free access to Azure RDBMS from Spring

**Comment by stliu** [comment]
close this one, we dont use this issue to track nickel issues anymore
