### ISSUE TITLE
Azure Core for Java (July 2021)

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#21897]
This contains all issues we plan to resolve by the end of the July 2021 release cycle. Additionally, this contains stretch goal issues which may be resolved in the release cycle.

_Partner Requests_

- [x] Add RequestContent to azure-core #21896
- [x] Add ResponseContent to azure-core #22434
- [x] Support Additional Configurations in HttpClientOptions #21193
- [x] [Feature Request] Add Request and Response Logging Hooks to HttpLoggingPolicy #11477

_Reliability_

~~- [ ] Unhandled exceptions in Reactor Scheduler threads could cause hangs #21693~~ _Moved to #21898_

_Performance Enhancements_

~~- [ ] [FEATURE REQ] Share HttpClient if not customized #21134~~ _Moved to #21898_

_Supportability_

- [x] Document Serialization and Deserialization Guidelines of JacksonAdapter #20997

_Stretch Goals_

~~- [ ] Logging: create logback policy to push log files to a data store #21833~~
- [x] Review HttpRequest Body Reading in HttpPipelinePolicies #14917
~~- [ ] Introduce JDK 13 to live test matrix #10465~~
- [x] Flakey test: ReactorNettyClientTests.testConcurrentRequests #4357
