### ISSUE TITLE
Azure Core for Java (August 2021)

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#21898]
This contains all issues we plan to resolve by the end of the August 2021 release cycle. Additionally, this contains stretch goal issues which may be resolved in the release cycle.

_Partner Requests_

- [ ] ~~Resilient Jackson Multi-Version Support #20998~~ _Targeted for September_
- [ ] ~~Introduce JDK 13 to live test matrix #10465~~ _Targeted for October_
- [x] Investigate Using Profiles when Including OS Specific Dependencies #21217
- [x] Support Recording and Live Test Version Configurations in Testing #21171
- [x] [FEATURE REQ] azure.core.credential.AzureSasCredential Sanitize SAS for URIs #20561
- [ ] ~~Support sending multipart/form-data in RestProxy #8702~~ _Targeted for September_

_Reliability_

- [x] Investigate If JsonFlatten Should Deeply Flatten #21506
- [x] [BUG] FlatteningSerializer not work correctly for Map/List with final modifier #20150
- [x] Flakey test: ReactorNettyClientTests.testConcurrentRequests #4357

_Performance Enhancements_

- [x] Review HttpRequest Body Reading in HttpPipelinePolicies #14917

_Supportability_

- [ ] ~~Logging: create logback policy to push log files to a data store #21833~~ _Targeted for September_
- [ ] ~~Add Documentation on Resolving Dependency Conflicts #12389~~ _Targeted for September_

_Tooling_

- [ ] ~~Investigate a From Source Analyze CI Job #21637~~ _Targeted for September_
- [x] Add a Status Report for azure-sdk-bom Dependency Alignment to Daily Report Generation #19401

_Stretch Goals_

- [ ] Investigate Optimizing JsonFlatten Serialization #21505
- [ ] Create Tooling to Generate SDK to Dependency Version Compatibility Chart #21220
- [ ] Create Tooling to Automated Patch Release Branch Creation #19400
- [ ] Standardize Java Version Build Trigger for Module Based Builds #19273
- [x] Create Tooling that can Generate an azure-sdk-bom Release #21901

**Comment by alzimmermsft** [comment]
August release has shipped
