### ISSUE TITLE
Azure Core for Java (September 2021)

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#21899]
This contains all issues we plan to resolve by the end of the September 2021 release cycle. Additionally, this contains stretch goal issues which may be resolved in the release cycle.

_Partner Requests_

- [ ] Create Tooling Capable of Creating a Sync Client from an Async Client #20512
- [ ] Support Using Tests as Javadoc and README Codesnippets #21902

_Reliability_

_Performance Enhancements_

- [ ] Investigate Optimizing JsonFlatten Serialization #21505

_Supportability_

- [x] Standardize Java Version Build Trigger for Module Based Builds #19273
- [x] Weekly Multi-Version Dependency Test Runs #20514

_Tooling_

- [x] Create Tooling to Generate SDK to Dependency Version Compatibility Chart #21220
- [x] Create Tooling to Automated Patch Release Branch Creation #19400
- [x] Create Tooling that can Generate an azure-sdk-bom Release #21901

_Stretch Goals_

**Comment by alzimmermsft** [comment]
Closing as September release has been shipped
