### ISSUE TITLE
[Epic] Make Azure Spring starters production ready

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#21970]
This is an epic to track all production-ready issues:

- [x] #22702: Unify user experience when using all Azure Spring starters
- [x] #21770: Spring multiple version support policy
- [ ] #21973: Make sure Spring Retry work with Azure SDK retry policy for all modules

**Comment by stliu** [comment]
since there is only one issue left, I'm clsoing this epic
