### ISSUE TITLE
Tooling for Java (Nickel Semester)

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#22216]
This contains all tooling issues we plan to resolve each month until the end of 2021. This issue only forecasts the next three months, past that it falls into an `unassigned` bucket and each month this will be updated.

_July 2021_

- [x] Add a Status Report for azure-sdk-bom Dependency Alignment to Daily Report Generation (#19401)
- [x] Add Dependency Version Management Tags to azure-sdk-bom (#19402)

_August 2021_

- [x] Add Artifact Validation in Release Pipeline (#15894)
- [x] Create Tooling to Automate Patch Release Branch Creation (#19400)
- [x] Revert TestMode Default Back to LIVE (#19660)

_September 2021_

- [x] Create Tooling to Generate SDK to Dependency Version Compatibility Chart (#21220)
- [ ] Enable way for pipelines to specify additional options to maven without overriding everything. (#21903)

_Unassigned_

- [ ] Investigate Logging Linting Errors to File in CI (#15349)
- [ ] Add README Version Validation in Release Pipeline (#15870)
- [ ] Create Utility to Generate Javadoc Codesnippet Stubs (#18988)
- [x] [FEATURE REQ] Need a way to test scenarios that run with restricted resource settings (#20712)
- [x] Weekly Multi-Version Dependency Test Runs (#20514)
- [ ] Consider adding support for json.env files to Test Framework (#16014)
- [x] Investigate Using Dependency Version Ranges (#22217)
