### ISSUE TITLE
Unify user experience when using all Azure Spring starters

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#22702]
When users use different Azure Spring starters, they expect to have a unified experience configuring azure sdk properties, creating credentials, and Spring-related functions.

- [x] The consistent user experience when configuring properties (#23421)
- [x] The consistent user experience when providing credentials (#21472)
  - [x] Since Azure SDKs should support TokenCredential, we need to provide this capability in our starters:
    - [x] Support TokenCredential in all **storage/database** area starters (#21486)
    - [x] Support TokenCredential in all **messaging** area starters (#22704)
    - [x] Support TokenCredential in all **security** area starters (#22705)
    - [x] Support TokenCredential in all **app config** starters (#22706)
  - [x] Different authentication methods are supported in different Azure SDKs other than TokenCredential, we should support all authentication methods an Azure SDK supports in our starters:
    - [x] Support other authentication methods in all **storage/database** area starters (#22707)
    - [x] Support other authentication methods in all **messaging** area starters (#22708)
    - [x] Support other authentication methods in all **security** area starters (#22709)
    - [x] Support other authentication methods in all **app config** area starters (#22710)
- [x] When Spring Boot Actuator is used and health endpoint is enabled in Spring Boot projects, health indicators are expected to indicate components' health status. We should support this in all our starters. (#21974)
  - [x]  Support in **messaging** components (#21976)
  - [x]  Support in **storage/database** components (#21977)
  - [x]  Support in **security** components (#21979)
  - [x]  Support in **app config** components (#21982)

**Comment by saragluna** [comment]
Closing this in favor of https://github.com/Azure/azure-sdk-for-java/issues/23402.
