### ISSUE TITLE
[TA-Epic] 3.2-preview.1 Extractive Summarization 

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#22988]
- [x]  Regenerate code by using v3.2-preview.1 swagger.
- [x]  Clean up duplicate and unused generated classes: such as `TasksStateTasksEntityLinkingTasksItem` and  `EntityLinkingTaskResult`.
- [x] Implementation + CHANGELOG + README + samples
