### ISSUE TITLE
[Epic] Spring Cloud for Azure 4.0

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#23402]
# Design Doc
- [x] #23920 
- [x] Design for a core module. [Spring Cloud for Azure 4.0 Core](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-Core-design)
- [x] #23624 
- [x] #23691
- [x] #23693
- [x] #23690
- [x] #23369

# Beta release
Things has to be done within our Beta Release:

- [x] #24260 

## Project structure

- [x] A separate resource-manager module, which is optional, and when provided, could bring the ability to provision resources.
- [x] #24330 
- [x] #23930
- [x] #24329
- [x] #24812

## Maven Artifact 

- [x] #23931
- [x] #24360
- [x] #24722 

## Improve Azure SDK Configuration support
  - [x] #23421
    - [x] #21972 
    - [x] #23367 
    - [x] #21552 
    - [x] #24754 Support configure retry.
    - [x] #25221
    - [x] #24656
    - [x] #16596 
    - [x] #21336
    - [x] #21593 
    - [x] #25223
    - [x] #25222
  - [x] #24658
  - [x] #24659
  - [x] #24657

## Improve Authentication
  - [x] Support TokenCredential for all SDK client auto-configuration
      - [x] #21486 
      - [x] #22704
      - [x] #22706
  - [x] Support other authentication methods than TokenCredential for all SDK client auto-configuration
    - [x] #22707 
    - [x] #22708
    - [x] #22709
    - [x] #22710 

 
### Health Indicator
 - [ ] #21976 
 - [x] #21977 
 - [x] #21979 
 - [x] #25225

### Tracing
 - [x] #21969

## Messaging
- [x] #22755
- [x] #23919
- [x] #23688
- [x] #25192
- [x] #25191
- [x] #25226
- [x] #25363

## Security
- [x] #23710
  - [x] #23932
  - [x] #23922
  - [x] #23942
  - [x] #24353

## Docs + Samples + Misc
- [x] #24334
  - [x] #24336
  - [x] #24335
- [x] #24351
  - [x] #24403 
  - [x] #24394
  - [x] #24397
  - [x] #24399
  - [x] #24396
  - [x] #24400
  - [x] #24401
  - [x] #24402
  - [x] #24393
  - [x] #24395

### Clean up starter module, to make it does dependency management only
- [x] #23926 
- [x] #23938
  - [x] #24392 
  - [x] #24384
  - [x] #24387
  - [x] #24388
  - [x] #24357
  - [x] #24385
  - [x] #24386
  - [x] #24389
  - [x] #24390
  - [x] #24391
----

# GA release

## GA Exit Criteria
 - [x] Other features
   - [x] #25646
 - [x] #25663 
 - [x] Doc @chenrujun 
    - [x] https://github.com/microsoft/spring-cloud-azure/issues/783
    - [x] https://github.com/microsoft/spring-cloud-azure/issues/784
    - [x] https://github.com/microsoft/spring-cloud-azure/issues/785
    - [x] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/95
    - [x] https://github.com/Azure/azure-sdk-for-java/issues/26307
 - [x] Blog @seanli1988 
 - [x] Sample @backwind1233 
   -  [x] #25651
   -  [x] #25652
 - [x] #25683
 - [x] #25697 @hui1110 
 - [x] #25684
 - [x] #24332
   - [x] #24409
   - [x] #24410
   - [x] #24411
   - [x] #24412
     - [x] #24359
- [x] #23773
  - [x] #24354
  - [x] #24363
- [x] #24469
- [x] #25224
- [x] #25054
- [x] https://github.com/Azure/azure-sdk-for-java/issues/27112
- [x] #24356
  - [x] #24413
  - [x] #24414
  - [x] #24415
  - [x] #24416
- [x] #25892
- [x] https://github.com/Azure/azure-sdk-for-java/issues/27350
- [x] https://github.com/Azure/azure-sdk-for-java/issues/25892
- [x] https://github.com/Azure/azure-sdk-for-java/issues/27303
- [x] #27480
- [x] Reference docs are up to date.
- [x] #27492
- [x] #27481

## Release
- [x] #26300
- [x] #24327 
- [ ] #24362  

---
# Post GA
- [ ] #19696 
- [ ] #25228
- [ ] #24369
- [ ] #22705
- [ ] #21976
- [x] #25698
- [x] #25699
- [x] #25700
### Metrics
- [ ] #21764
- [ ] #23400
## Ensure test coverage
- [x] #24333
  - [x] #24405
  - [x] #24406
  - [x] #24407
  - [x] #24408
    - [x] #24358

**Comment by saragluna** [comment]
Closing this issue now, the post-ga part will be logged in https://github.com/Azure/azure-sdk-for-java/issues/28000.
