### ISSUE TITLE
[TA] Nov Epic: Custom Features, Testing, Investigation

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#24548]
Main focus: 
- [x] https://github.com/Azure/azure-sdk-for-java/issues/24546
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/24547

Others:
- [x] https://github.com/Azure/azure-sdk-for-java/issues/24186
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/24183
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/23361
