### ISSUE TITLE
Tasks for new spring-boot versions: 2.5.7 and 2.4.13

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#24988]
Copied from here: https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release

Spring boot released [spring-boot v2.5.7] and [spring-boot v2.4.13]. we need do the following tasks.

# Task list
- Before azure-sdk-for-java in band release
  - [ ] Upgrade spring-boot and test compatibility. Sample issue: [azure-sdk-for-java#24291].

- After azure-sdk-for-java in band release.
  - [ ] Update version and screenshot in MS docs. [MS docs about spring framework]
  - [ ] Update version in azure-spring-boot-samples. Sample PR: [azure-spring-boot-samples#62].
  - [ ] Update related wiki pages: `Spring-Support-Multiple-Versions.md`, `Spring-Versions-Mapping.md`.

Since we can't finish these tasks in this month, so I assign this issue to @saragluna instead of @backwind1233 .

[spring-boot v2.5.7]: https://github.com/spring-projects/spring-boot/releases/tag/v2.5.7
[spring-boot v2.4.13]: https://github.com/spring-projects/spring-boot/releases/tag/v2.4.13
[azure-sdk-for-java#24291]: https://github.com/Azure/azure-sdk-for-java/issues/24291
[azure-spring-boot-samples#62]: https://github.com/Azure-Samples/azure-spring-boot-samples/pull/62
[MS docs about spring framework]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/

**Comment by moarychan** [comment]
Close this issue now due to this issue https://github.com/Azure/azure-sdk-for-java/issues/25581.
