### ISSUE TITLE
[Epic] All Samples of using Azure Active Directory in Spring Boot application.

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#25817]
- [ ] Azure Active Directory
    - [ ] Servlet Applications
      - [ ] OAuth2 (OpenID)
        - [ ] Login
        - [x] client
        - [x] resource-server
        - [x] resource-server check-permission by claims in access-token
        - [x] client access resource-server
        - [x] client access multiple resource-server
        - [x] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
    - [ ] Reactive Applications
      - [ ] OAuth2
        - [ ] Login
        - [ ] client
        - [ ] resource-server
        - [ ] resource-server check-permission by claims in access-token
        - [ ] client access resource-server
        - [ ] client access multiple resource-server
        - [ ] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway

TODO: Create a new repo named: spring-boot-application-with-azure-active-directory-b2c
 - [ ] Azure Active Directory B2C
    - [ ] Servlet Applications
      - [ ] OAuth2
        - [ ] Login
        - [ ] client
        - [ ] resource-server
        - [ ] resource-server check-permission by claims in access-token
        - [ ] client access resource-server
        - [ ] client access multiple resource-server
        - [ ] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
    - [ ] Reactive Applications
      - [ ] OAuth2
        - [ ] Login
        - [ ] client
        - [ ] resource-server
        - [ ] resource-server check-permission by claims in access-token
        - [ ] client access resource-server
        - [ ] client access multiple resource-server
        - [ ] On-Behalf-of flow
        - [ ] MFA
        - [ ] Gateway
      - [ ] SAML2 
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway
      - [ ] LDAP
        - [ ] Login
        - [ ] Logout
        - [ ] MFA
        - [ ] Gateway

**Comment by chenrujun** [comment]
Hi, @stliu , @seanli1988 

`Spring Cloud AWS` and `Spring Cloud GCP` only support one scenario: resource-server.
The main feature they provided is validate the `aud` claim.
The `aud` claim validation feature will supported by Spring Boot natively, tracked by this issue: https://github.com/spring-projects/spring-boot/issues/28427 


But `okta-spring-boot` support web-application. For web-application, there are a lot of scenarios, now I prefer to write samples instead of release a starter because:  These scenarios can be achieved by configuring spring-security. It's not easy to our starter to cover all scenarios.


Refs:
1. https://github.com/awspring/spring-cloud-aws/blob/2.3.x/spring-cloud-aws-autoconfigure/src/main/java/io/awspring/cloud/autoconfigure/security/CognitoAuthenticationAutoConfiguration.java
2. https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-autoconfigure/src/main/java/com/google/cloud/spring/autoconfigure/security/FirebaseAuthenticationAutoConfiguration.java
3. https://github.com/okta/okta-spring-boot/tree/master/oauth2/src/main/java/com/okta/spring/boot/oauth

**Comment by clavinovahan** [comment]
@chenrujun, if gateway in the folder structure above means Spring Cloud Gateway, it is built on top of spring webflux and maybe its OAuth2 sample shall be listed only in Reactive Applications branch instead of both Servlet and Reactive Applications branches?

**Comment by chenrujun** [comment]
@clavinovahan .

Thank you for your information.
Now I'm not very clear about these features.
For example: whether SAML2 and LDAP scenario needs sample about Gateway.

Now I just list all scenarios I can image. And I'll mark them as finished if one of the following thing happened:
1. Sample finished.
2. Find out that this scenario does not exist.

**Comment by chenrujun** [comment]
Closing this issue. Current plan is providing sample when there is customer ask.
