### ISSUE TITLE
Tasks for spring-boot 2.6.2 and 2.5.8

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#26146]
Spring Boot released [2.6.2](https://github.com/spring-projects/spring-boot/releases/tag/v2.6.2) and [2.5.8](https://github.com/spring-projects/spring-boot/releases/tag/v2.5.8). We should do following tasks.

# Task list
- Before azure-sdk-for-java in band release
  - [x] Read spring boot release notes. Sample: [Spring-Boot-2.6-Release-Notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes).
  - [x] Upgrade dependencies' version according to spring-boot-dependencies and spring-cloud-dependencies. Sample issue: [azure-sdk-for-java#24291](https://github.com/Azure/azure-sdk-for-java/issues/24291).

- After azure-sdk-for-java in band release.
  - [ ] Update [azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples)
  - [ ] Update [CHANGELOG](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring).
  - [ ] Update [Reference doc](https://github.com/microsoft/spring-cloud-azure/tree/docs/docs/src/main/asciidoc).
  - [ ] Update [MS docs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/).
  - [ ] Update related wiki pages: [Spring-Support-Multiple-Versions](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Support-Multiple-Versions), [Spring-Versions-Mapping](https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Versions-Mapping).

Task list is copied from this page:
https://github.com/Azure/azure-sdk-for-java/wiki/Spring-Cloud-Azure-tasks-for-a-new-Spring-Boot-release

**Comment by chenrujun** [comment]
Hi, @Netyyyy , could you please help to handle this task?

**Comment by chenrujun** [comment]
> Upgrade dependencies' version according to spring-boot-dependencies and spring-cloud-dependencies. Sample issue: azure-sdk-for-java#24291.

Hi, @alzimmermsft .
I see you created #26389 and #26286.
How about always use this issue to upgrade external dependencies' version?
So we can make sure all external dependencies' versions are align to spring-boot-dependencies.

**Comment by chenrujun** [comment]
Reopen this issue because not all tasks in the checklist are checked.

**Comment by Netyyyy** [comment]
spring-boot now has a new version, so close it and works on https://github.com/Azure/azure-sdk-for-java/issues/26887
