### ISSUE TITLE
[Epic] Update MS docs: Spring Cloud Azure 4.0

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#26307]
Copied from https://github.com/Azure-Samples/azure-spring-boot-samples/issues/95

# Target page:
 - https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
 - GitHub: https://github.com/MicrosoftDocs/azure-dev-docs-pr

**Note** that your PR should be a draft PR before 4.0 GA. And assign @chenrujun as assignee in your created draft PR.

# Tasks

## Before GA release.

1. Update project name to `Spring Cloud Azure`.
2. Update artifactId and version. (4.0 GA version)
3. Update package name / class name.
4. Update property prefix.
5. Add link to reference doc: https://microsoft.github.io/spring-cloud-azure

## After GA release

1. Change link in MS docs into tag instead of version. For example, link to azure-sdk-for-java repo, azure-spring-boot-samples repo.

# Sub Tasks

## Screenshot of sub tasks
![image](https://user-images.githubusercontent.com/13167207/143145131-e078c2ee-680a-4b10-8b3b-9f2499eb9bf1.png)
![image](https://user-images.githubusercontent.com/13167207/143145407-1a93f1e1-a35b-45dd-93c7-fd16ea8417f5.png)

## Sub task table

 - We use one PR to contain all changes: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2487
 - @backwind1233, @yiliuTo , @Netyyyy , @hui1110 , please merge you branch to `chenrujun:spring-cloud-azure_4.0` instead of `master`.
 - Then we can get the preview page in this page: https://review.docs.microsoft.com/en-us/azure/developer/java/spring-framework/?branch=pr-en-us-2487

:x: : Not Finished.
:heavy_check_mark:  : Finished.

| Sub page                                  | GitHub Issue | assignee             | page updated ?        | QA tested?  | 
| --------------------------------- | -------------- | ------------------ | ----------------          | -------------- |
| Spring on Azure                       | https://github.com/Azure-Samples/azure-spring-boot-samples/issues/97                | @Netyyyy           | :heavy_check_mark: | :x:                  | 
| Spring Boot Starters for Azure | https://github.com/Azure-Samples/azure-spring-boot-samples/issues/98                | @hui1110           | :heavy_check_mark: | :x:                  | 
| Spring Security                         | https://github.com/Azure-Samples/azure-spring-boot-samples/issues/99                |@chenrujun         | :x:                             | :x:                  | 
| Messaging                                | https://github.com/Azure-Samples/azure-spring-boot-samples/issues/100              | @yiliuTo              | :x:                             | :x:                  | 
| Storage and database              | https://github.com/Azure-Samples/azure-spring-boot-samples/issues/101              | @backwind1233 | :heavy_check_mark:  | :x:                  | 

 - [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/97  @Netyyyy 
 - [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/98  @hui1110 
 - [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/99  @chenrujun 
 - [ ] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/100  @yiliuTo 
 - [x] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/101 @backwind1233 
 - [x] https://github.com/Azure-Samples/azure-spring-boot-samples/issues/102 @saragluna

**Comment by chenrujun** [comment]
Link to related PR: https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/2487/

**Comment by saragluna** [comment]
The PR has been merged, closing this issue now.
