### ISSUE TITLE
[TA] Language Pillar Commitments for Text Analytics (July 2021-March 2022)

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#26326]
[Azure Cognitive Service for Language](https://docs.microsoft.com/en-us/azure/cognitive-services/language-service/) is an AI service that can extract information, classify text, understand conversational language, answer questions, and more.

This issue tracks the work we have planned for this package for the duration of July 2021 - March 2022

### New features:
- [x] Adding support for extractive summarization
- [x] Adding support for Custom Text

### General improvements:
- [x] [Document the current issues in the client that affect the customer experience](https://gist.github.com/deyaaeldeen/40badd8f0460a9a3cd5965b1e4d14adf)
- [ ] Design how to integrate the client with the new Azure Cognitive Service for Language instead of the old Azure Text Analytics
  - [Service design draft](https://microsoft.sharepoint-df.com/:w:/r/teams/ALPSAzureLanguagePillars/_layouts/15/guestaccess.aspx?e=LpZZXi&share=EZPRUkaOsN1HscCEdBIvFooBsIlxftyxrfzPhHTtVko_vw)
  - [Timeline document](https://microsoft-my.sharepoint.com/:x:/p/abhahn/EcKwBxxcBuZCql_NDPfB2XsBvr3qRXGDKwvKkQJAo1s9Zw?e=FmVPNr&isSPOFile=1&sourceId=&params=%7B%22AppName%22%3A%22Teams-Desktop%22%2C%22AppVersion%22%3A%2227%2F21110108719%22%7D)
  - [Language's Conversation SDK archboard](https://github.com/Azure/azure-sdk/issues/3471)
  - [Language's Question Answering SDK archboard](https://github.com/Azure/azure-sdk/issues/3089)

### Testing improvements:
- [ ] Currently, we are using a static resource to run all tests for all languages. Investigate the possibility of dynamic allocation resource without training a new model (which is time-consuming for custom text models).
