### ISSUE TITLE
[Epic] Build spring on azure web site

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#27773]
Just like https://start.aliyun.com , we should have a web site like https://spring-on-azure.com.

 - [ ] Determine what contents this website should contain.
 - [ ] Investigate how to develop and deploy the web site.
 - [ ] Enrich the contents of the web site.

**Comment by jialigit** [comment]
Investigate and list the todos and prepare the environments?

enrich the contents: this is the next step after the above one?

**Comment by chenrujun** [comment]
@jialigit Detailed contents is not decided yet, need more discussion with our PM.

**Comment by chenrujun** [comment]
# Spring on Azure samples problems and solution proposal

## Current problems

All repositories in scope are listed in [Spring on Azure Repositories](https://microsoftapc.sharepoint.com/:x:/r/teams/Springintegration/_layouts/15/doc2.aspx?sourcedoc=%7B20276df2-2c1f-44b9-9f79-dda67874e8c2%7D&action=edit&activeCell=%27All%20repositories%27!A86&wdinitialsession=4e6a62e5-b276-48fe-bf6b-0a4b64902a6f&wdrldsc=15&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT&cid=7fef911f-0330-4628-b39c-03873c519367). 

Here is problem list:

1. I cannot find samples. 
2. Sample is not easy to follow.
3. Sample does not support all supported versions. For example: sample for spring-boot 2.5 and spring-boot 2.6 
4. Multiple similar samples.
5. Not provide the best solution. 
6. Not using supported version. For example: use spring-boot 2.2, which is not supported version.
7. Not updated for more than one year.
8. Lack of synergy between among Azure products. i.e.: samples from Spring Cloud Apps does not use Spring Cloud Azure libraries
9. Bad repo name
10. Steep learning curve.

## Solution proposal

### 1. Create 2 new repositories:
  1.1. `spring-and-azure-product-samples`. It is used to manage all Spring and Azure related samples. Customer can find required sample by Azure product name or Spring project name. Here is an example: [chenrujun/spring-and-azure-product-samples](https://github.com/chenrujun/spring-and-azure-product-samples).
  1.2. `spring-and-azure-product-sample-template`. It is the template repository, all Spring on Azure sample repositories should follow this template. Here is an example: [spring-and-azure-product-sample-template](https://github.com/chenrujun/spring-and-azure-product-sample-template)

### 2. How to solve above 10 problems by the 2 repositories.

  2.1. I cannot find samples. All samples can be found in `spring-and-azure-product-samples`. Customer can find their required sample by Azure product name or Spring project name.

  2.2. Sample is not easy to follow. The `spring-and-azure-product-sample-template` will define the required contents in README, and make sure all sample is easy to follow.

  2.3. Sample does not support all supported versions. 
      2.3.1. `spring-and-azure-product-sample-template` requires that sample repository should use different branch to support different spring-boot version.
      2.3.2. Use pipeline (For example: GitHub actions) to manage all sample repositories. For example: When spring-boot released a new version, the pipeline will responsible to create new branch for all sample repositories then upgrade to latest spring-boot version. The pipeline can host in `spring-and-azure-product-samples` repository.

  2.4. Multiple similar samples.
    2.4.1. Deprecate duplicated samples.
    2.4.2. Split samples according to Azure product. For example, in `spring-and-azure-cosmos-samples` should only introduce the feature about cosmos. `Use keyvault to manage cosmos secret` should not put in `spring-and-azure-cosmos-samples`. But we can put a link which point to `spring-and-azure-keyvault-samples`, which will introduce how to manage secret by Azure Keyvault.

  2.5. Not provide the best solution. Now samples are all grouped by Azure product. The maintainer of each repository should be the expert of using this Azure product in Spring apps. The maintainers should be responsible to provide the best solution in the samples. 

  2.6. Not using supported version. It can be avoided in `2.3.2. Use pipeline (For example: GitHub actions) to manage all sample repositories`.

  2.7. Not updated for more than one year. It can be avoided in `2.3.2. Use pipeline (For example: GitHub actions) to manage all sample repositories`.
 
 2.8. Lack of synergy between among Azure products. i.e.: samples from Spring Cloud Apps does not use Spring Cloud Azure libraries. This mainly happened in end-to-end samples. End-to-end sample maintainer should refer to other feature-specific sample repo to get the best solution. 

  2.9. Bad repo name. Follow the `spring-and-azure-product-sample-template` will solve this problem. Here is some example repo names:  `spring-and-azure-active-directory-samples`, `spring-and-azure-keyvault-samples`, `spring-and-azure-event-hubs-samples`
 
 2.10. Steep learning curve. Follow the `spring-and-azure-product-sample-template` will solve this problem. Because `spring-and-azure-product-sample-template` requires a learn path of each feature, make sure one sample is easy to learn. For example, here is a folder structure of a sample repository:
  ![image](https://user-images.githubusercontent.com/13167207/171561864-72d2086b-c482-45a8-ad93-e0b05d028cc8.png)
  There should be a learning path like this:
  ![image](https://user-images.githubusercontent.com/13167207/171561209-c8df98f7-914a-42e6-830b-5f4b82e5a5a9.png)
  In the learn-path image, `sample-A -> sample-B` means if customer want to run sample-B, he should run sample-A first. 

### 3. How to handle end-to-end samples

Divide all sample repositories into 2 categories: 
 - `Feature-specific sample`:  only introduce specific feature to customer. This kind of sample should follow the `spring-and-azure-product-sample-template`, and track by `spring-and-azure-product-samples`.
 - `End-to-end sample` will teach customer build a production-ready project step by step. 
    + Not force these sample follow the sample template because these sample may be forked from other repo or has its own design rule. It's not easy to force these samples follow same template.
    +These sample should be tracked by `spring-and-azure-product-samples` to make sure it's tracked and managed in a central place.


## Next step
  - [ ] Create the 2 sample repo in {Azure-Samples](https://github.com/Azure-Samples) :
      - `Azure-Samples/spring-and-azure-product-samples`
      - `Azure-Samples/spring-and-azure-product-samples-template`
  - [ ] Write `spring-and-azure-product-samples-template`, and release 1.0.0 version.
  - [ ] Make current samples follow the template
    - [ ] Make Cosmos DB related samples follow the template
      - [ ] Create repository like `spring-and-azure-cosmos-db-samples` from `spring-and-azure-product-samples-template`, add it to `spring-and-azure-product-samples`,
      - [ ] Move current spring and cosmos-db related sample into the new repo
      - [ ] Deprecate original repo, add link in original repo's readme, link to new repo
      - [ ] Update spring-and-azure-product-samples-template, release a new version if necessary.
    - [ ] Make Azure Active Directory related samples follow the template
    - [ ] Make Azure KeyVault related samples follow the template
    - [ ] etc..
  - [ ] Create job to manage these repositories. For example: 
    - [ ] Create branch `spring-boot_3.0` for all managed repositories by a GitHub Action. Or Use GitAction to create the issue: let the repository maintainer do this task mainally.
    - [ ] When `spring-and-azure-product-samples-template` released a new version, Use GitHub Action to create issues in each repositories: let the repository maintainer update the template version.

**Comment by fangjian0423** [comment]
Updates:

[Azure for Spring developers hub page](https://learn.microsoft.com/en-us/azure/developer/java/spring/) is now live.
