### ISSUE TITLE
[EPIC] Improve MS docs about Spring Cloud Azure

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#28017]
### Context

[MS docs about Spring](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/) has a lot of things need to improve. 

### Problem

TODO: 
1. list all problems
2. Set priority for these problems

Problems:
1. [P0] `Spring Cloud Azure Reference Doc` has a lot of content, which will make it hard to read.
2. [P?] `Azure Active Directory dev guide` because it already exist in `Spring Cloud Azure Reference Doc`.
3. [P?] `Azure Cosmos DB dev guide` because it already exist in `Spring Cloud Azure Reference Doc`.

### Goal 

Fix all existing problems.

#### Proposal

 - [ ] #32147
 - [ ] #30847
 - [ ] Delete `Azure Active Directory dev guide` because it already exist in `Spring Cloud Azure Reference Doc`.
 - [ ] Delete `Azure Cosmos DB dev guide` because it already exist in `Spring Cloud Azure Reference Doc`.
 - [ ] Delete all contents under `Getting Started Guides`, redirect them to samples
 - [ ] Delete contents under `Tutorials`, Use sample in GitHub repo instead.
 - [ ] Delete all contents under https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/ except Spring-Cloud-Azure reference doc. 
  - [x] Delete [To Do List with Cosmos DB](https://github.com/Microsoft/todo-app-java-on-azure/)(not updated since 2019.01) and [To Do List with MySQL](https://github.com/Azure-Samples/mysql-spring-boot-todo)(archived by owner) samples, and add [Spring Cloud Azure Samples](https://github.com/Azure-Samples/azure-spring-boot-samples)

**Comment by fangjian0423** [comment]
Task 8 samples in ms doc has been updated, refer https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3712.

**Comment by chenrujun** [comment]
Closing this issue.
Because we decide to use GitHub issue to track Feature or Bug.
Epic is not necessary anymore.
