### ISSUE TITLE
Write Spike Research for Spring on Azure 

### ISSUE THREAD

**Issue by backwind1233** [Azure/azure-sdk-for-java#28056]
### Context

Please refer to parent issue (#27773) to get more information about the context.

### Goal

Output the problem list and give a plan about how to solve these problems.

### Tasks
 - [x] Collect all samples in scope
 - [x] List all problems about these samples.
 - [x] Output a proposal about how to solve these problems.

**Comment by chenrujun** [comment]
# Problems

## Problems about samples.
Problems about samples already listed in [this excel file](https://microsoftapc.sharepoint.com/:x:/r/teams/Springintegration/_layouts/15/doc2.aspx?sourcedoc=%7B20276df2-2c1f-44b9-9f79-dda67874e8c2%7D&action=edit&activeCell=%27All%20repositories%27!A86&wdinitialsession=4e6a62e5-b276-48fe-bf6b-0a4b64902a6f&wdrldsc=15&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT&cid=7fef911f-0330-4628-b39c-03873c519367).

## Problems about docs
1. Lack a portal for all Spring on Azure docs.
2. Problems about AzureSpringCloud MS page already listed in https://github.com/Azure/azure-sdk-for-java/issues/28017



# Solution Proposal:

## MS docs 

### Pages in scope
 1. Spring on Azure: `https://docs.microsoft.com/en-us/azure/developer/java/spring/`. It's a new page, we need to design TOC of it.
  3. Spring Cloud Azure: `https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/`. This page already exists, we need to update it.

### MS docs: Spring Cloud Azure 
1. Delete all contents except Spring-Cloud-Azure reference doc. 
2. Flatten Spring-Cloud-Azure reference doc.
4. Redirect current link like `Getting Started` / `Turorials` / `Samples` to GitHub repositories. 

### MS docs: Spring on Azure 
Need to design TOC about it.


## Spring Samples
1. Create sample repository template that can solve all problems.
2. Make all Spring-On-Azure sample repositories follow the template.

**Comment by chenrujun** [comment]
Closing this issue.
1. Proposal has already given.
2. The Proposal was not the final version. Still need to discuss with stakeholders. Use https://github.com/Azure/azure-sdk-for-java/issues/27773 to track the process.
