### ISSUE TITLE
Sync reference from MS docs to GitHub pages

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#29161]
## Context

This is next step of #27570.

Now we have 2 places to hold Spring Cloud Azure reference doc:

1. MS docs: 
    1. URL: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/
    2. GiHub Repo: https://github.com/MicrosoftDocs/azure-dev-docs-pr
3. GitHub pages: 
    1. URL https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html
    2. GitHub repo: https://github.com/microsoft/spring-cloud-azure

## Goal

Use this issue to track the reference doc sync task for each release of Spring Cloud Azure.

## Solution

From 4.3.0, follow this workflow to update reference doc:

1. For developers who want to update reference doc:
    1. Create draft PR in MS docs repo ([MicrosoftDocs/azure-dev-docs-pr](https://github.com/MicrosoftDocs/azure-dev-docs-pr/))
    3. Add the PR in to current issue's `Tasks` section. Make sure your PR is tracked and will be synced to GitHub pages repo by scrum master.
    5. Corporate with @KarlErickson about your PR, make the PR approved.

3. For scrum master:
    1. When release finished, make all related PRs merged in MS docs repo.
    2. Sync file changes from MS docs repo ([MicrosoftDocs/azure-dev-docs-pr](https://github.com/MicrosoftDocs/azure-dev-docs-pr/)) to GitHub pages repo ([microsoft/spring-cloud-azure](https://github.com/microsoft/spring-cloud-azure)).

### Tasks

 - [x] Sync reference doc for Spring Cloud Azure 4.1.0 (@hui1110 )
   - [x] Create branch spring-cloud-azure_4.1.0 in [hui1110/azure-dev-docs-pr](https://github.com/hui1110/azure-dev-docs-pr)
   - [x] Merge spring-cloud-azure_4.1.0 to [MicrosoftDocs/azure-dev-docs-pr](https://github.com/MicrosoftDocs/azure-dev-docs-pr)
   - [x] Take file changes from MS docs to GitHub pages
   - [x] Update tag in GitHub pages repo
 - [x] Sync reference doc for Spring Cloud Azure 4.2.0 (@hui1110 )
   - [x] Create branch spring-cloud-azure_4.2.0 in [hui1110/azure-dev-docs-pr](https://github.com/hui1110/azure-dev-docs-pr)
   - [x] Merge spring-cloud-azure_4.2.0 to [MicrosoftDocs/azure-dev-docs-pr](https://github.com/MicrosoftDocs/azure-dev-docs-pr)
   - [x] Take file changes from MS docs to GitHub pages
   - [x] Update tag in GitHub pages repo
 - [x] Sync reference doc for Spring Cloud Azure 4.3.0 (@hui1110 )
   - [x] [PR about Spring Cloud Azure: 4.3.0 update property tables](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3168)
   - [x] [PR about credential-free support: feature support ](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3124)
   - [x] [PR about credential-free support: quick start]( https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3192)
   - [x] [PR about credential-free support: reference doc](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3242)
   - [x] [PR about add Storage and Key Vault starter description to Spring Cloud Azure Reference documentation](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3233)
   - [x] [Add JWT Client Authentication instructions](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3248)
 - [x] Sync reference doc for Spring Cloud Azure 4.4.0 (@hui1110 )
   - [x] [PR about Spring Cloud Azure: 4.4.0 update property tables](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3496)
   - [x]  [remove outdated content for Kafka support on release 4.4.0](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3406)
   - [x] [Fix code error for Service Bus](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3418)
   - [x] [Add contents about connecting to Azure AD via proxy](https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3570)

**Comment by hui1110** [comment]
The reference documentation for 4.4.0 and 4.5.0-beta.1 has been released, this issue is now closed.

**4.4.0**:  https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html

**4.5.0-beta.1**:  https://microsoft.github.io/spring-cloud-azure/4.5.0-beta.1/reference/html/index.html

**Comment by hui1110** [comment]
Need to sync the next version of the document.

**Comment by hui1110** [comment]
Sync reference doc for Spring Cloud Azure 4.5.0

   - [ ]  https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3743

**Comment by hui1110** [comment]
In the current sprint(2022-11), sync the reference doc for Spring Cloud Azure **4.5.0** and **6.0.0-beta.3**.

**Comment by hui1110** [comment]
In the next sprint(2022-12), sync the reference doc for Spring Cloud Azure **4.5.0**

   - [x]  https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3743
   - [ ] https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3668

**Comment by moarychan** [comment]
MS reference doc improvement PR merged:
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3813
- https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3825

Please help sync changes to Github reference doc main branch 4.5.0-beta.1 and [feature/spring-boot-3](https://github.com/microsoft/spring-cloud-azure/tree/feature/spring-boot-3) branch 6.0.0-beta.4.

**Comment by chenrujun** [comment]
Sync changes from [MicrosoftDocs/azure-dev-docs-pr repo](https://github.com/MicrosoftDocs/azure-dev-docs-pr) to [microsoft/spring-cloud-azure repo](https://github.com/microsoft/spring-cloud-azure)

| Source PR | Sync to main branch | Sync to feature/spring-boot-3 branch |
|---|---|---|
| https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3743 | Link to PR: TODO  | Not necessary |
