### ISSUE TITLE
Add Spring Cloud Azure in each Azure product's MS docs page

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#29470]
## Context

Now in each Azure Product's MS docs, there is no entry for `Spring Cloud Azure`. For example: In this page: https://docs.microsoft.com/en-us/azure/event-hubs/, there is no link to Spring Cloud Azure. @seanli1988 already created PR:

 - https://github.com/MicrosoftDocs/azure-docs-pr/pull/199915
 - https://github.com/MicrosoftDocs/azure-docs-pr/pull/199911
 - https://github.com/MicrosoftDocs/azure-docs-pr/pull/199916
 - https://github.com/MicrosoftDocs/azure-docs-pr/pull/199912
 - https://github.com/MicrosoftDocs/azure-docs-pr/pull/199910
 - https://github.com/MicrosoftDocs/azure-docs-pr/pull/199907

But after @KarlErickson's review, we found that it's not that simple. We need more investigation about how to add "Spring Cloud Azure" entry in each Azure product's MS docs.

## Problem

1. These PRs are not merged. And there is `Check error` in these PRs.
2. Some PR didn't give the best solution. We need more consideration about how to add entry for "Spring on Azure" in each services' MS docs.

## Goal

Add Spring Cloud Azure in each Azure product's MS docs page

### Tasks

 - [x] Re-iInvestigate and design how to add "Spring Cloud Azure" in related services' MS docs.

 - [x] Make these PRs merged or closed:
   - [x] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199915
   - [x] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199911
   - [x] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199916
   - [x] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199912
   - [x] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199910
   - [x] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199907

**Comment by chenrujun** [comment]
| Service Name | Link to MS docs | Link to PR |
| ---------------| ------------------| -------------|
| Azure AD | https://docs.microsoft.com/en-us/azure/active-directory/ | <ul><li>- [ ] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199915</li> </ul> |
| Cosmos DB | https://docs.microsoft.com/en-us/azure/cosmos-db/ | <ul><li>- [ ] no PR now</li> </ul> |
| Key Vault | https://docs.microsoft.com/en-us/azure/key-vault/ | <ul><li>- [ ] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199907</li> </ul>|
| Event Hubs | https://docs.microsoft.com/en-us/azure/event-hubs/ | <ul><li>- [ ]  https://github.com/MicrosoftDocs/azure-docs-pr/pull/199915</li> </ul> |
| Service Bus | https://docs.microsoft.com/en-us/azure/event-hubs/ | <ul><li>- [ ]   https://github.com/MicrosoftDocs/azure-docs-pr/pull/199910</li> <li>- [ ] https://github.com/MicrosoftDocs/azure-docs-pr/pull/199911</li> </ul>  |
| Storage | https://docs.microsoft.com/en-us/azure/storage/ |  <ul><li>- [ ]  https://github.com/MicrosoftDocs/azure-docs-pr/pull/199916</li> </ul>  |

**Comment by chenrujun** [comment]
Here is the list that can add **spring-cloud-azure** in each Azure Service's MS docs page

 - [ ] index.yml (The index pages do not have the uniform contents, so there is no sub items)
 - [ ] TOC.yml
   - [ ] Quickstarts
   - [ ] Tutorial
   - [ ] Sample
   - [ ] Reference

**Comment by chenrujun** [comment]
Link to related PRs:

 - [ ] https://github.com/MicrosoftDocs/azure-docs-pr/pull/203989

**Comment by chenrujun** [comment]
Designs:
 - [x] App Configuration. https://github.com/microsoft/spring-cloud-azure/discussions/978
 - [ ] Azure AD
 - [ ] Cosmos DB
 - [ ] Key Vault
 - [ ] Service Bus
 - [ ] Event Hubs
 - [ ] Storage

**Comment by Netyyyy** [comment]
Update Key Vault: https://github.com/MicrosoftDocs/azure-docs-pr/pull/205476

**Comment by chenrujun** [comment]
Update Azure Active Directory: https://github.com/MicrosoftDocs/azure-docs-pr/pull/207687

**Comment by chenrujun** [comment]
Update Service Bus: https://github.com/MicrosoftDocs/azure-docs-pr/pull/207807

**Comment by chenrujun** [comment]
Update Azure Storage: https://github.com/MicrosoftDocs/azure-docs-pr/pull/207815

**Comment by chenrujun** [comment]
All designs are written in [One Note](https://microsoftapc.sharepoint.com/teams/Springintegration/_layouts/15/Doc.aspx?sourcedoc=%7B979d750c-2e38-4f8f-8e78-a17145269e2f%7D&action=edit&wd=target(Design%20doc%20-%20Adding%20Spring%20Cloud%20Azure%20in%20MS%20docs.one%7C84b95d47-570d-41fd-bb15-a07df0473212%2F(Done%5C)%20PR%20descriptions%7Cef6b78d7-1bbd-463d-aca5-02db822ac659%2F)&wdorigin=NavigationUrl&share=IgEMdZ2XOC6PT454oXFFJp4vAXYn3mHbRRgaag_u1f1VaNQ).

**Comment by chenrujun** [comment]
Closing this issue because all related PRs have been merged.
