### ISSUE TITLE
[Epic] Prepare and publish passwordless docs

### ISSUE THREAD

**Issue by saragluna** [Azure/azure-sdk-for-java#30338]
This is an epic to track all the doc related tasks of passwordless connections.

### Context

With all the changes we made to support passwordless connections:
- https://github.com/Azure/azure-sdk-for-java/issues/29218
- https://github.com/Azure/azure-sdk-for-java/issues/29785
- https://github.com/Azure/azure-sdk-for-java/issues/28685

we also need to publish/modify docs to help users work with them. The docs include quickstarts, migration guides, and reference docs. 

There's a template worked out by Alex can be found here:
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1205727432
- https://github.com/MicrosoftDocs/azure-docs-pr/pull/203348#issuecomment-1203381358

| Service           | Java - quickstart                              | Spring - quickstart                                                                                              | Migration guide                                   |
|-------------------|------------------------------------------------|------------------------------------------------------------------------------------------------------------------|---------------------------------------------------|
| MySQL             | Update existing [Java quickstart MySQL]        | Update existing [Spring quickstart MySQL JDBC] <br/> Update existing [Spring quickstart MySQL JPA]               | Add new doc (add contextual tabs for Java/Spring) |
| PostgreSQL        | Update existing [Java quickstart PostgreSQL]   | Update existing [Spring quickstart MySQL JDBC] <br/> Update existing [Spring quickstart MySQL JDBC]              | Add new doc (add contextual tabs for Java/Spring) |
| EventHubs - Kafka | Add new doc                                    | Update existing [Spring quickstart Kafka]                                                                        | Update existing [Spring migration Kafka]   |
| SQL Database      | Update existing [Java quickstart SQL Database] | Update existing [Spring quickstart SQL Database JDBC] <br/> Update existing [Spring quickstart SQL Database JPA] | Add new doc (add contextual tabs for Java/Spring) |

### Goal
Publish migration documentation after the feature is enabled.
#### Migration guides
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29224 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3423
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29782 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3476
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30339 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3483
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30350

#### Quickstarts
**Docs maintained by our team**
- [ ] #30437 - resolves in https://github.com/MicrosoftDocs/azure-docs-pr/pull/208824
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29225 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3419
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30340 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3434
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29783 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3442
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30341 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3442
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30342 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3511
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30343 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3511
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30345 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3406
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/30348

**Docs maintained by partner team**
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30346 - resolves in https://github.com/MicrosoftDocs/azure-docs-pr/pull/208242
- [x] https://github.com/Azure/azure-sdk-for-java/issues/30347 - resolves in https://github.com/MicrosoftDocs/azure-docs-pr/pull/208670

#### Reference docs
- [x] https://github.com/Azure/azure-sdk-for-java/issues/29221 - resolves in https://github.com/MicrosoftDocs/azure-dev-docs-pr/pull/3463

#### Scattered docs using Spring and MySQL
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/30437 - resolves in https://github.com/MicrosoftDocs/azure-docs-pr/pull/208824

[Java quickstart MySQL]: https://docs.microsoft.com/en-us/azure/mysql/single-server/connect-java
[Spring quickstart MySQL JPA]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-mysql
[Spring quickstart MySQL JDBC]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-mysql	
[Java quickstart PostgreSQL]: https://docs.microsoft.com/en-us/azure/postgresql/single-server/connect-java
[Spring quickstart PostgreSQL JPA]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-postgresql
[Spring quickstart PostgreSQL JDBC]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-postgresql
[Java quickstart SQL Database]: https://docs.microsoft.com/en-us/azure/postgresql/single-server/connect-java
[Spring quickstart SQL Database JPA]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-sql-server
[Spring quickstart SQL Database JDBC]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jdbc-with-azure-sql-server
[Spring quickstart Kafka]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub
[Spring migration Kafka]: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure?tabs=maven#remove-credentials-from-spring-kafka-applications

**Comment by saragluna** [comment]
#30347 will be replaced by this tutorial https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-passwordless-spring-database-app?toc=%2Fazure%2Fdeveloper%2Fintro%2Ftoc.json&bc=%2Fazure%2Fdeveloper%2Fintro%2Fbreadcrumb%2Ftoc.json&tabs=mysql.

#30348 will be taken care by the service team. 

Closing the epic now. All passwordless docs can be found on site: https://aka.ms/passwordless-connections.
