### ISSUE TITLE
[EPIC] Project Memphis - Create templates

### ISSUE THREAD

**Issue by seanli1988** [Azure/azure-sdk-for-java#31797]
Create templates that will be consumed by JHipster, AZD and VScode. We will use the AZD template format and create the following templates for
•	Spring security
•	Spring MVC
•	Event-driven apps

story 1: spike research in find out how our template would work end-to-end with JHipser, AZD and VScode

story 2: build POC

story 3: define feature spec for spring mvc template

story 4: publish azd template

### AZD 

- [x] Spike research for AZD: https://github.com/Azure/azure-sdk-for-java/issues/31948
- [x] POC `todo-java-postgresql-passwordless-aca` AZD template: https://github.com/Azure/azure-sdk-for-java/issues/32027
- [x] Define feature spec for AZD: https://github.com/Azure/azure-sdk-for-java/issues/32026

### JHipster

- [x] Spike research for JHipster
- [ ] POC JHipster template
- [ ] Define feature spec for JHipster

### VScode

- [ ] Spike research for VScode
- [ ] POC VScode template
- [ ] Define feature spec for VScode

**Comment by saragluna** [comment]
AZD has been finished, JHipster will also be ready, closing this issue now since VSCode is not in consideration.
