### ISSUE TITLE
[Epic] Spring Cloud Azure 6.0 GA

### ISSUE THREAD

**Issue by moarychan** [Azure/azure-sdk-for-java#31890]
This is the epic issue to track all issues about Spring Cloud Azure 6.0 GA.

### Prerequisites
- [x] https://github.com/Azure/azure-sdk-for-java/issues/31344
- [x] https://github.com/azure/azure-sdk-for-java/issues/31938
- [x] https://github.com/azure/azure-sdk-for-java/issues/31939
- [ ] https://github.com/azure/azure-sdk-for-java/issues/31892
- [ ] ~~https://github.com/azure/azure-sdk-for-java/issues/31891~~
- [ ] ~~https://github.com/azure/azure-sdk-for-java/issues/31893~~
- [ ] https://github.com/azure/azure-sdk-for-java/issues/31017
- [x] https://github.com/azure/azure-sdk-for-java/issues/31937

### Post GA
- [x] https://github.com/azure/azure-sdk-for-java/issues/31894
- [ ] https://github.com/azure/azure-sdk-for-java/issues/31896
- [ ] https://github.com/azure/azure-sdk-for-java/issues/31895

**Comment by stliu** [comment]
I have seen lots of issues about this spring cloud azure 6.0, could you link all of these issues in this epic?

**Comment by moarychan** [comment]
OK， basically it's all there, if I find any new ones, I'll add them in

**Comment by stliu** [comment]
closing this, avoid using epic

**Comment by fangjian0423** [comment]
@stliu @moarychan should we change all the Spring Cloud Azure issues title from 6.0 to 5.0?

**Comment by moarychan** [comment]
Updated to the major version `5`, see more from [Spring Cloud Azure 5.0 Release](https://github.com/Azure/azure-sdk-for-java/issues/31895).
