### ISSUE TITLE
[FEATURE REQ] `StorageSeekableByteChannel`

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-java#32014]
**Is your feature request related to a problem? Please describe.**
`StorageInputStream` currently provides a low-memory-footprint mechanism to provide a seekable view of bytes in a Storage resource via `mark(int)` and `reset()`. Unfortunately, mark() is limited to max int, whereas long values are fully supportable in this situation.

Further, azure-storage-blob-nio must support a `SeekableByteChannel`. It currently depends on `StorageInputStream` as an implementation, and so is subject to those same limits, despite the API of the class suggesting it should not be. To support long-value seeking, blob nio must implement its own `SeekableByteChannel`, but it would be best to have this implementation in the main storage packages.

**Describe the solution you'd like**
azure-storage-common transition its `StorageInputStream` and `StorageOutputStream` implementations to a `StorageSeekableByteChannel` implementation, leaving the old classes as facade over the new channel class. Service packages adopt their implementations appropriately. Channels could only be opened in read mode or write mode (something Java implementations are fine doing).

**Describe alternatives you've considered**
Alternatives aren't viable as the limitation is in the mark/reset API from Java.

**Additional context**
Need prompted by #31924

**Progress**
- [x] Blob read (#33794)
- [x] Block blob write (#33817)
- [ ] Page blob write
- [ ] Append blob write
- [ ] DataLake read
- [ ] DataLake write
- [x] Share file read (#33545)
- [x] Share file write (#33545)

**Comment by sebastianhorn1** [comment]
Dear jaschrep,
thank you for the evaluation you have done. Regarding my problem for me it would be more important that at the end the soulution implements the SeekableByteChannel Interface from java.nio because my solution only relyes on this interface.

Hope that describes it well 
Kind Regards 
Sebastian Horn
