### ISSUE TITLE
POC `todo-java-postgresql-aca` AZD template

### ISSUE THREAD

**Issue by fangjian0423** [Azure/azure-sdk-for-java#32027]
## Context

ADZ have 2 templates about Java language.

- [todo-java-mongo-aca](https://github.com/Azure-Samples/todo-java-mongo-aca) runs on Azure Container Apps
- [todo-java-mongo](https://github.com/Azure-Samples/todo-java-mongo) runs on App Service

All of them store the todo data in mongodb.

## Goal

We want to changed the mongodb to postgresql, and also using [passwordless](https://learn.microsoft.com/en-us/azure/developer/intro/passwordless-overview).

## Solution

 - [x] Create a new AZD template from `todo-java-mongo-aca` template
 - [x] Change mongodb to postgresql on java code
 - [x] Change mongodb to postgresql flexible server on bicep
 - [x] Publish to github repository

**Comment by fangjian0423** [comment]
PostgreSQL Flexible Server Passwordless can't created by terraform and bicep now.

[PostgreSQL Single Server Passwordless support creating by terraform and bicep now](https://learn.microsoft.com/en-us/azure/templates/microsoft.dbforpostgresql/servers/administrators?pivots=deployment-language-bicep).

**Comment by fangjian0423** [comment]
Now the [todo-java-postgresql-aca template](https://github.com/fangjian0423/todo-java-postgresql-aca) can work.

Architecture: 

![image](https://user-images.githubusercontent.com/5254035/204174705-ce5b80a8-2ab1-47ee-8ca3-82ad6a56abd1.png)

Next is make the template production ready and publish to Azure-Samples org.

Here is a step list:

1. Remove Key Vault, and use passwordless, but as the [comment](https://github.com/Azure/azure-sdk-for-java/issues/32027#issuecomment-1327014351) mentioned, only postgresql single server support passwordless now, we should wait postgresql flexible server passwordless feature ga.  I think single server and flexible server are mostly same for bicep, we can have a list to describe the things what we should.
2. Move out where cosmos appears in repository, like readme, architecture diagram, java code
3. Github repository move to Azure-Samples org,  not on personal account
4. Code review
5. Publish to [Awesome AZD Templates](https://azure.github.io/awesome-azd/)

This issue is just a POC, and I will create an issue to track them.

**Comment by fangjian0423** [comment]
We can avoid using deploymentscripts if we could use Service Connector to do the passwordless connection.

Unfortunately, Service Connector didn't support ARM tempalte/bicep now.

**Comment by fangjian0423** [comment]
Notice that [terraform azurerm](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/postgresql_flexible_server_active_directory_administrator) now support PostgreSQL Flexible Server Passwordless.


Maybe terraform is more fit for us to do the infrastructure provisioning 😅

**Comment by fangjian0423** [comment]
Close the issue because [todo-java-postgresql-aca-terraform](https://github.com/fangjian0423/todo-java-postgresql-aca-terraform) and [todo-java-postgresql-terraform](https://github.com/fangjian0423/todo-java-postgresql-terraform) run successfully.
