### ISSUE TITLE
[Epic] Secure Spring Application from zero to hero

### ISSUE THREAD

**Issue by stliu** [Azure/azure-sdk-for-java#32384]
# Problem

Security is one of the most critical areas in application development. Our objective is to help developers to build the most secure application quickly.

In this epic, we're going to : 

1. define the best practices to build a secure Spring Application.
2. see how our product can help to simplify the process.

# Goal

The goal of this epic:

- [ ] Security guideline for spring on azure customers to build the most secure application.
- [ ] Identifies features missing in Spring Cloud Azure to help customers adopt this guideline.
- [ ] Samples and blogs to promote these security practices

# Security Best Practice

By security best practice, I mean something like [this](https://piotrminkowski.com/2021/05/26/spring-microservices-security-best-practices/) for all spring applications on Azure.

Azure already have a [Microsoft Azure Well-Architected Framework - Security](https://learn.microsoft.com/en-us/training/modules/azure-well-architected-security/)

* Always TLS, mTLS if possible
* Minimal privilege with AuthN and AuthZ
* Externalize Secrets
* [Sign In With Microsoft](https://developer.okta.com/docs/guides/add-an-external-idp/microsoft/create-an-app-at-idp/) and enable 2FA
*
