### ISSUE TITLE
[FEATURE REQ] mgmt Network Application Gateway, convenience layer for WAF policy for WAF_V2

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#32566]
Service will announce deprecation of old WafConfiguration for Application Gateway.

https://learn.microsoft.com/en-us/azure/web-application-firewall/ag/policy-overview

features:
1. #35239 
2. #35240 
3. #35241 
4. #35242 
5. #35243 
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/35239
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/35240
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/35241
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/35242
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/35243
```
