### ISSUE TITLE
Azure Cosmos SDK - Simplifying logging and emitting metrics for Application developers

### ISSUE THREAD

**Issue by kushagraThapar** [Azure/azure-sdk-for-java#32759]
Many applications use Cosmos APIs (e.g., readItem(pk).block().toDocument(entityClass)) to read/write documents, while ignoring the accompanying CosmosDiagnostic object in the response (impacting triaging of issues). The CosmosDiagnostic is quite verbose (several KB per response), but proves to be valuable upon issues. Therefore, it is too costly to log the CosmosDiagnostic  for every response, but it is preferable to just log it when the enclosing response meets specific criteria. For example, only log the CosmosDiagnostic if the enclosing response has status code http408 (request timeout). Since logging CosmosDiagnostic is a common functionality for all applications, it is most suitable to implement the logging within the Cosmos SDK. The current CosmosDiagnostic class is also not friendly to extracting only some portions of it that are of interest to the application.

- [x] [Exposing Client Metrics](https://github.com/Azure/azure-sdk-for-java/issues/32760)
- [x] [Default Implementation of Open Telemetry](https://github.com/Azure/azure-sdk-for-java/issues/32761)
- [x] [Cosmos Client logging extension](https://github.com/Azure/azure-sdk-for-java/issues/32762)

**Comment by kushagraThapar** [comment]
This is done.
