### ISSUE TITLE
Proactive connection management enhancements

### ISSUE THREAD

**Issue by jeet1995** [Azure/azure-sdk-for-java#33088]
- [x] [Open connection failure threshold](https://github.com/Azure/azure-sdk-for-java/issues/33080) 
- [x] [Timeout handling for metadata requests](https://github.com/Azure/azure-sdk-for-java/issues/33087) 
- [x] [Concurrent warm up of containers](https://github.com/Azure/azure-sdk-for-java/issues/33082) 
- [x] [Semaphore timeout for concurrently opening connections](https://github.com/Azure/azure-sdk-for-java/issues/33079) 
- [x] [Diagnostics for proactive connection management](https://github.com/Azure/azure-sdk-for-java/issues/33038)

```[tasklist]
### Tasks
- [ ] Add connection warmup tests when metadata requests (collection / partition key range / address resolution) in the warmup flow fail.
```

**Comment by kushagraThapar** [comment]
@jeet1995 if this is done, please close it.
