### ISSUE TITLE
[FEATURE REQ] Make App Config and Spring Data Cosmos have same behavior of other Spring Cloud Azure artifacts

### ISSUE THREAD

**Issue by chenrujun** [Azure/azure-sdk-for-java#33758]
## Context.

Spring Cloud Azure is an open-source project that helps make it easier to use [Azure services](https://azure.microsoft.com/products/) in [Spring](https://spring.io/) applications. Here is official document about it: [Spring Cloud Azure overview](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview).

## Problem
Some artifacts not have same behavior as other Spring Cloud Azure artifacts. Include spring app configuration related artifacts and Spring Data Cosmos.

### Same behavior definition:
 - Source code position: Put in [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring).
 - Group Id: **spring.cloud.azure**.
 - Version: Next GA version: **4.7.0** / **5.1.0**.
 - BOM: Included in [spring-cloud-azure-dependencies](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.6.0/sdk/boms/spring-cloud-azure-dependencies/pom.xml)
 - Document: Put in [Spring Cloud Azure MS learn toc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview).
 - Sample: Put in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples).

## Goal
Make all `Spring Cloud Azure` artifacts have the same behavior.

### App Configuration 
 - Artifact list:
    - azure-spring-cloud-appconfiguration-config
    - azure-spring-cloud-appconfiguration-config-web
    - azure-spring-cloud-feature-management
    - azure-spring-cloud-feature-management-web
    - spring-cloud-azure-starter-appconfiguration
    - azure-spring-cloud-starter-appconfiguration-config
 - Job to be done
   - [x] In main branch. (ETA: 2023-03-31)
      - [x] Move source code to [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring)
      - [x] Change group id to **com.azure.spring**. (The group id is already **com.azure.spring** before change foloer.)
      - [x] Change version to **4.7.x**. (Will do. Refs: https://github.com/Azure/azure-sdk-for-java/issues/33758#issuecomment-1452246369)
      - [x] Included in [spring-cloud-azure-dependencies](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.6.0/sdk/boms/spring-cloud-azure-dependencies/pom.xml)
      - [x] **Architecture Board review**. Work in Progress. Refs: https://github.com/Azure/azure-sdk/issues/5518
      - [x] **API review**. 
      - [x] GA release.
      - [x] Document put in [Spring Cloud Azure MS learn toc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview).
      - [x] Sample put in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples).
   - [ ] In [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3/sdk/spring) branch.  (ETA: 2023-04-30)
      - [x] Move source code to [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring) Link to PR: https://github.com/Azure/azure-sdk-for-java/pull/34254
      - [x] Change group id to **com.azure.spring**.
      - [x] Change version to **5.x**. (Will do. Refs: https://github.com/Azure/azure-sdk-for-java/issues/33758#issuecomment-1452246369)
      - [x] Included in [spring-cloud-azure-dependencies](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.6.0/sdk/boms/spring-cloud-azure-dependencies/pom.xml)
      - [ ] Native support
      - [x] API review. (Not necessary. Refs: https://github.com/Azure/azure-sdk-for-java/issues/33758#issuecomment-1452246775)
      - [x] GA release.
      - [x] Document put in [Spring Cloud Azure MS learn toc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview).
      - [x] Sample put in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples).
      - [ ] Close related issue: https://github.com/Azure/azure-sdk-for-java/issues/20489

### Spring Data Cosmos
 - Artifact list:
    - azure-spring-data-cosmos
    - spring-cloud-azure-starter-data-cosmos
 - Job to be done
   - [ ] In main branch.  (ETA: 2023-04-30. 2 months before [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3/sdk/spring) branch. )
      - [x] Move source code to [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring) Link to PR: https://github.com/Azure/azure-sdk-for-java/pull/33905
      - [x] Change group id to **com.azure.spring**. (❌ Abandoned. Reason: For step 1, we are just moving the packages to a new folder, we don't need to update the group id and versioning, as there are no code changes for the customer.)
      - [x] Change version to 4.7.x. (❌ Abandoned. Reason: For step 1, we are just moving the packages to a new folder, we don't need to update the group id and versioning, as there are no code changes for the customer.)
      - [x] Included in [spring-cloud-azure-dependencies](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.6.0/sdk/boms/spring-cloud-azure-dependencies/pom.xml)
      - [ ] Architecture Board review. 
      - [ ] API review.
      - [ ] GA release.
      - [x] Document put in [Spring Cloud Azure MS learn toc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview).
      - [x] Sample put in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples).
   - [ ] In [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3/sdk/spring) branch.  (ETA: 2023-06-30 . Refs: https://github.com/Azure/azure-sdk-for-java/issues/30458#issuecomment-1420777090)
      - [x] Move source code to [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring)
      - [ ] Change group id to **com.azure.spring**.
      - [x] Change version to 5.x.
      - [x] Included in [spring-cloud-azure-dependencies](https://github.com/Azure/azure-sdk-for-java/blob/spring-cloud-azure-autoconfigure_4.6.0/sdk/boms/spring-cloud-azure-dependencies/pom.xml)
      - [ ] Native support
      - [x] API review. (@TheovanKraay, Is Architecture Board review necessary here?)
      - [x] GA release.
      - [x] Document put in [Spring Cloud Azure MS learn toc](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/spring-cloud-azure-overview).
      - [x] Sample put in [Azure-Samples/azure-spring-boot-samples](https://github.com/Azure-Samples/azure-spring-boot-samples).

**Comment by mrm9084** [comment]
@chenrujun the release of non-beta versions the App Configuration libraries depends on an API review by the SDK team. They are scheduled for the next few days but expect work items to come from it. https://github.com/Azure/azure-sdk/issues/5518#issuecomment-1445532432

**Comment by chenrujun** [comment]
@mrm9084 
Thanks for the information. Here is my understanding of current status: Correct me if I have any misunderstanding:

1. There are 5 App Configuration related artifacts:
   - azure-spring-cloud-appconfiguration-config
   - azure-spring-cloud-appconfiguration-config-web
   - azure-spring-cloud-feature-management
   - azure-spring-cloud-feature-management-web
   - azure-spring-cloud-starter-appconfiguration-config

2. Progress of these artifacts:
   - [x] Put in [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring)
   - [x] Change group id to **com.azure.spring**.
   - [x] ❌ Version change to **4.7.x**. (Abandoned because of ... @mrm9084, could you please give reason here?)
   - [ ] **Architecture Board review**. Work in Progress. Refs: https://github.com/Azure/azure-sdk/issues/5518
   - [ ] **API review**. 
   - [ ] GA release on **March Release Train**.
   - [ ] Sync to [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3/sdk/spring) branch. (@mrm9084 What's the version here? 5.0 or 5.1?)
   - [ ] API review. (@mrm9084, Is **Architecture Board review** necessary here?)
   - [ ] GA release on **April Release Train**.

**Comment by chenrujun** [comment]
@TheovanKraay 
Here is my current understanding. Correct me if I have any misunderstanding.

1. There are 1 Spring Data Cosmos related artifacts:
    - azure-spring-data-cosmos

2. Progress of these artifacts:
    - [ ] Move source code to [sdk/spring folder](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/spring)
    - [ ] Change group id to **com.azure.spring**.
    - [ ] Change version to 4.7.x. (❌ Abandoned because of ... @TheovanKraay, could you please give reason here?)
    - [ ] Architecture Board review. 
    - [ ] API review.
    - [ ] GA release on **March Release Train**.
    - [ ] Sync to [feature/spring-boot-3](https://github.com/Azure/azure-sdk-for-java/tree/feature/spring-boot-3/sdk/spring) branch. (TheovanKraay What's the version here? 5.0 or 5.1?)
    - [ ] API review.
    - [ ] GA release on **April Release Train**.

**Comment by mrm9084** [comment]
Also, no API changes should happen for the 5.x release.

**Comment by chenrujun** [comment]
Hi, @mrm9084 
Thank you very much for you information. 

1. 

> Also, no API changes should happen for the 5.x release.

Does it mean there is no need for **Architecture Board review** and **API review** when GA 5.x?

2. I updated the issue description. Especially this part: **Solution Proposal -> App Configuration -> Job to be done** . Please take a look. Correct me if I have any misunderstandng.
3. Could you please give the ETA of 4.x and 5.x GA?

**Comment by cyrmans** [comment]
Do you hava any idea when the feature about native support for app configuration will be planned ?
