### ISSUE TITLE
Release Storage Track 2 Library Preview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#3496]
Goal:

Release a preview of the Storage client libraries

- [ ] Common
  - [ ] Credentials
  - [ ] Common classes (exceptions, error codes, HttpRange, etc)
- [ ] Blobs
    - [x] Move from Gauri's fork to upstream's storage-proto branch
    - [ ] Smart download to file (parallel, large file, create directories as needed)
    - [ ] Smart upload from file (parallel, large file)
    - [ ] `exists()` method on container and blob clients (previously written using `getProperties()`)
    - [x] method to get parent client on blobs and containers
    - [ ] `listBlobsHierachy()`
    - [ ] Blob InputStream or OutputStream
    - [ ] Finish migrating tests and enable all of them
    - [x] Convert all manually paginated methods to auto-continued
    - [x] Convert all methods that return AutoRest generated headers to return manually crafted types
    - [x] Add `URL getURL()` method on clients
    - [ ] Implement lease, access conditions
    - [ ] AAD support
    - [ ] Help and Samples
- [ ] Files
    - [ ] Track 2 Guidelines and Requirements
    - [ ] Repo guidelines
    - [ ] Tests and Recordings
    - [ ] Help and Samples
- [ ] Queues
    - [ ] Track 2 Guidelines and Requirements
    - [ ] Repo guidelines
    - [ ] Tests and Recordings
    - [ ] Help and Samples
    - [ ] client side encryption
- [ ] SAS
  - [ ] Track 2 Guidelines and Requirements
  - [ ] Repo guidelines
  - [ ] Tests and Recordings
  - [ ] Help and Samples
