### ISSUE TITLE
[Java] Release Event Hubs Track 2 Library Preview 1

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#3498]
## Goal

Release Preview for Track 2 of Event Hub.

See if we can re-use underlying components of the existing Event Hubs library with modifications to the public surface 
area to align with our current design docs.

### Track 2 Guideline Requirements

- [x] #3582: Solidify API surface area and scenarios that are covered
- [x] #3535: Update APIs to support pagination if possible.
- [x] #3579: Use new Authentication model
- [x] #3532: Map thrown exceptions to ones used in exception hierarchy
- [x] #3533: Add support for retry policy
- [x] #3530: Verify telemetry information meets guidelines
- [x] #3534: Update Cancellation Token or Timeout
- [x] #3581: Update namespace
- [ ] #3531: Update logging to match design spec.
- [ ] #3536: Explore support for tracing

### Features

- [x] #3598: Create EventSender
- [x] #3599: Create underlying proton-j layer with Reactor
- [x] #3600: Create Link, Session, and Connection with Reactor
- [x] #3601: Create EventReceiver
- [x] #3714: Create Unit tests for exception classes
- [x] #3715: Create Unit tests for EventReceiver
- [x] #3716: Create Unit tests for EventSender
- [x] #3717: Create Unit tests for EventHubClient
- [ ] #3580: Ensure Proxy support aligns with Track 2 guidelines

### Documentation and Samples Readiness

- [x] #3578: Update javadoc
- [x] #3538: Adapt existing or write new README
- [x] #3537: Add samples
