### ISSUE TITLE
Release Azure.Identity Library Preview

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#3505]
Goal:

Release the Azure.Identity library
Integrate this library in the other client libraries.

- [ ] Gap Analysis of MSAL 
- [ ] Provide Feedback to MSAL Team and schedule updates
- [ ] Finalize Azure.Identity footprint for SDK Preview
- [x] Azure.Core Updates
  - [x] Credential (base for Token, SAS, etc)
  - [x] TokenCredential 
  - [x] CredentialPolicy
- [ ] Azure.Identity
  - [ ] Classes
    - [ ] AzureCredential
    - [ ] ClientSecretCredential
    - [ ] ClientCertificateCredential
    - [ ] MSICredential
    - [ ] TokenCredentialProvider
    - [ ] EnvironmentCredentialProvider
    - [ ] MSICredentialProvider
  - [ ] Implementations
    - [ ] ClientSecretCredential
    - [ ] ClientCertificateCredential
    - [ ] ManagedIdentityCredential
- [ ] Investigate other authentication schemes we need to support (user auth, auth from shared token cache)

**Comment by joshfree** [comment]
Closing Preview 1 (July Preview) Epic
