### ISSUE TITLE
[BUG] mgmt, investigate on occasional thread stuck

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#35244]
We've had several customer reports of occasional thread stuck when using mgmt SDK. 
Need to investigate on each one and maybe there's a shared root cause. 
* #33056
* #33829
* https://github.com/Azure/azure-sdk-for-java/issues/36808
* ~~IcM, timeout exception: https://portal.microsofticm.com/imp/v3/incidents/details/391847100/home (turned out to be an external timeout)~~
* ~~Tooling team reported thread stuck when calling convenience method, resolved by calling serviceClient method~~(spring app backend creating managedcontainer for quite some time and looks like stuck)
```[tasklist]
### Tasks
- [ ] Investigate `Schedulers.io()` on the behavior of thread shortage
- [ ] Test Completeable.complete() as return value for Completeable
- [x] Netty configuration
- [ ] Investigate on delete code where the polling stuck occurs
```
