### ISSUE TITLE
[FEATURE REQ]: `CosmosDiagnostics` improvements.

### ISSUE THREAD

**Issue by jeet1995** [Azure/azure-sdk-for-java#36647]
Include the following information in the `CosmosDiagnostics` string.

```[tasklist]
### Tasks
- [ ] Add `SessionRetryOptions` to the diagnostics.
- [ ] Add client-level `excludeRegions` to the diagnostics.
- [ ] Rename `proactiveInit` to `proactiveInitCfg`.
```
