### ISSUE TITLE
[FEATURE REQ] mgmt function app, convenience API for creating function app with `managedEnvironmentId`

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#37156]
docs: https://learn.microsoft.com/en-us/azure/azure-functions/functions-container-apps-hosting

It's a new hosting plan compared to previous App Service Plans: [All hosting plans](https://learn.microsoft.com/en-us/azure/azure-functions/functions-scale#operating-systemruntime)

Some major implementation differences(found in [azure-cli](https://github.com/Azure/azure-cli/blob/d8c3a443cf2e3b82ebb816152974ab5db8237b6d/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L3955), may not be exhaustive):
For managed container app environment based(Centauri) Function Apps
1. SiteConfig needs to be set to SiteInner.siteConfig when **creating** FunctionApp, instead of updating SiteConfig after Function App is created. Though future update on site configs will be using **update** method.
2. Some property values are different, e.g. kind in SiteInner need to be "functionapp,linux,container,azurecontainerapps"
3. Some update methods(updateSiteConfig, updateAppSettings) are LRO for Centauri Function Apps, but not defined as such in swagger. Need to manual poll. 

```[tasklist]
### Tasks
- [x] Test cases for function app on ACA
- [x] Interface design
- [x] [Implementation investigation] SiteConfig behavior change
- [x] [Implementation investigation] SiteInner property modifications
- [x] [Implementation investigation] manual LRO for updating SiteConfig and AppSettings
- [x] Interface Implementation
- [x] Alpha release for tooling team
- [ ] Stable release
```

**Comment by weidongxu-microsoft** [comment]
For (3), should we ask service to fix?

LRO not marked as LRO means every SDK fails.

**Comment by XiaofeiCao** [comment]
> For (3), should we ask service to fix?
> 
> LRO not marked as LRO means every SDK fails.

Yeah, I'll ask them for confirmation. CLI team seems to be aware of this issue too: https://github.com/Azure/azure-cli/blob/dev/src/azure-cli/azure/cli/command_modules/appservice/custom.py#L459

**Comment by XiaofeiCao** [comment]
## Use cases for function app on Azure Container Apps 

### Create function app with managed environment
```java
FunctionApp functionApp = appServiceManager.functionApps().define(webappName)
    .withRegion(Region.US_EAST)
    .withNewResourceGroup(rgName1)
    .withManagedEnvironmentId(managedEnvironmentId) // create with managedEnvironmentId
    //.withManagedEnvironmentName(managedEnvironmentName) // create with managedEnvironmentName
    .withMaxReplicas(10) // with scale setting
    .withMinReplicas(3) // with scale setting
    .withBuiltInImage(FunctionRuntimeStack.JAVA_17)
    .withAppSetting("WEBSITE_RUN_FROM_PACKAGE", FUNCTION_APP_PACKAGE_URL)
    .create();
```

### Update scale settings
```java
functionApp.update()
    .withMaxReplicas(15) // with scale setting
    .withMinReplicas(5) // with scale setting
    .apply();
```

**Comment by XiaofeiCao** [comment]
2.34.0 released.
