### ISSUE TITLE
Investigate if we can use `HttpUrlConnection` for our default HTTP client in generic-core

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#37514]
Currently with `azure-core`, every HTTP-based SDK by default includes `azure-core-http-netty` as a dependency otherwise all applications using HTTP-based SDKs would need to include an HttpClient implementing library as a dependency. 

```[tasklist]
### Tasks
- [x] Provide a default HttpUrlConnection client implementation for customers wanting to use this library directly.
- [x] https://github.com/Azure/azure-sdk-for-java/issues/38278
- [ ] Provide a multi jar release support/guideline document to have multiple release jars for different environments.
- [ ] Implement a feature to support SSL and TLS protocols.
- [ ] Investigate which HTTP clients should be supported – HUC, JDK HttpClient or a different client (shaded Apache? AWS uses it). This also depends on the need for async stack.
```
