### ISSUE TITLE
Investigate compile time annotation processing

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#37563]
- Eliminate the need for using reflective utils in Rest Proxy. | Eliminate the need for using reflective utils in Rest Proxy.  
- Reducing the amount of runtime reflection required for an HTTP call – can build-time annotation processing give us better performance?
Ref - https://apiview.dev/Assemblies/Review/ad330c0d401e45adb0fde58ac674c3cb#aa3c4e9d37c543c1bd3e1f187b9aaa72

```[tasklist]
### Tasks
- [x] Remove un-required annotations from core
- [x] Add the tooling to repo
```

### Follow up
- [ ] Support for FormParam

**Comment by samvaity** [comment]
https://github.com/Azure/azure-sdk-for-java/pull/43457
