### ISSUE TITLE
Simplify exception hierarchy to `HttpRequestException`  & `HttpResponseException`

### ISSUE THREAD

**Issue by samvaity** [Azure/azure-sdk-for-java#37567]
[Reference](https://apiview.dev/Assemblies/Review/ad330c0d401e45adb0fde58ac674c3cb#87dd7dc103c04648924c64c16f3ced37):
"Introduce an `HttpExceptionType` `ExpandableStringEnum` with values for `RESOURCE_EXISTS`, etc. I would then move these two exception types and the enum into the appropriate `*.http.*` package."

Read [this](https://apiview.dev/Assemblies/Review/ad330c0d401e45adb0fde58ac674c3cb#2b535ae1450a4c29be2ef72aed874721) as well.

Would this work?

```java
class SomeException extend HttpResponseException<Foo> {
    Foo getValue();
}
```

@vcolin7: I took the approach of specifying the response exception body type in `UnexpectedResponseExceptionInformation` for the time being.

```[tasklist]
### Tasks
- [x] Remove all subtypes of `HttpResponseException` and use an `ExpandableStringEnum` instead
- [x] ~~Consider adding T to getValue from exception~~ Use the `UnexpectedResponseExceptionInformation` annotation to infer the type of the body to get from `HttpResponseException`
- [ ] Rethink for UnexpectedLengthException -> Can we have a better ClientSideException story here instead?
- [ ] Consider moving on from using `UnexpectedResponseExceptionType` in favor of the new `HttpResponseInformation` annotation
```
