### ISSUE TITLE
Refactor the `Response` classes and how users can get default implementations

### ISSUE THREAD

**Issue by vcolin7** [Azure/azure-sdk-for-java#37786]
```[tasklist]
### Tasks
- [x] Make `StreamResponse` an interface that extends from `Response`
- [x] Add a factory method to `Response` and `StreamResponse` to get a default implementation of each
- [x] Make `SimpleResponse` package-private and write a default implementation for `StreamResponse` (e.g. `SimpleStreamResponse`)
- [x] Make `SimpleStreamResponse.getValue()` return an `InputStream` instead of `ByteBuffer`
- [ ] Add support for checking if the value of a `StreamResponse` is replayable, has been consumed, needs caching, chunking and other related tasks
```
