### ISSUE TITLE
[FEATURE REQ] investigate enable stream serialization for mgmt

### ISSUE THREAD

**Issue by weidongxu-microsoft** [Azure/azure-sdk-for-java#38333]
**Is your feature request related to a problem? Please describe.**
Relate to https://github.com/Azure/azure-sdk-for-java/issues/38569

Pending investigate whether mgmt can have `stream-style-serialization` turned on.

Potential issue:
- Some class in azure-core-management needs update to impl the interface.
  - Alan's PR https://github.com/Azure/azure-sdk-for-java/pull/38322
- There could be bug involved with weird mgmt SDK.
- The flatten solution in mgmt may affect.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [ ] Expected solution specified

```[tasklist]
### Tasks
- [ ] https://github.com/Azure/autorest.java/issues/2740
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40047
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40409
- [ ] https://github.com/Azure/autorest.java/issues/2741
```

**Comment by alzimmermsft** [comment]
I believe #38322 is related to this as well
