### ISSUE TITLE
Migrate v2 AMQP stack to Event Hubs

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#38476]
Dependent on #33708 

1. Define the opt-in flag for each Event Hub client types.
2. Update the client builder to have utility type for this opt-in/opt-out (we can copy it from the SB Client builder).
3. Wire the ReactorConnectionCache for Event Hubs.
4. Write the MessageFlux based receiver for the v2 low-level async-receiver.
5. Write the WindowedSubscriber based receiver for the v2 low-level sync-receiver.
6. When doing #_4, #_5 make sure the buffering of the events are predictable (can be computed from prefetch and backpressure const).
7. Reevaluate the operators in the Processor path, remove the duplicate / unnecessary that creates unexpected backpressure to the v2 low level async-receiver.
8. Re-Write the processor pump implementation to make it like the MessagePump we developed in SB.
9. Wire the RequestResponseChannelCache and new ReactorSessionCache.
10. Come up with stress test scenarios – so we can watch for memory, throughput, recoveries.
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40484
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40499
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40500
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40501
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40502
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/40503
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/41806
```

**Comment by anuchandy** [comment]
Implemented and shipped (5.19.0 with feature-flag, 5.20.0 as default), closing.
