### ISSUE TITLE
Migrate JSON serialization to azure-json

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#38569]
# Steps to onboard azure-json into SDK's

See this guide: https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Json-Migration

# Libraries to migrate

```[tasklist]
### Tasks
- [x] com.azure.resourcemanager:azure-resourcemanager
- [x] com.azure.resourcemanager:azure-resourcemanager-advisor
- [x] com.azure.resourcemanager:azure-resourcemanager-agrifood
- [x] com.azure.resourcemanager:azure-resourcemanager-alertsmanagement
- [x] com.azure.resourcemanager:azure-resourcemanager-apicenter
- [x] com.azure.resourcemanager:azure-resourcemanager-apimanagement
- [x] com.azure.resourcemanager:azure-resourcemanager-appcomplianceautomation
- [x] com.azure.resourcemanager:azure-resourcemanager-appconfiguration
- [x] com.azure.resourcemanager:azure-resourcemanager-appcontainers
- [x] com.azure.resourcemanager:azure-resourcemanager-applicationinsights
- [x] com.azure.resourcemanager:azure-resourcemanager-appplatform
- [x] com.azure.resourcemanager:azure-resourcemanager-appservice
- [x] com.azure.resourcemanager:azure-resourcemanager-attestation
- [x] com.azure.resourcemanager:azure-resourcemanager-authorization
- [x] com.azure.resourcemanager:azure-resourcemanager-automanage
- [x] com.azure.resourcemanager:azure-resourcemanager-automation
- [x] com.azure.resourcemanager:azure-resourcemanager-avs
- [ ] com.azure.resourcemanager:azure-resourcemanager-azureadexternalidentities
- [x] com.azure.resourcemanager:azure-resourcemanager-azurearcdata
- [x] com.azure.resourcemanager:azure-resourcemanager-azurestack
- [x] com.azure.resourcemanager:azure-resourcemanager-azurestackhci
- [x] com.azure.resourcemanager:azure-resourcemanager-baremetalinfrastructure
- [x] com.azure.resourcemanager:azure-resourcemanager-batch
- [ ] com.azure.resourcemanager:azure-resourcemanager-batchai
- [x] com.azure.resourcemanager:azure-resourcemanager-billing
- [x] com.azure.resourcemanager:azure-resourcemanager-billingbenefits
- [x] com.azure.resourcemanager:azure-resourcemanager-botservice
- [x] com.azure.resourcemanager:azure-resourcemanager-cdn
- [x] com.azure.resourcemanager:azure-resourcemanager-changeanalysis
- [x] com.azure.resourcemanager:azure-resourcemanager-chaos
- [x] com.azure.resourcemanager:azure-resourcemanager-cognitiveservices
- [ ] com.azure.resourcemanager:azure-resourcemanager-commerce
- [x] com.azure.resourcemanager:azure-resourcemanager-communication
- [x] com.azure.resourcemanager:azure-resourcemanager-compute
- [x] com.azure.resourcemanager:azure-resourcemanager-confidentialledger
- [x] com.azure.resourcemanager:azure-resourcemanager-confluent
- [x] com.azure.resourcemanager:azure-resourcemanager-connectedvmware
- [x] com.azure.resourcemanager:azure-resourcemanager-consumption
- [x] com.azure.resourcemanager:azure-resourcemanager-containerinstance
- [x] com.azure.resourcemanager:azure-resourcemanager-containerregistry
- [x] com.azure.resourcemanager:azure-resourcemanager-containerservice
- [x] com.azure.resourcemanager:azure-resourcemanager-containerservicefleet
- [x] com.azure.resourcemanager:azure-resourcemanager-cosmos
- [x] com.azure.resourcemanager:azure-resourcemanager-cosmosdbforpostgresql
- [x] com.azure.resourcemanager:azure-resourcemanager-costmanagement
- [x] com.azure.resourcemanager:azure-resourcemanager-customerinsights
- [x] com.azure.resourcemanager:azure-resourcemanager-dashboard
- [x] com.azure.resourcemanager:azure-resourcemanager-databox
- [x] com.azure.resourcemanager:azure-resourcemanager-databoxedge
- [x] com.azure.resourcemanager:azure-resourcemanager-databricks
- [x] com.azure.resourcemanager:azure-resourcemanager-datadog
- [x] com.azure.resourcemanager:azure-resourcemanager-datafactory
- [x] com.azure.resourcemanager:azure-resourcemanager-datalakeanalytics
- [x] com.azure.resourcemanager:azure-resourcemanager-datalakestore
- [x] com.azure.resourcemanager:azure-resourcemanager-datamigration
- [x] com.azure.resourcemanager:azure-resourcemanager-dataprotection
- [x] com.azure.resourcemanager:azure-resourcemanager-defendereasm
- [x] com.azure.resourcemanager:azure-resourcemanager-delegatednetwork
- [ ] com.azure.resourcemanager:azure-resourcemanager-deploymentmanager
- [x] com.azure.resourcemanager:azure-resourcemanager-desktopvirtualization
- [x] com.azure.resourcemanager:azure-resourcemanager-devcenter
- [x] com.azure.resourcemanager:azure-resourcemanager-devhub
- [x] com.azure.resourcemanager:azure-resourcemanager-deviceprovisioningservices
- [x] com.azure.resourcemanager:azure-resourcemanager-deviceupdate
- [x] com.azure.resourcemanager:azure-resourcemanager-devspaces
- [x] com.azure.resourcemanager:azure-resourcemanager-devtestlabs
- [x] com.azure.resourcemanager:azure-resourcemanager-digitaltwins
- [x] com.azure.resourcemanager:azure-resourcemanager-dns
- [x] com.azure.resourcemanager:azure-resourcemanager-dnsresolver
- [x] com.azure.resourcemanager:azure-resourcemanager-dynatrace
- [x] com.azure.resourcemanager:azure-resourcemanager-edgeorder
- [x] com.azure.resourcemanager:azure-resourcemanager-education
- [x] com.azure.resourcemanager:azure-resourcemanager-elastic
- [x] com.azure.resourcemanager:azure-resourcemanager-elasticsan
- [x] com.azure.resourcemanager:azure-resourcemanager-eventgrid
- [x] com.azure.resourcemanager:azure-resourcemanager-eventhubs
- [x] com.azure.resourcemanager:azure-resourcemanager-extendedlocation
- [x] com.azure.resourcemanager:azure-resourcemanager-fluidrelay
- [x] com.azure.resourcemanager:azure-resourcemanager-frontdoor
- [x] com.azure.resourcemanager:azure-resourcemanager-graphservices
- [x] com.azure.resourcemanager:azure-resourcemanager-hanaonazure
- [x] com.azure.resourcemanager:azure-resourcemanager-hardwaresecuritymodules
- [x] com.azure.resourcemanager:azure-resourcemanager-hdinsight
- [x] com.azure.resourcemanager:azure-resourcemanager-hdinsight-containers
- [x] com.azure.resourcemanager:azure-resourcemanager-healthbot
- [x] com.azure.resourcemanager:azure-resourcemanager-healthcareapis
- [ ] com.azure.resourcemanager:azure-resourcemanager-hybridcompute
- [ ] com.azure.resourcemanager:azure-resourcemanager-hybridconnectivity
- [ ] com.azure.resourcemanager:azure-resourcemanager-hybridcontainerservice
- [ ] com.azure.resourcemanager:azure-resourcemanager-hybridkubernetes
- [ ] com.azure.resourcemanager:azure-resourcemanager-hybridnetwork
- [x] com.azure.resourcemanager:azure-resourcemanager-imagebuilder
- [x] com.azure.resourcemanager:azure-resourcemanager-iotcentral
- [x] com.azure.resourcemanager:azure-resourcemanager-iotfirmwaredefense
- [x] com.azure.resourcemanager:azure-resourcemanager-iothub
- [x] com.azure.resourcemanager:azure-resourcemanager-keyvault
- [x] com.azure.resourcemanager:azure-resourcemanager-kubernetesconfiguration
- [x] com.azure.resourcemanager:azure-resourcemanager-kusto
- [x] com.azure.resourcemanager:azure-resourcemanager-labservices
- [x] com.azure.resourcemanager:azure-resourcemanager-loadtesting
- [x] com.azure.resourcemanager:azure-resourcemanager-loganalytics
- [x] com.azure.resourcemanager:azure-resourcemanager-logic
- [x] com.azure.resourcemanager:azure-resourcemanager-logz
- [x] com.azure.resourcemanager:azure-resourcemanager-machinelearning
- [ ] com.azure.resourcemanager:azure-resourcemanager-machinelearningservices
- [x] com.azure.resourcemanager:azure-resourcemanager-maintenance
- [x] com.azure.resourcemanager:azure-resourcemanager-managedapplications
- [x] com.azure.resourcemanager:azure-resourcemanager-managednetworkfabric
- [x] com.azure.resourcemanager:azure-resourcemanager-managementgroups
- [x] com.azure.resourcemanager:azure-resourcemanager-maps
- [x] com.azure.resourcemanager:azure-resourcemanager-mariadb
- [x] com.azure.resourcemanager:azure-resourcemanager-marketplaceordering
- [x] com.azure.resourcemanager:azure-resourcemanager-mediaservices
- [x] com.azure.resourcemanager:azure-resourcemanager-mixedreality
- [x] com.azure.resourcemanager:azure-resourcemanager-mobilenetwork
- [x] com.azure.resourcemanager:azure-resourcemanager-monitor
- [x] com.azure.resourcemanager:azure-resourcemanager-msi
- [ ] com.azure.resourcemanager:azure-resourcemanager-mysql
- [x] com.azure.resourcemanager:azure-resourcemanager-mysqlflexibleserver
- [x] com.azure.resourcemanager:azure-resourcemanager-netapp
- [x] com.azure.resourcemanager:azure-resourcemanager-network
- [ ] com.azure.resourcemanager:azure-resourcemanager-networkanalytics
- [x] com.azure.resourcemanager:azure-resourcemanager-networkcloud
- [x] com.azure.resourcemanager:azure-resourcemanager-networkfunction
- [x] com.azure.resourcemanager:azure-resourcemanager-newrelicobservability
- [x] com.azure.resourcemanager:azure-resourcemanager-nginx
- [x] com.azure.resourcemanager:azure-resourcemanager-notificationhubs
- [x] com.azure.resourcemanager:azure-resourcemanager-oep
- [x] com.azure.resourcemanager:azure-resourcemanager-operationsmanagement
- [x] com.azure.resourcemanager:azure-resourcemanager-orbital
- [x] com.azure.resourcemanager:azure-resourcemanager-paloaltonetworks-ngfw
- [x] com.azure.resourcemanager:azure-resourcemanager-peering
- [x] com.azure.resourcemanager:azure-resourcemanager-playwrighttesting
- [x] com.azure.resourcemanager:azure-resourcemanager-policyinsights
- [x] com.azure.resourcemanager:azure-resourcemanager-postgresql
- [x] com.azure.resourcemanager:azure-resourcemanager-postgresqlflexibleserver
- [x] com.azure.resourcemanager:azure-resourcemanager-powerbidedicated
- [x] com.azure.resourcemanager:azure-resourcemanager-privatedns
- [x] com.azure.resourcemanager:azure-resourcemanager-providerhub
- [x] com.azure.resourcemanager:azure-resourcemanager-purview
- [x] com.azure.resourcemanager:azure-resourcemanager-quantum
- [x] com.azure.resourcemanager:azure-resourcemanager-qumulo
- [x] com.azure.resourcemanager:azure-resourcemanager-quota
- [x] com.azure.resourcemanager:azure-resourcemanager-recoveryservices
- [x] com.azure.resourcemanager:azure-resourcemanager-recoveryservicesbackup
- [x] com.azure.resourcemanager:azure-resourcemanager-recoveryservicesdatareplication
- [x] com.azure.resourcemanager:azure-resourcemanager-recoveryservicessiterecovery
- [x] com.azure.resourcemanager:azure-resourcemanager-redis
- [x] com.azure.resourcemanager:azure-resourcemanager-redisenterprise
- [x] com.azure.resourcemanager:azure-resourcemanager-relay
- [x] com.azure.resourcemanager:azure-resourcemanager-reservations
- [x] com.azure.resourcemanager:azure-resourcemanager-resourceconnector
- [x] com.azure.resourcemanager:azure-resourcemanager-resourcegraph
- [x] com.azure.resourcemanager:azure-resourcemanager-resourcehealth
- [x] com.azure.resourcemanager:azure-resourcemanager-resourcemover
- [x] com.azure.resourcemanager:azure-resourcemanager-resources
- [ ] com.azure.resourcemanager:azure-resourcemanager-samples
- [x] com.azure.resourcemanager:azure-resourcemanager-scvmm
- [x] com.azure.resourcemanager:azure-resourcemanager-search
- [x] com.azure.resourcemanager:azure-resourcemanager-security
- [ ] com.azure.resourcemanager:azure-resourcemanager-securitydevops
- [x] com.azure.resourcemanager:azure-resourcemanager-securityinsights
- [x] com.azure.resourcemanager:azure-resourcemanager-selfhelp
- [x] com.azure.resourcemanager:azure-resourcemanager-servicebus
- [x] com.azure.resourcemanager:azure-resourcemanager-servicefabric
- [x] com.azure.resourcemanager:azure-resourcemanager-servicelinker
- [x] com.azure.resourcemanager:azure-resourcemanager-servicenetworking
- [x] com.azure.resourcemanager:azure-resourcemanager-signalr
- [x] com.azure.resourcemanager:azure-resourcemanager-sphere
- [x] com.azure.resourcemanager:azure-resourcemanager-springappdiscovery
- [x] com.azure.resourcemanager:azure-resourcemanager-sql
- [x] com.azure.resourcemanager:azure-resourcemanager-sqlvirtualmachine
- [x] com.azure.resourcemanager:azure-resourcemanager-storage
- [x] com.azure.resourcemanager:azure-resourcemanager-storagecache
- [x] com.azure.resourcemanager:azure-resourcemanager-storageimportexport
- [x] com.azure.resourcemanager:azure-resourcemanager-storagemover
- [x] com.azure.resourcemanager:azure-resourcemanager-storagepool
- [x] com.azure.resourcemanager:azure-resourcemanager-streamanalytics
- [x] com.azure.resourcemanager:azure-resourcemanager-subscription
- [x] com.azure.resourcemanager:azure-resourcemanager-support
- [x] com.azure.resourcemanager:azure-resourcemanager-synapse
- [ ] com.azure.resourcemanager:azure-resourcemanager-test
- [x] com.azure.resourcemanager:azure-resourcemanager-timeseriesinsights
- [x] com.azure.resourcemanager:azure-resourcemanager-trafficmanager
- [ ] com.azure.resourcemanager:azure-resourcemanager-videoanalyzer
- [x] com.azure.resourcemanager:azure-resourcemanager-vmwarecloudsimple
- [x] com.azure.resourcemanager:azure-resourcemanager-voiceservices
- [x] com.azure.resourcemanager:azure-resourcemanager-webpubsub
- [x] com.azure.resourcemanager:azure-resourcemanager-workloads
- [ ] com.azure.spring:spring-cloud-azure-appconfiguration-config
- [ ] com.azure.spring:spring-cloud-azure-appconfiguration-config-web
- [ ] com.azure.spring:spring-cloud-azure-autoconfigure
- [ ] com.azure.spring:spring-cloud-azure-feature-management
- [ ] com.azure.spring:spring-messaging-azure
- [ ] com.azure.spring:spring-messaging-azure-eventhubs
- [ ] com.azure.spring:spring-messaging-azure-servicebus
- [ ] com.azure.spring:spring-messaging-azure-storage-queue
- [ ] com.azure:azure-ai-anomalydetector
- [x] com.azure:azure-ai-contentsafety
- [x] com.azure:azure-ai-documentintelligence
- [ ] com.azure:azure-ai-formrecognizer
- [x] com.azure:azure-ai-openai
- [ ] com.azure:azure-ai-personalizer
- [ ] com.azure:azure-ai-textanalytics
- [ ] com.azure:azure-ai-translation-text
- [ ] com.azure:azure-ai-vision-imageanalysis
- [ ] com.azure:azure-analytics-defender-easm
- [ ] com.azure:azure-analytics-purview-sharing
- [x] com.azure:azure-analytics-purview-datamap
- [ ] com.azure:azure-analytics-synapse-accesscontrol
- [x] com.azure:azure-analytics-synapse-artifacts
- [ ] com.azure:azure-analytics-synapse-managedprivateendpoints
- [ ] com.azure:azure-analytics-synapse-monitoring
- [ ] com.azure:azure-analytics-synapse-spark
- [ ] com.azure:azure-communication-callautomation
- [ ] com.azure:azure-communication-callingserver
- [ ] com.azure:azure-communication-chat
- [ ] com.azure:azure-communication-common
- [ ] com.azure:azure-communication-email
- [ ] com.azure:azure-communication-identity
- [x] com.azure:azure-communication-jobrouter
- [ ] com.azure:azure-communication-networktraversal
- [ ] com.azure:azure-communication-phonenumbers
- [ ] com.azure:azure-communication-rooms
- [ ] com.azure:azure-communication-sms
- [ ] com.azure:azure-containers-containerregistry
- [ ] com.azure:azure-core
- [ ] com.azure:azure-core-experimental
- [ ] com.azure:azure-core-management
- [ ] com.azure:azure-core-metrics-opentelemetry
- [ ] com.azure:azure-core-serializer-avro-jackson
- [ ] com.azure:azure-core-serializer-json-gson
- [ ] com.azure:azure-core-serializer-json-jackson
- [ ] com.azure:azure-core-test
- [ ] com.azure:azure-core-tracing-opentelemetry
- [ ] com.azure:azure-core-version-tests
- [ ] com.azure:azure-cosmos
- [ ] com.azure:azure-cosmos-benchmark
- [ ] com.azure:azure-cosmos-dotnet-benchmark
- [ ] com.azure:azure-cosmos-encryption
- [ ] com.azure:azure-cosmos-tests
- [ ] com.azure:azure-data-schemaregistry-apacheavro
- [ ] com.azure:azure-data-schemaregistry-jsonschema
- [ ] com.azure:azure-data-tables
- [ ] com.azure:azure-developer-loadtesting
- [ ] com.azure:azure-digitaltwins-core
- [ ] com.azure:azure-health-insights-cancerprofiling
- [ ] com.azure:azure-health-insights-clinicalmatching
- [ ] com.azure:azure-identity
- [ ] com.azure:azure-iot-deviceupdate
- [ ] com.azure:azure-iot-modelsrepository
- [ ] com.azure:azure-json
- [ ] com.azure:azure-json-reflect
- [ ] com.azure:azure-maps-elevation
- [ ] com.azure:azure-maps-geolocation
- [ ] com.azure:azure-maps-render
- [ ] com.azure:azure-maps-route
- [ ] com.azure:azure-maps-search
- [ ] com.azure:azure-maps-timezone
- [ ] com.azure:azure-maps-traffic
- [ ] com.azure:azure-maps-weather
- [ ] com.azure:azure-media-videoanalyzer-edge
- [ ] com.azure:azure-messaging-eventgrid
- [ ] com.azure:azure-messaging-webpubsub
- [ ] com.azure:azure-messaging-webpubsub-client
- [ ] com.azure:azure-mixedreality-authentication
- [ ] com.azure:azure-mixedreality-remoterendering
- [ ] com.azure:azure-monitor-ingestion
- [ ] com.azure:azure-monitor-opentelemetry-exporter
- [ ] com.azure:azure-monitor-query
- [ ] com.azure:azure-quantum-jobs
- [ ] com.azure:azure-sdk-template
- [ ] com.azure:azure-sdk-template-three
- [ ] com.azure:azure-sdk-template-two
- [ ] com.azure:azure-search-documents
- [ ] com.azure:azure-security-attestation
- [ ] com.azure:azure-security-confidentialledger
- [ ] com.azure:azure-security-keyvault-jca
- [ ] com.azure:azure-spring-data-cosmos
```

# After migration

Once you've completed migration for your libraries update the tracking above and remove yourself as one of the issue assignees.

**Comment by weidongxu-microsoft** [comment]
management-plane https://github.com/Azure/azure-sdk-for-java/issues/38333
We would include this in spring planning. Probably going to take months. @XiaofeiCao 

data-plane, SDK from typespec maybe the first ones. I think Shawn is checking OpenAI, Jose is checking OpenAI Assistants. Others currently on @haolingdong-msft (as well as the last few fixed and release of 0.14.0)

**Comment by XiaofeiCao** [comment]
### WIP
|Index|SDK|reason|
|--|--|--|
|1| azure-resourcemanager-deviceprovisioningservices | codegen issue, EMPTY_BYTE_ARRAY not generated in client: https://deschutes-ppe.microsoft.com/webclient/2e52a55a-9ddd-4a12-ad75-039f120a08f1 |
|2| azure-resourcemanager-paloaltonetworks-ngfw | met many breaking changes, likely codegen issue |
|3| azure-resourcemanager-networkanalytics| service backend no longer works, wait for confirmation, likely won't migrate |

### Excluded

|Index|SDK|reason|
|--|--|--|
|1| azure-resourcemanager-samples |  |
|2| azure-resourcemanager-test |  |
|3| azure-resourcemanager-perf |  |
|4| azure-resourcemanager-commerce | service define two success response with different body: https://github.com/Azure/azure-rest-api-specs/pull/23172#issuecomment-1475702721 |
|5| azure-resourcemanager-azureadexternalidentities | we never released first beta due to service never fixing backend: https://github.com/Azure/azure-sdk-for-java/pull/42223#issuecomment-2401690656 |

### Deprecated

|Index|SDK|reason|
|--|--|--|
|7| azure-resourcemanager-machinelearningservices | decommissioned |
|8| azure-resourcemanager-loadtestservice | decommissioned |
|9| azure-resourcemanager-batchai | decommissioned |
|10| azure-resourcemanager-videoanalyzer | decommissioned |
|11| azure-resourcemanager-securitydevops | specs deleted from repo, will be merged into security |
|12| azure-resourcemanager-deploymentmanager | decommissioned |
|13| azure-resourcemanager-mysql | service backend no longer works |

**Comment by XiaofeiCao** [comment]
Done migrating mgmt libs to azure-json. 
For excluded packages, see https://github.com/Azure/azure-sdk-for-java/issues/38569#issuecomment-2559218054 for reason.

**Comment by weidongxu-microsoft** [comment]
For commerce, if we really want to, we can generate upon an older commit ID of the specs repo.

**Comment by alzimmermsft** [comment]
Closing as completed as all valid cases have been migrated which is the spirit of this issue.
