### ISSUE TITLE
[Kafka V2]Kafka V2

### ISSUE THREAD

**Issue by xinlian12** [Azure/azure-sdk-for-java#38773]
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38768
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38769
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38767
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38766
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38765
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38770
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38772
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38771
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/38776
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/39066
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/39231
- [ ] https://github.com/Azure/azure-sdk-for-java/issues/39498
```
