### ISSUE TITLE
Release KeyVault Track 2 Library Preview 2 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#4059]
This tracks the work of releasing the KeyVault Track 2 Preview 2

### API Design ###
- [ ] Crypto in Keys
  - [X] Proposal ready (#4394)
  - [ ] Design approved

### Features ###
- [X] Challenge based authentication (to run in any clouds) #4057 #4058 
- [ ] Nightly run of tests #4067 
- [x] Crypto support for keys 
  - [X] Crypto via the service
    - [X] Code complete
      - [X] Async methods (#4395, #4397, #4402)
      - [X] Sync methods (#4395, #4397, #4402)
      - [x] Testing complete (#4401)
  - [x] Crypto on the client 
    - [x] Code complete (#4396)
      - [X] Rsa - encrypt/decrypt, wrap/unwrap   (sync/async)
      - [X] EC - sign/verify  (sync/async)
      - [x] Symmetric Key  ---- (encrypt/decrypt, wrap/unwrap  )
    - [x] Testing complete

### Docs ### 
- [x] Samples (#4398) 
- [x] Readme updates (#4399)  
- [X] Javadocs
