### ISSUE TITLE
Azure Json / Azure Xml - Stream style migration (client libraries)

### ISSUE THREAD

**Issue by srnagar** [Azure/azure-sdk-for-java#40614]
Guide on how to migrate: https://github.com/Azure/azure-sdk-for-java/wiki/Azure-Json-Migration

```[tasklist]
### Tasks
- [x] azure-ai-anomalydector (@srnagar)
- [x] azure-ai-formrecognizer (just a few manual code references to Jackson Databind) (@samvaity)
- [x] ~~azure-ai-personalizer (@samvaity)~~ never released, migration will be required by partner team on GA
- [x] azure-ai-textanalytics (stream-style serialization enabled, generated classes using Jackson still [maybe handwritten but header lies] -> TA has v1 and v2 versions, models are generated but v1 models no longer in the spec definition so v1 models won't pick up changes automatically) (@mssfang)
- [x] azure-ai-translationtext (@srnagar)
- [x] azure-ai-vision-face (@mssfang)
- [x] azure-ai-vision-imageanalysis (@srnagar)
- [x] azure-analytics-defender-easm (@weidongxu-microsoft) - Waiting to solve issues with regenerating the library with TypeSpec
- [x] azure-analytics-purview-datamap (@mssfang)
- [x] azure-analytics-synapse-accesscontrol (@alzimmermsft)
- [x] azure-analytics-synapse-managedprivateendpoints (@alzimmermsft)
- [x] azure-analytics-synapse-monitoring (@alzimmermsft)
- [x] azure-analytics-synapse-spark (@alzimmermsft)
- [x] azure-communication-callautomation (@anuchandy)
- [x] ~~azure-communication-callingserver (@anuchandy) ([REVIEW-IN-PROGRESS](https://github.com/Azure/azure-sdk-for-java/pull/41101))~~ - Update 7/12: Service is being decomissioned :(
- [x] azure-communication-chat (@anuchandy)
- [x] azure-communication-common (@conniey)
- [x] azure-communication-email (@anuchandy) ([REVIEW IN-PROGRESS](https://github.com/Azure/azure-sdk-for-java/pull/41222))
- [x] azure-communication-identity (@samvaity)
- [x] azure-communication-messages (@conniey)
- [x] azure-communication-phonenumbers (@srnagar)
- [x] azure-communication-rooms (@samvaity)
- [x] azure-communication-sms (@srnagar)
- [x] azure-compute-batch (@conniey)
- [x] azure-data-schemaregistry-apacheavro (only has a dependency and module-opens) (@vcolin7)
- [x] azure-data-schemaregistry-jsonschema (only has a module-opens) (@vcolin7)
- [x] azure-developer-devcenter (@vcolin7) - Did not need migration, already using `JsonSerializable`
- [x] azure-developer-loadtesting (@vcolin7) - [Done](https://github.com/Azure/azure-sdk-for-java/pull/41399)
- [x] azure-digitaltwins-core (@alzimmermsft)
- [x] ~~azure-health-insights-cancerprofiling (@vcolin7)~~ (will migrate when releasing)
- [x] ~~azure-health-insights-clinicalmatching (@vcolin7)~~ (will migrate when releasing)
- [x] ~~azure-health-insights-radiologyinsights (@vcolin7)~~ (will migrate when releasing)
- [x] azure-identity (@billwert)
- [x] ~~azure-iot-modelsrepository (@vcolin7) - Service just released a first beta in 2021.~~ (will enforce migration when/if GA'ing)
- [x] azure-maps-elevation (@alzimmermsft)
- [x] azure-maps-geolocation (@alzimmermsft)
- [x] azure-maps-render (@alzimmermsft)
- [x] azure-maps-route (@alzimmermsft)
- [x] azure-maps-search (@alzimmermsft)
- [x] azure-maps-timezone (@alzimmermsft)
- [x] azure-maps-traffic (@alzimmermsft)
- [x] azure-maps-weather (@alzimmermsft)
- [x] ~~azure-media-videoanalyzer-edge (@vcolin7)~~ - Service was deprecated in 2022. (See [README](https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/videoanalyzer/azure-media-videoanalyzer-edge))
- [x] azure-messaging-eventgrid (@billwert)
- [x] azure-messaging-webpubsub (@alzimmermsft)
- [x] azure-messaging-webpubsub-client (@alzimmermsft)
- [x] azure-mixedreality-authentication (@vcolin7) - [Done](https://github.com/Azure/azure-sdk-for-java/pull/41386)
- [x] azure-mixedreality-remoterendering (@anuchandy) [Done](https://github.com/Azure/azure-sdk-for-java/pull/41122)
- [x] azure-monitor-ingestion (test opens to Jackson) (@jairmyree) [keeping test opens as this is testing custom serialization]
- [x] azure-monitor-opentelemetry-exporter (service team)
- [x] ~~azure-quantum-jobs (@vcolin7)~~ (will enforce migration when/if GA'ing)
- [x] ~~azure-sdk-build-tool (@srnagar)~~ deprecated
- [x] azure-security-keyvault-jca (@vcolin7)
```

<details><summary>Excluded libraries</summary>
<p>

Excluded Track 1 using Jackson:

- azure-batch
- azure-cognitiveservices-autosuggest
- azure-cognitiveservices-computervision
- azure-cognitiveservices-contentmoderator
- azure-cognitiveservices-customimagesearch
- azure-cognitiveservices-customsearch
- azure-cognitiveservices-customvision-prediction
- azure-cognitiveservices-customvision-training
- azure-cognitiveservices-entitysearch
- azure-cognitiveservices-faceapi
- azure-cognitiveservices-imagesearch
- azure-cognitiveservices-luis-authoring
- azure-cognitiveservices-luis-runtime
- azure-cognitiveservices-newssearch
- azure-cognitiveservices-qnamaker
- azure-cognitiveservices-spellcheck
- azure-cognitiveservices-textanalytics
- azure-cognitiveservices-videosearch
- azure-cognitiveservices-visualsearch
- azure-cognitiveservices-websearch
- azure-eventgrid
- azure-keyvault
- azure-keyvault-cryptography
- azure-keyvault-webkey
- azure-loganalytics
- azure-media
- azure-storage-blob

Exluded Track 2 using Jackson:

- azure-cosmos
- azure-cosmos-encryption
- azure-cosmos-kafka-connection
- azure-cosmos-spark_3-1_2-12
- azure-cosmos-spark_3-2_2-12
- azure-cosmos-spark_3-3_2-12
- azure-cosmos-spark_3-4_2-12
- azure-cosmos-spark_3-5_2-12
- azure-cosmos-test
- azure-storage-blob
- azure-storage-blob-batch
- azure-storage-blob-changefeed
- azure-storage-blob-cryptography
- azure-storage-blob-nio
- azure-storage-common
- azure-storage-internal-avro

Excluded Resource Manager:

- azure-resourcemanager-advisor
- azure-resourcemanager-agrifood
- azure-resourcemanager-alertsmanagement
- azure-resourcemanager-apicenter
- azure-resourcemanager-apimanagement
- azure-resourcemanager-appcomplianceautomation
- azure-resourcemanager-appconfiguration
- azure-resourcemanager-appcontainers
- azure-resourcemanager-applicationinsights
- azure-resourcemanager-appplatform
- azure-resourcemanager-appservice
- azure-resourcemanager-astro
- azure-resourcemanager-attestation
- azure-resourcemanager-authorization
- azure-resourcemanager-automanage
- azure-resourcemanager-automation
- azure-resourcemanager-avs
- azure-resourcemanager-azureadexternalidentities
- azure-resourcemanager-azurearcdata
- azure-resourcemanager-azurestack
- azure-resourcemanager-azurestackhci
- azure-resourcemanager-baremetalinfrastructure
- azure-resourcemanager-batch
- azure-resourcemanager-batchai
- azure-resourcemanager-billing
- azure-resourcemanager-billingbenefits
- azure-resourcemanager-botservice
- azure-resourcemanager-cdn
- azure-resourcemanager-changeanalysis
- azure-resourcemanager-chaos
- azure-resourcemanager-cognitiveservices
- azure-resourcemanager-commerce
- azure-resourcemanager-communication
- azure-resourcemanager-compute
- azure-resourcemanager-confidentialledger
- azure-resourcemanager-confluent
- azure-resourcemanager-connectedvmware
- azure-resourcemanager-consumption
- azure-resourcemanager-containerinstance
- azure-resourcemanager-containerregistry
- azure-resourcemanager-containerservice
- azure-resourcemanager-containerservicefleet
- azure-resourcemanager-cosmos
- azure-resourcemanager-cosmosdbforpostgresql
- azure-resourcemanager-costmanagement
- azure-resourcemanager-customerinsights
- azure-resourcemanager-dashboard
- azure-resourcemanager-databox
- azure-resourcemanager-databoxedge
- azure-resourcemanager-databricks
- azure-resourcemanager-datadog
- azure-resourcemanager-datafactory
- azure-resourcemanager-datalakeanalytics
- azure-resourcemanager-datalakestore
- azure-resourcemanager-datamigration
- azure-resourcemanager-dataprotection
- azure-resourcemanager-defendereasm
- azure-resourcemanager-delegatednetwork
- azure-resourcemanager-deploymentmanager
- azure-resourcemanager-desktopvirtualization
- azure-resourcemanager-devcenter
- azure-resourcemanager-devhub
- azure-resourcemanager-deviceprovisioningservices
- azure-resourcemanager-deviceregistry
- azure-resourcemanager-deviceupdate
- azure-resourcemanager-devopsinfrastructure
- azure-resourcemanager-devspaces
- azure-resourcemanager-devtestlabs
- azure-resourcemanager-digitaltwins
- azure-resourcemanager-dns
- azure-resourcemanager-dnsresolver
- azure-resourcemanager-dynatrace
- azure-resourcemanager-edgeorder
- azure-resourcemanager-edgezones
- azure-resourcemanager-education
- azure-resourcemanager-elastic
- azure-resourcemanager-elasticsan
- azure-resourcemanager-eventgrid
- azure-resourcemanager-eventhubs
- azure-resourcemanager-extendedlocation
- azure-resourcemanager-fluidrelay
- azure-resourcemanager-frontdoor
- azure-resourcemanager-graphservices
- azure-resourcemanager-hanaonazure
- azure-resourcemanager-hardwaresecuritymodules
- azure-resourcemanager-hdinsight
- azure-resourcemanager-hdinsight-containers
- azure-resourcemanager-healthbot
- azure-resourcemanager-healthcareapis
- azure-resourcemanager-hybridcompute
- azure-resourcemanager-hybridconnectivity
- azure-resourcemanager-hybridcontainerservice
- azure-resourcemanager-hybridkubernetes
- azure-resourcemanager-hybridnetwork
- azure-resourcemanager-imagebuilder
- azure-resourcemanager-informaticdatamanagement
- azure-resourcemanager-iotcentral
- azure-resourcemanager-iotfirmwaredefense
- azure-resourcemanager-iothub
- azure-resourcemanager-keyvault
- azure-resourcemanager-kubernetesconfiguration
- azure-resourcemanager-kusto
- azure-resourcemanager-labservices
- azure-resourcemanager-largeinstance
- azure-resourcemanager-loadtesting
- azure-resourcemanager-loganalytics
- azure-resourcemanager-logic
- azure-resourcemanager-logz
- azure-resourcemanager-machinelearning
- azure-resourcemanager-machinelearningservices
- azure-resourcemanager-maintenance
- azure-resourcemanager-managedapplications
- azure-resourcemanager-managednetworkfabric
- azure-resourcemanager-managementgroups
- azure-resourcemanager-maps
- azure-resourcemanager-mariadb
- azure-resourcemanager-marketplaceordering
- azure-resourcemanager-mediaservices
- azure-resourcemanager-migrationdiscoverysap
- azure-resourcemanager-mixedreality
- azure-resourcemanager-mobilenetwork
- azure-resourcemanager-monitor
- azure-resourcemanager-msi
- azure-resourcemanager-mysql
- azure-resourcemanager-mysqlflexibleserver
- azure-resourcemanager-netapp
- azure-resourcemanager-network
- azure-resourcemanager-networkanalytics
- azure-resourcemanager-networkcloud
- azure-resourcemanager-networkfunction
- azure-resourcemanager-newrelicoberveability
- azure-resourcemanager-nginx
- azure-resourcemanager-notificationhubs
- azure-resourcemanager-oep
- azure-resourcemanager-operationsmanagement
- azure-resourcemanager-oracledatabase
- azure-resourcemanager-orbital
- azure-resourcemanager-paloaltonetworks-ngfw
- azure-resourcemanager-peering
- azure-resourcemanager-playwrighttesting
- azure-resourcemanager-policyinsights
- azure-resourcemanager-postgresql
- azure-resourcemanager-postgresqlflexibleserver
- azure-resourcemanager-powerbidedicated
- azure-resourcemanager-privatedns
- azure-resourcemanager-providerhub
- azure-resourcemanager-purview
- azure-resourcemanager-quantum
- azure-resourcemanager-qumulo
- azure-resourcemanager-quota
- azure-resourcemanager-recoveryservices
- azure-resourcemanager-recoveryservicesbackup
- azure-resourcemanager-recoveryservicesdatareplication
- azure-resourcemanager-recoveryservicessiterecovery
- azure-resourcemanager-redis
- azure-resourcemanager-redisenterprise
- azure-resourcemanager-relay
- azure-resourcemanager-reservations
- azure-resourcemanager-resourceconnector
- azure-resourcemanager-resourcegraph
- azure-resourcemanager-resourcehealth
- azure-resourcemanager-resourcemover
- azure-resourcemanager-resources
- azure-resourcemanager-samples
- azure-resourcemanager-scvmm
- azure-resourcemanager-search
- azure-resourcemanager-security
- azure-resourcemanager-securitydevops
- azure-resourcemanager-securityinsights
- azure-resourcemanager-selfhelp
- azure-resourcemanager-servicebus
- azure-resourcemanager-servicefabric
- azure-resourcemanager-servicelinker
- azure-resourcemanager-servicenetworking
- azure-resourcemanager-signalr
- azure-resourcemanager-sphere
- azure-resourcemanager-springappdiscovery
- azure-resourcemanager-sql
- azure-resourcemanager-sqlvirtualmachine
- azure-resourcemanager-standbypool
- azure-resourcemanager-storage
- azure-resourcemanager-storageactions
- azure-resourcemanager-storagecache
- azure-resourcemanager-storageimportexport
- azure-resourcemanager-storagemover
- azure-resourcemanager-storagepool
- azure-resourcemanager-streamanalytics
- azure-resourcemanager-subscription
- azure-resourcemanager-support
- azure-resourcemanager-synapse
- azure-resourcemanager-test
- azure-resourcemanager-timeseriesinsights
- azure-resourcemanager-trafficmanager
- azure-resourcemanager-videoanalyzer
- azure-resourcemanager-vmwarecloudsimple
- azure-resourcemanager-voiceservices
- azure-resourcemanager-webpubsub
- azure-resourcemanager-workloads
- azure-resourcemanager-workloadssapvirtualinstance

Excluded Spring:

- azure-spring-data-cosmos
- spring-cloud-azure
- spring-cloud-azure-appconfiguration-config
- spring-cloud-azure-appconfiguration-config-web
- spring-cloud-azure-autoconfigure
- spring-cloud-azure-feature-management
- spring-cloud-azure-stream-binder-eventhubs
- spring-cloud-azure-stream-binder-servicebus
- spring-messaging-azure
- spring-messaging-azure-eventhubs
- spring-messaging-azure-servicebus
- spring-messaging-azure-storage-queue
</p>
</details>
