### ISSUE TITLE
[FEATURE REQ] Support auth by customer defined TokenCredencial for all scenarios

### ISSUE THREAD

**Issue by rujche** [Azure/azure-sdk-for-java#40897]
**Is your feature request related to a problem? Please describe.**
When migrate auth in Spring tests, the pipeline shows that some integration test failed because related feature not support auth by customer defined **TokenCredential** bean.
1. Link to PR: https://github.com/Azure/azure-sdk-for-java/pull/40800
2. Link to pipeline: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3914516&view=logs&j=b6747878-dc75-581a-bba2-ee42aac9c86f&t=9578c5f5-3931-5ca2-47db-3cca71421dc5&l=16070
3. Screenshot of test failure of pipeline:
> ![image](https://github.com/Azure/azure-sdk-for-java/assets/171773178/c9e7987f-4a70-4175-ab07-e6fb342315da)

**Describe the solution you'd like**
Develop new feature: Make related scenario support customer-defined TokenCredential. Make all existing integration tests passed in pipeline. 

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Description Added
- [x] Expected solution specified
```[tasklist]
### Tasks
- [ ] Make Service BusMultiBinder support customer defined TokenCredential
- [ ] Make PassworkLessMySQL support customer defined TokenCredential
- [ ] Make KeyVaultPropertySource support customer defined TokenCredential
- [ ] Make ServiceBusJmsPasswordless support customer defined TokenCredential
```

**Comment by rujche** [comment]
Sharing:
About **ServiceBusMultiBindersIT**, **@ConditionalOnMissingBean** not take effect because there are 2 **ApplicationContext**s:
Here is the screenshot about how to find the 2 **ApplicationContext**s:

![image](https://github.com/Azure/azure-sdk-for-java/assets/171773178/40504b8f-5cd6-4943-acd1-073a399d8458)
