### ISSUE TITLE
azure-json, migrate existing premium MGMT libs

### ISSUE THREAD

**Issue by XiaofeiCao** [Azure/azure-sdk-for-java#41194]
Part of https://github.com/Azure/azure-sdk-for-java/issues/40619

```[tasklist]
### MGMT premium libs
- [x] azure-resourcemanager-appplatform
- [x] azure-resourcemanager-appservice
- [x] azure-resourcemanager-authorization
- [x] azure-resourcemanager-cdn(https://github.com/Azure/autorest.java/issues/2841)
- [x] azure-resourcemanager-compute
- [x] azure-resourcemanager-containerinstance
- [x] azure-resourcemanager-containerregistry
- [x] azure-resourcemanager-containerservice
- [x] azure-resourcemanager-cosmos
- [x] azure-resourcemanager-dns
- [x] azure-resourcemanager-eventhubs
- [x] azure-resourcemanager-keyvault
- [x] azure-resourcemanager-monitor(https://github.com/Azure/autorest.java/issues/2841)
- [x] azure-resourcemanager-msi
- [x] azure-resourcemanager-network
- [x] azure-resourcemanager-privatedns
- [x] azure-resourcemanager-redis
- [x] azure-resourcemanager-resources
- [x] azure-resourcemanager-search
- [x] azure-resourcemanager-servicebus
- [x] azure-resourcemanager-sql(https://github.com/Azure/autorest.java/issues/2841)
- [x] azure-resourcemanager-storage
- [x] azure-resourcemanager-trafficmanager
- [x] azure-resourcemanager
```

```[tasklist]
### Existing issues and affected libs
- [ ] https://github.com/Azure/autorest.java/issues/2826
- [ ] https://github.com/Azure/autorest.java/issues/2841
```

**Comment by XiaofeiCao** [comment]
2.42.0 released with the azure-json migration.
