### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 2 for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#4130]
## Deliverable
Released azure-messaging-eventhubs 5.0.0-preview.2.
https://search.maven.org/artifact/com.azure/azure-messaging-eventhubs/5.0.0-preview.2/jar

## Goal
Release a second preview of Event Hubs client library

### Track 2 Guidelines

- [ ] #3531 - Update logging to match design spec.
- [ ] #3580 - Ensure Proxy support aligns with Track 2 guidelines
- [x] #4042 - Investigate Retry surface area

### Features

- [x] #4308 - Add fixed retry
- [ ] #3806 - Replace any external links with aka.ms ones
- [ ] #3884 - Listen for clean-up events from session/link children
- [ ] #3923 - Replace constant strings with resource strings
- [ ] #4352 - Reopen connection on transient errors.
- [ ] #4372 - EventHubConsumer recreates AMQP link on failure
- [x] #4262 - Add support for individual send message Retry
- [x] #4371 - Design Event Processor Host
- [x] #4137 - Should consider max link size when creating batches in EventDataCollector
- [x] #4263 - Add functionality that will create and send an EventDataBatch

### Bugs

- [x] #4139 - Cannot open more than 2 consumers at the same time

### Closed
- [x] #4132 - Add support for WEB_SOCKETS
- [x] #4214 - Enable live tests
- [x] #3714 - Create Unit tests for exception classes
- [x] #3894 - Rename `Retry` to `RetryPolicy`
- [x] #4041 - Update the scope of classes in azure-core-amqp
- [x] #4136 - Clone retry policy and other builder parameters
- [x] #4215 - Add Annotations for ServiceClient, ServiceMethod, etc.
- [x] #4309 - Cloning Options and so they don't get modified when a new instance is created.
- [x] #4423 - Enable live tests for Event Hubs client library

## Related
* [Event Hubs Track 2 Preview 1](https://github.com/Azure/azure-sdk-for-java/issues/3498)
* Parent issue: https://github.com/Azure/azure-sdk/issues/442
