### ISSUE TITLE
[FEATURE REQ]: Evaluate improvements for `CosmosDiagnostics`. 

### ISSUE THREAD

**Issue by jeet1995** [Azure/azure-sdk-for-java#41332]
# Tasks

- [ ] From incidents and customer concerns, the stringified representation of `CosmosDiagnostics` occupies space which breaches size / character limits in whatever log analytics service the customer may choose to use, causing diagnostic strings to be truncated - an example of such limits specific to Azure Monitor - https://learn.microsoft.com/en-us/azure/azure-monitor/service-limits#logs-ingestion-api. Evaluate ways to reduce the size / characters taken up by a stringified representation of `CosmosDiagnostics` instance without losing the information it wishes to convey.

- [ ] As a part of the above issue, evaluate if there is a way to rejig the diagnostic string to display errors first as opposed to successes.

- [ ] The diagnostic string captures configurations set at the client-level or through operation-specific `Cosmos*RequestOptions` instances. With, dynamic request options - see #40061, operation-specific `Cosmos*RequestOptions` instances can be overridden. It could help to understand the source of these settings in the diagnostics.
 
- [ ] Expose `CosmosDiagnostics` for `handleChanges` and `handleLatestVersionChanges` overloads exposed for `ChangeFeedProcessor`. For `handleLatestVersionChanges`, both `ALL_VERSIONS_AND_DELETES` and `INCREMENTAL` change feed modes should emit `CosmosDiagnostics`. Validate the correctness of the diagnostics emitted by the `queryChangeFeed()` API.

**Comment by Vrinda2311** [comment]
@jeet1995 @kushagraThapar Found below issues in CosmosDiagnostics.

1. CosmosDiagnostics does not accurately represent the actual consistencyCfg in use, especially when overridden by dynamic request options. It only displays the client level consistency configuration.
2. Similarly, CosmosDiagnostics does not accurately represent the actual e2ePolicyCfg in use, especially when overridden by dynamic request options. It only displays the client level e2ePolicy.
3. Query/readMany operations do not honor excluded regions. Same is not even reflected in the diagnostics.

**Comment by tvaron3** [comment]
One suggestion for the showing the options in the diagnostics is only showing the effective options, so which one were actually executed in the request regardless of client, dynamic, or request level.

**Comment by jeet1995** [comment]
Closing — partial fix shipped in PR #41738 (CFP diagnostics). Remaining improvements will be addressed on a need-basis.
