### ISSUE TITLE
Release Storage Track 2 Library Preview 2 for Java

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4314]
**Azure Core**
- [x] #4443 Update codegen for Azure Core Preview 3
- [x] #4246 Trim quotes from eTag

**General**
- [ ] #4326 Migrate to PagedFlux (xstore team)
- [ ] #4328 Add default logging and redactions (xstore team)
- [x] #4444 Research test migration

**Blobs**
- [x] #4454 Get Snapshot Client from ContainerClient
- [x] #4319 Add deleteContainer method to StorageClient
- [x] #4316 Turn on linting
- [x] #4325 Turn on disabled tests
- [x] #4453 Return snapshot client for createSnapshot
- [x] #4321 Migrate additional V11 unit tests

**Queues**
- [x] #4037 Initial Queue implementation
- [x] #4459 Better name for QueueServiceClient
- [ ] #4492 Add SAS token generation support (xstore team)
- [ ] #4495 Add Bearer token support
- [x] #4496 Add link to REST API documentation in JavaDocs

**Files**
- [x] #4051 Initial Files implementation
- [ ] #4493 Add SAS token generation support (xstore team)
- [x] #4497 Add link to REST API documentation in JavaDocs
- [x] #4526 Add getFileClient to ShareClient
