### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 2 for Java

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#4433]
- [x] Spec for Distributed Tracing Produced @johanste 
- [ ] Distributed Tracing Plugin / Context updated to support Open Telemetry for Java @samvaity
- [ ] Tracing Context propagated through each Track 2 HTTP-based Library @samvaity
   - [x] AppConfiguration
   - [x] Azure.Core
   - [ ] Azure.Identity (blocked, moved to preview 3)
   - [ ] KeyVault
      - [x] Secrets
      - [x] Keys
      - [ ] Certificates
   - [ ] Storage (moved to preview 3)
      - [ ] Blobs
      - [ ] Files
      - [ ] Queues

**Comment by joshfree** [comment]
Closing Epic tracking Distributed Tracing Preview 2 feature work
