### ISSUE TITLE
Release Storage Track 2 Library Preview 4 for Java

### ISSUE THREAD

**Issue by alzimmermsft** [Azure/azure-sdk-for-java#4714]
*=Work owned by _xstore_ team
### Features
- [ ] * ~CRC~ MD5 #4508
- [ ] * Default logging and log redaction #4328
- [ ] * Client Side encryption #3970, #4481, #5322 
- [ ] * Batch support #4509, #4510, #5161 
  - [ ] multi-part/mixed support in Azure.Core #5161 
- [x] * Investigate porting TransferManager #4875

### Fit and Finish
- [ ] Consistency with V11
  - [ ] Progress Reporting #5243
- [ ] Perf issues #4527
   - [x] Thread pool sharing #5170 
- [ ] Stress issues #5180, #5275 
  - [x] Timeouts on uploading large files #5221
- [ ] URL encoding for blob name #4324
- [x] Support implicit root container #4370
- [x] FileClient to use InputStream and OutputStream #4528
- [ ] Test updates #5001, #5167, #5236, #5259, #5250 
  - [ ] Mocking support #5051
  - [x] Upload from file tests #5236
- [ ] Code refactoring #5021, #5125, #5138, #5226, #5289 
- [x] API naming, ordering cleanup #4457, #5323, #4458, #4525, #4543, #4916, #5075 
  - [x] Sync upload from file block parameter #5234
- [x] Swagger/Autogen issues
  - [x] PageBlobUploadPagesFromURLHeaders missing field encryptionKeySha256 #5286 
  - [x] Return URL instead of string, swagger change #4523 
  - [x] BlobItem/BlobMetadata swagger issue #5000 
- [x] Bugs #5341 

### Docs
- [ ] JavaDoc improvements #4047 
- [x] Enhance SAS documentation #5228
- [x] Add samples (async and side by side with v8) #5187

### Moved to Preview 5
- [ ] Porting guides #5311, #5312, #5313
