### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 4 for Java

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#4762]
**API Design**
- N/A for Preview 4

**Feature Work**
- [x] **undone from Preview 3** rename plugin from tracing-opentelemetry to azure.core.tracing
- [x] OpenTelemetry Packages available for testing by Azure SDK team
   - [x] Java SDK (**no ETA**) https://github.com/open-telemetry/opentelemetry-java
- [ ] **Preview 4** Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry

**Documentation**
- N/A for Preview 4

**CUT**
- [ ] **Preview 4** Azure.Identity tracing added (blocked on MSAL httpClient abstraction https://github.com/Azure/azure-sdk-for-java/issues/5284)
- [ ] **Preview 4** UX study (validate theory that tracing support in Azure SDK is extremely useful for diagnosing reliability issues)
- [ ] **Preview 4** Before the UX study, audit to make sure tracing is consistent across each language
- [ ] **Preview 4** React to UX study feedback

**Related** 
- Preview 2 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4433
- Preview 3 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4761
- Preview 4 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4762

**Comment by joshfree** [comment]
Closing issue tracking the release of azure-core-tracing-opencensus version 1.0.0-preview.4
