### ISSUE TITLE
Release Azure.Identity Library Preview 4 for Java

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#4969]
**API Design**
- [ ] **Preview 4** Review Exception Patterns across languages (@schaabs)
- [ ] **Preview 4** Review Authority Host Configuration and ensure consistency across Languages (@schaabs)

**Feature Work**
- [x] **Preview 4**  Authorization Code Flow support with MSAL https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow
- [x] **Preview 4** Create a combination of Automated and Manual testing (postman, curl, etc documented steps)
   - [x] Define Positive/Negative/Stress SSO test cases (cross applications, cross browser tabs)

**Documentation**
- [x] N/A

**CUT (implementation only changes, no API changes)**
- [x] **Preview 4** Design solution for publishing credentials to shared token cache for dev-time experience (@schaabs)
- [x] **Preview 4** Implement solution for publishing credentials to shared token cache
   - [x] Cross-Language-SDK testing to ensure the Shared Token Cache functions as expected (correct synchronization)

**Related**
   - [x] Preview 4 for Java https://github.com/Azure/azure-sdk-for-java/issues/4969
   - [x] Preview 3 for Java https://github.com/Azure/azure-sdk-for-java/issues/4761
   - [x] Preview 2 for Java https://github.com/Azure/azure-sdk-for-java/issues/4419
   - [x] Preview 1 for Java https://github.com/Azure/azure-sdk-for-java/issues/3505

**Comment by joshfree** [comment]
Closing as Preview 4 (October Preview) has been release for Azure.Identity
