### ISSUE TITLE
Build code generator for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#5036]
**Features**
- [x] Develop Autorest JSON-RPC server (#5494)
- [x] Port TypeScript code model to Java (#5495)
- [x] Migrate templates from v2 to v3 (#5496)
- [ ] Parse code model (#5497)
- [ ] Make basic Swagger generate (pass test server) (#5498)
- [ ] Integrate shared autorest.common modules (#5499)
--------------
- [ ] Develop x-ms generic extensions (#5500)
- [ ] Develop x-ms-pageable (#5501)
- [ ] Develop x-ms-long-running-operation (#5502)
- [ ] Develop azure-core-management (#5503)
- [ ] Develop `--azure-arm=True` (#5504)
- [ ] Generate info needed for lite gen (#5505)
- [ ] Design shared multi-api support (#5506)

**Tests**
- [ ] Convert gulp files to tox
- [ ] Port testserver launcher
- [ ] Plug new CI
