### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 4 for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5223]
Deliverable:
https://github.com/Azure/azure-sdk/blob/master/releases/2019-10-11/2019-10-11-java-preview4.md

For general summary & goal, please see: [Release Event Hub Track 2 Library (#442)](https://github.com/Azure/azure-sdk/issues/442) 

The work items linked to this issue herein represent the tasks needed to produce the 4th preview for the "track two" Event Hubs client library.

## API Design Review with the Board 
- [x] Create and send batch

## Features
- [ ] 🏃‍♀ Proxy Support
- [x] Last Enqueued Event Info on Consumer #5147

## Diagnosability
- [ ] Review logging

## Stress Testing
- [ ] 🏃‍♀Work with Service team to re-use existing Track 1 test framework to test Track 2 code

## Links to previous preview items
* [Event Hubs Track 2 Preview 1](https://github.com/Azure/azure-sdk-for-java/issues/3498)
* [Event Hubs Track 2 Preview 2](https://github.com/Azure/azure-sdk-for-java/issues/4130)
* [Event Hubs Track 2 Preview 3](https://github.com/Azure/azure-sdk-for-java/issues/4311)
