### ISSUE TITLE
Release Event Hubs Track 2 Library Preview 5 for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#5479]
The work items linked to this issue herein represent the tasks needed to produce the 5th preview for the "track two" Event Hubs client library.

## API Design Review with the Board 
- [ ] Follow up review for Event Processor

## Features
- [ ] Event Processor
- [x] [Stop exposing implementation classes in azure-core-amqp](https://github.com/Azure/azure-sdk-for-java/issues/5478)
## Diagnosability
- [ ] Review existing logging story

## Links to previous preview items
* [Event Hubs Track 2 Preview 1](https://github.com/Azure/azure-sdk-for-java/issues/3498)
* [Event Hubs Track 2 Preview 2](https://github.com/Azure/azure-sdk-for-java/issues/4130)
* [Event Hubs Track 2 Preview 3](https://github.com/Azure/azure-sdk-for-java/issues/4311)
* [Event Hubs Track 2 Preview 4](https://github.com/Azure/azure-sdk-for-java/issues/5223)

**Comment by ramya-rao-a** [comment]
Closing this issue as Preview 5 has been released.
