### ISSUE TITLE
Release AzConfig Track 2 Library Preview 5 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#5674]
### Features ###
- [x] Ensure exceptions are consistent for certain operations (c.f. other languages) 
- [x] Conditional Request: getSetting(), deleteSetting()
- [x] Renaming asOfDayTime to acceptDateTime, and lock to readOnly 
- [x] [BUG] AzConfig Revisions Range Returns 416 Status Code

### Docs ###
- [x] Add Samples
