### ISSUE TITLE
Release Azure.Identity Library Preview 5 for Java

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#5679]
**API Design**
- [ ] **From Preview 4** Review Exception Patterns across languages for consistency (@schaabs)
- [ ] **From Preview 4** Review Authority Host Configuration and ensure consistency across Languages (@schaabs)

**Feature Work**
- [ ] Fix remaining active issues (excludes Milestone=Backlog) https://github.com/Azure/azure-sdk-for-java/issues?q=is%3Aopen+is%3Aissue+label%3AAzure.Identity+no%3Amilestone

**Documentation**
- [x] N/A

**Related**
   - [x] Release Azure.Identity Track 2 Library https://github.com/Azure/azure-sdk/issues/536
   - [x] Preview 4 for Java https://github.com/Azure/azure-sdk-for-java/issues/4969
   - [x] Preview 3 for Java https://github.com/Azure/azure-sdk-for-java/issues/4761
   - [x] Preview 2 for Java https://github.com/Azure/azure-sdk-for-java/issues/4419
   - [x] Preview 1 for Java https://github.com/Azure/azure-sdk-for-java/issues/3505
