### ISSUE TITLE
Release Distributed Tracing Track 2 Plugin Preview 5 for Java

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#5684]
**API Design**
- N/A

**Feature Work**
- [x] OpenTelemetry Packages available for testing by Azure Java SDK team (**no ETA**) https://github.com/open-telemetry/opentelemetry-java
   - [x] Azure SDK Distributed Tracing Plugin / Context tested with OpenTelemetry alpha release
- [x] Zero Bug Bounce on active issues https://github.com/azure/azure-sdk-for-java/issues?q=is%3Aopen+is%3Aissue+label%3AClient+label%3AMonitor

**Documentation**
- [x] Update existing code samples for Storage, KeyVault, and EventHubs to include Distributed Tracing for OpenCensus and OpenTelemetry

**Related** 
- Release Distributed Tracing Track 2 Support https://github.com/Azure/azure-sdk/issues/501
- Preview 4 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4762
- Preview 3 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4761
- Preview 2 Tracing Epic for Java: https://github.com/Azure/azure-sdk-for-java/issues/4433

**Comment by joshfree** [comment]
Closing as this tracked the tracing preview for the November 2019 SDK update

http://repo2.maven.apache.org/maven2/com/azure/azure-core-tracing-opencensus/1.0.0-preview.4/
