### ISSUE TITLE
Release AzConfig Track 2 Library Preview 6 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#6166]
### Features
   - [x] Enable AAD authentication once service supports it
   - [x] Integrate feedback from UX studies on SetReadOnly/ClearReadOnly
   - [x] Integrate feedback form UX studies on AsOf vs. AcceptDateTime
   - [ ] Add support for setting RequestID,  Correlation Id and Correlation Context
   - [ ] Implement support for sync token
   - [ ] Auto generate protocol layer from swagger.
   - [x] Service API version support
   - [x] Remove Range support from SettingSector
 
### Docs
 - [x] Update samples
 - [x] Update readme

**Comment by mssfang** [comment]
Preview 6 released already
