### ISSUE TITLE
Release KeyVault Track 2 Library Preview 6 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#6215]
### December Milestone aka 'Release Blocking'
- [x] Address remaining Certificates API review feedback #6285  (PR approved - awaiting final ack)
- [ ] API Review of Certificates

### Features ###
- [x] Upgrade tests to JUnit 5 #6286 
- [x] Code Cleanup
   - [x] Refactor AesCbcHmacSha2 Class #4870 
   - [x] Fix checkstyle issues  #5145
   - [x] Fix javadoc issues #5139 

### Docs ###
- [ ] Review Javadocs
