### ISSUE TITLE
Cosmos: Enable Ignored tests and assess test failures

### ISSUE THREAD

**Issue by David-Noble-at-work** [Azure/azure-sdk-for-java#6289]
A number of tests have been disabled while work on V4 has progressed. We now need to know 

- What tests can be re-enabled, 
- What tests should be fixed before V4 release, and
- What test fixes can be postponed until after V4 release

I will provide recommendations, some test fixes/workarounds, and updated test TODOs before resolving this issue.

### Status

I've been running CI pipelines as well as fast, long, and e2e test suites against production endpoints on compute optimized and compute/memory constrained cloud environments. Kushagra and I have addressed a number of failures on my working branch with fixes or workarounds. All tests that run automatically pass but a number of "/azp run java - cosmos - tests" issues remain. 

The most recent CI Test run results are [here](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=190024&view=ms.vss-test-web.build-test-results-tab). We're at a 99.37% test pass rate with 37 failed tests out of a total of 31,110 tests with no test initialization failures or timeouts. This is not to say that test initialization issues are gone; just that the most recent run completed without test initialization failures or time outs.

This is a significant improvement over where we were a few days ago when a large number of tests/test classes were disabled due to test/test class initialization failures. Now, just one test is ignored: 

- `ConsistencyTests1::validateConsistentPrefixOnAsyncReplication` because it requires BOUNDED_STALENESS

Our remaining issues fall into one or more of these categories:

- Large document operations (query, create, read) in Gateway, Direct HTTP, and Direct TCP mode. 
- Operations that fail in compute optimized environments like my cloud test environments.
- Operations that fail in compute/memory constrained environments like CI.
- Tests that fail because the targeted cosmos instance is configured at a lower consistency level than required.

Here is a more detailed view of the current state of testing on cloud and in CI pipelines.

- Fast, long, and e2e test runs succeed locally when running against production endpoints.

   I've not tested locally against the emulator.

- Long and e2e tests reliably pass in each of my two Standard F16s_v2 (16 vcpus, 32 GiB memory) environments.

- A number of fast tests fail in each of my two Standard F16s_v2 (16 vcpus, 32 GiB memory) environments.
  
  Here is one full set of test results: [azure-cosmos-test-results.fast.fail.tar.gz](https://github.com/Azure/azure-sdk-for-java/files/3856073/azure-cosmos-test-results.fast.fail.tar.gz). Here is a summary of the failures:

  - All protocols and most if not all of the three consistency levels that CI currently tests.

    `AggregateQueryTests::queryDocumentsWithAggregates`
    `DocumentCrudTest::createLargeDocument`
    `DocumentCrudTest::readDocumentWithVeryLargePartitionKey`
    `VeryLargeDocumentQueryTest::queryLargeDocuments`

  - Direct HTTPS only

    `ParallelDocumentQueryTest::queryDocuments [Strong, Session consistency]`

  - Direct TCP only

    `DocumentCrudTest::deleteDocument [Eventual, Session consistency]`
    `DocumentCrudTest::deleteDocument_undefinedPK [Session consistency]`
    `DocumentCrudTest::readDocument [Eventual consistency]`

  **Implication:** we have some work to do in compute optimized environments.

- In CI Test runs `CosmosPartitionKeyTests::testNonPartitionedCollectionOperations` consistently fails with a 429 error.

  See, for example, this [test failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=190024&view=ms.vss-test-web.build-test-results-tab&runId=6817662&resultId=100061&paneView=debug),

- In CI Test runs `VeryLargeDocumentQueryTest::queryLargeDocuments` consistently fails with a `NullPointerException`.

  See, for example, this [test failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=190024&view=ms.vss-test-web.build-test-results-tab&runId=6817560&resultId=100403&paneView=debug)

- In CI Test runs a number of tests intermittently fail due to initialization timeouts

  #6380 `SinglePartitionReadFeedDocumentsTest`
  #6379 `ReadFeedDocumentsTest`
  #6346 `AggregateQueryTests`
  #6383 `UserDefinedFunctionUpsertReplaceTest` 

  See, for example, this [check run](https://github.com/Azure/azure-sdk-for-java/pull/6373/checks?check_run_id=307016978).

- In CI Test runs a number of tests fail because the Cosmos DB instances they're hitting aren't configured for the failed tests.

  See, for example, these [build results](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=189821&view=ms.vss-test-web.build-test-results-tab)

- In CI Test runs readMyWrites intermittently fails.

  See, for example, this [test failure](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=190024&view=ms.vss-test-web.build-test-results-tab&runId=6817690&resultId=100000&paneView=debug).

  This test runs more than once and may fail once or twice. Every once in a while no failures occur. On the last test failure that I checked, I saw 6 out of a total of 406,664 operation failures; an error rate of 1.5 x 10-5.

- All CI test results are consistent with the results of tests run on my Standard D2s v3 (2 vcpus, 8 GiB memory) environment.

  **Full set of cloud test results from compute/memory constrained app-server-lin-2:**
  - [azure-cosmos-test-results.e2e.fail.tar.gz](https://github.com/Azure/azure-sdk-for-java/files/3856350/azure-cosmos-test-results.e2e.fail.tar.gz)
  - [azure-cosmos-test-results.fast.fail.tar.gz](https://github.com/Azure/azure-sdk-for-java/files/3856351/azure-cosmos-test-results.fast.fail.tar.gz)
  - [azure-cosmos-test-results.long.pass.tar.gz](https://github.com/Azure/azure-sdk-for-java/files/3860920/azure-cosmos-test-results.long.pass.tar.gz)

  **Implication:** we have issues to address when running in resource constrained environments.

- We are not testing BOUNDED_STALENESS and CONSISTENT_PREFIX consistency levels

  We agreed to address BOUNDED_STALENESS and CONSISTENT_PREFIX consistency levels issues following release of 4.0.

### Environments

Cloud tests were run in each of three environments running against co-located Cosmos DB instances provisioned with up to one million RUs:

- [app-server-lin-1](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/86886548-0a7c-430b-b16f-014095647de4/resourceGroups/danoble.sdk-development/providers/Microsoft.Compute/virtualMachines/appserver-lin-1/overview) Standard F16s_v2 (16 vcpus, 32 GiB memory)
- [app-server-lin-2](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/86886548-0a7c-430b-b16f-014095647de4/resourceGroups/danoble.sdk-development/providers/Microsoft.Compute/virtualMachines/appserver-lin-2/overview) Standard D2s v3 (2 vcpus, 8 GiB memory) 
- [app-server-lin-3](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/86886548-0a7c-430b-b16f-014095647de4/resourcegroups/danoble.sdk-development/providers/Microsoft.Compute/virtualMachines/appserver-lin-3/overview)  Standard F16s_v2 (16 vcpus, 32 GiB memory) 

### Issues and recommendations

1. [x] **1** #6346 AggregateQueryTests initialization intermittently fails due to collection truncation error and consistently times out in CI environments

      **Observations:**
      Truncation fails due to 503, resource unavailable exception.

      **Workaround:** 
      Ignore failed collection truncations that regularly occur on azure cloud and less frequently occur on local dev test environments. 

      **Recommendation:**
      Apply workaround. Accept that ignoring truncation failures may (will?) cause `AggregateQueryTest` failures later. Address truncation failure issue following V4 release.

2. [x] **2** #6340 `ResourceTokenTest::readDocumentOfParKeyFromTwoCollPermissionWithDiffPartitionKeys` test failure

    Kushagra addressed this issue with a fix to the test.

3. [x] **3** #6339 `ResourceTokenTest::readDocumentFromPermissionFeed` test failure
  
    Kushagra addressed this issue with a fix to the test.

4. [x] **4** #6338 `ResourceTokenTest::readDocumentFromCollPermissionWithDiffPartitionKey_ResourceNotFound` test failure

    Kushagra addressed this issue with a fix to the test.

5. [ ] **5** #6336 `DocumentCrudTest::readDocumentWithVeryLargePartitionKey` test failure

6. [ ] **6** #6335 `DocumentCrudTest::createLargeDocument` test failure

7. [x] **7** #6337 `DocumentCrudTest::deleteDocument` test failure 

    **Observations:**
    I have not seen that this issue reproduce in CI or local test environments but this test consistently fails in Direct HTTPS and Direct TCP mode at Strong, Session, and Eventual consistency levels when run in my compute optimized azure cloud test environments. Failures are always due to timeout.

   **Recommendation:**
   Ensure these tests pass in compute-optimized cloud test environments following v4 release.

8. [X] **8** #6334 `CosmosPartitionKeyTests::testNonPartitionedCollectionOperations` test failures

    Fixed by Kushagra

9. [X] **9** #6327 `BackPressureTest::readFeed` test failures

      Fixed by Kushagra

10. [x] **10** #6326 `BackPressureTest::query` test failures

      Fixed by Kushagra

11. [ ] **11** #6377 `VeryLargeDocumentQueryTest::queryLargeDocuments` intermittently times out

    **Observations:**

    When tested locally against a production endpoint this test intermittently fails due to timeouts in Gateway, Direct HTTPS, and Direct TCP when the default timeout is 60 seconds. After bumping the SETUP_TIMEOUT and TIMEOUT intervals to 120 seconds, I have seen that the test consistently succeeds in between 20 and 90 seconds when tested locally and in my azure cloud environments.

    CI Emulator runs consistently timeout at 120 seconds.

    **Currently untested:** Emulator runs outside CI.

     **Workaround:**
     Increase timeout intervals from the default of 60 seconds to 120 seconds. Move this test out of the emulator test group into the simple test group for now.

    **Recommendation:**
   Address query performance issues following release of v4. Apply the workaround for now.

12. [x]  **12** #6378 ConsistencyTests1::validateConsistentPrefixOnAsyncReplication test failure

    **Observations:**
    This test is configured to use the `BoundedStaleness` consistency level. We agreed to address all bounded staleness consistency issues following release of V4.

    **Recommendation:**
    Ensure this test passes when we address BoundedStaleness issues following release of V4. Continue to ignore this test for now.

13. [ ] **13** #6379 ReadFeedDocumentsTest initialization consistently times out in CI environments

14. [ ] **14** #6380 SinglePartitionReadFeedDocumentsTest initialization consistently times out in CI environments

15. [ ] **15** #6383 UserDefinedFunctionUpsertReplaceTest initialization consistently times out in CI environments

16. [ ] **16** #6386 OrderbyDocumentQueryTest initialization intermittently times out in CI environments

  **Observations:**
  Succeeds when run locally and on compute optimized cloud environments. The before_OrderbyDocumentQueryTest method intermittently times out on compute/memory constrained cloud environments and CI pipelines.

  **Recommendation:**
  Bump SETUP_TIMEOUT limit and rerun the OrderbyDocumentQueryTest when a timeout occurs.

### Direct TCP Reliability check

The read-my-writes benchmark runs to completion without errors in both my performance test environments at concurrency levels 16, 32, 64, 128, 256, 512, and 1,024. In 20 minute runs at each level the best throughput was seen at:

* v4.X, concurrency: 128, 439.83 events / second
* v2.6.X, concurrency: 256, 638.44 events / second

This result is consistent with my ad-hoc observation that we have regressed on performance with this workload. See me for comparative numbers at each concurrency level. 

**Implication:**
Prior read and write latency/throughput test runs indicate that 4.X out performs 2.6.X on reads and writes. Hence, it is reasonable to assume we've regressed on query performance between 2.6.X and 4.X.
