### ISSUE TITLE
Move AutoRest generated clients into master

### ISSUE THREAD

**Issue by jianghaolu** [Azure/azure-sdk-for-java#667]
### Problem
Today, branches in the Azure SDK for Java Repository (a.k.a. this repo) are a bit confusing. `master` contains the old clients that we are not fully supporting, and the upcoming new clients are hidden in the branch `autorest`. 2 problems involved in this:
1. Violating *Anything in the master branch is always deployable* (https://guides.github.com/introduction/flow/). What are making sure that is always deployable and apply fixes asap is actually the `autorest` branch. Bugs in `master` will take a bit longer to be fixed, if ever, which arguably makes it not always deployable.
2. It's not discoverable for users to see the up-to-date development work in `autorest` branch. 

### Goal
We want to have a master branch that is as up-to-date as possible while making sure it's stable.

### Proposal
We propose the following model for SDK for Java branching:
1. `master` contains the stable builds of the upcoming releases - It should be releasable at any point. The version number will always be `{next release version}-SNAPSHOT`.
2. Features are developed on feature branches and CI jobs make sure when they are merged they won't break `master`
3. Past releases are tagged except for 4)
4. For a big breaking change, e.g. 1.0, past release is preserved as a branch for a minimal of 6 months

===
Here is a graph showing this model. Today we have `master` branch containing the old clients, `autorest` branch containing the new 1.0 candidates. We want to make the change to move the old clients into 0.9 and the 1.0.0-SNAPSHOT bits in `autorest` to `master`.
![azure sdk for java branching - new page-5](https://cloud.githubusercontent.com/assets/2320445/14692209/7a45e980-070a-11e6-8dc5-4d1912513452.png)
Notes:
- Purple timeline: the old client generated
- Yellow timeline: the new AutoRest generated client
- Blue labels: branches
- Green labels: tags or releases
- Dotted lines: release activity
- Dashed lines: Branches created for past releases upon hot fix requests
- Pink version number: The package version for `azure`

**Comment by jianghaolu** [comment]
### Tasks
- [ ] Verify Azure.Java in Azure/autorest:master generates correct code
- [ ] Verify `autorest` branch in Azure/azure-sdk-for-java is deployable
- [ ] Tag `master` branch in Azure/autorest as `java-1.0.0-beta1`
- [ ] Tag `autorest` branch in Azure/azure-sdk-for-java as `1.0.0-beta1`
- [ ] Send pull request from `javavnext`to `master` in AutoRest
- [ ] Send pull request from `exp` in azure-sdk-for-java-pr to `autorest` branch in azure-sdk-for-java
- [ ] Create branch `0.9` from `master` in azure-sdk-for-java (and remove `master`)
- [ ] Create branch `master` from `autorest` in azure-sdk-for-java (and remove `autorest`)
- [ ] Set the new `master` branch as default branch.

**Comment by jianghaolu** [comment]
This is done. Hooray!!
