### ISSUE TITLE
Create Test Automation for Azure.Identity running in Azure Hosted Environments

### ISSUE THREAD

**Issue by joshfree** [Azure/azure-sdk-for-java#7107]
**Epic: Create Test Automation for Azure.Identity running in Azure Hosted Environments**

- [x] Azure Cloud Shell
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/795
- [x] Azure VM
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/815
- [x] Azure Kubernetes
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/814
- [x] Azure WebJobs
  - [x] /sdk/e2e test assets checked-in so that they can be referenced from Vendor Instructions
  - [x] Language-specific instructions added to https://github.com/Azure/azure-sdk/issues/902

**Comment by joshfree** [comment]
Updating issue as Functions and App Services has been moved to the backlog
