### ISSUE TITLE
[UX Study] Address UserStudy feedbacks 

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#7594]
- [x] Remove `getDetectedLanguages` from `DetectLanguageResult` #8013 
- [x] Rename `erroneousDocumentCount` to `invalidDocumentCount` #7897
- [x] Rename `NamedEntity` -> `CategorizedEntity` #7897
- [x] Rename `type` and `subtype` properties on `NamedEntity` to `category` and `subCategory`. #7897
- [x] Rename `SentimentClass` to `Sentiment`. #7939
- [x] Create new model `PiiEntitiesResult`  and return it for `getPiiEntities` on `RecognizePiiEntitiesResult`. #7897
- [x] Delete `s` from all `detectLanguage`  method overloads. #7897
- [x] Add a new model for scores called `SentimentScore`  #7939
- [x] Update `TextSentiment` and `DocumentSentiment` models to use `SentimentScore` for scores. #7939
- [x] Update List<string> input methods to include options parameter.#8013
- [x] Update Readme, samples, changelog. #8014 
- [x] Update client method names to say `detectLanguageBatch`  and remove methods similar to `detectBatchLanguage(List<String> textInputs)` #8013
- [x] Return atomic type for all simple APIs #7939
- [x] Rename `getLinkedEntities()` to `getEntities` and global variable `linkedEntities` to `entities` #8014

**Comment by samvaity** [comment]
Closed with #8014, #7897 , #7939 , #8013
