### ISSUE TITLE
March release of KeyVault for Java

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-java#8005]
# Features

- [x] Add new Soft Delete properties to Key Vault data plane (#8291)
- [x] KeyOperations needs to support "import" for 7.1-preview (#8345)

# Bugs

- [x] Importing PEM-encoded certificates may not work (#8226)

**Comment by joshfree** [comment]
@heaths @g2vinay can this issue be closed now (or title updated to reflect what is currently being tracked)?

**Comment by heaths** [comment]
If it's been released with these features, yes.

**Comment by g2vinay** [comment]
Closing this issue now.
