### ISSUE TITLE
Release Event Hubs March 2020 update for Java

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#8082]
This is a parent issue tracking the work planned for Event Hubs for the March update.
Code complete date: March 6th, 2020

## API design 
- [ ] **In Progress** Propose smarter send APIs such that the user doesnt have to one by one fill the `EventDataBatch` to be able to send events
- [ ] **In Progress** Propose API to receive in batches
- [ ] **In Progress** Propose API to control greedy claiming of partitions by the Event Processor

## Features
- [ ] Code sample showing how to convert IotHub connection string to an Event Hubs compatible one which points to the built-in Event Hubs endpoint
- [ ] Receiver Redirect feature
- [ ] Review current logging experience, come up with a plan to streamline and be consistent across languages for ease of customer support, tackle low hanging fruits

## Testing
- [x] Test Event Hubs and Storage Blob checkpoint store in Azure Stack

cc @conniey, @srnagar

**Comment by ramya-rao-a** [comment]
Pending tasks have been moved to the April update being tracked in #8982

@srnagar, Please close this issue after doing the below
- Provide pointer to the March update and a link to the changelog 
- Move issues in this epic to #8982

**Comment by conniey** [comment]
Done as an april release.
