### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 3 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8135]
This tracks the work to release the Azure Cognitive Search Track2 Preview 3 Library

### Arch board
- [x] Review user defined schemas (part 2)
  - [x] FieldBuilder
- [ ] ArchBoard review for batching
- [x] API review for Index operations

### Features
- [ ] Move spatial types to Azure.Core
- [ ] ~Move SearchDocument to Azure.Core~
- [ ] Address feedback from Arch Board / UX Study
- [x] Finish implementation for
  - [x] Skillset
  - [x] Synonyms
- [x] Design and implement 
  - [x] Indexers
- [x] Design and implement DataSources
- [ ] ~Cross language consistency meeting and API Review~
- [ ] ~Performance testing~ 

### Docs
- [x] Schedule UX study 
  - [x] Define hypothesis
- [ ] Run UX Study
