### ISSUE TITLE
Release Azure Cognitive Search Track 2 Library Preview 4 for Java

### ISSUE THREAD

**Issue by AlexGhiondea** [Azure/azure-sdk-for-java#8136]
This tracks the work to release the Azure Cognitive Search Track2 Preview 4 Library

### Arch Board
- [x] Cross language consistency review
- [x] Final API shape approval

### Features
- [ ] Finalize implementation of FieldBuilder
- [x] Address API feedback (arch board and UX study)
- [x] Cleanup swagger transformation code 
- [x] Enable live testing

### UX Studies
- [x] Prepare UX study
- [x] Run through the UX study

### Docs
- [ ] Samples

**Comment by sima-zhu** [comment]
preview 4 is released. close the issue
