### ISSUE TITLE
[Feature] UX Study follow up 2 + API Review feedback

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#8224]
- [x] Rename property  sentimentScores to confidenceScores #8301
- [x] For LinkedEntity, rename Id to DataSourceEntityId and getDataSourceEntityId() #8301
- [x] Rename the class SentimentScorePerLabel to SentimentConfidenceScorePerLabel to reflect swagger naming. #8301 
- [x] Delete all intermediate `WithResponse` suffixed and Update APIs #8301
- [x] Unroll defaultCountryHint and defaultLanguage to builder API and remove TextAnalyticsClientOptions. #8301
- [x] Remove InnerError #8301
- [x] Change all input List<T> to Iterable<T> #8301 
- [x] API Tool feedbacks: https://apiview.dev/Assemblies/Review/942b652edaf44b7189f41270cf07e54f #8391
- [x] Delete `DocumentResultCollection` class and create `TextAnalyticsPagedResponse` class to include `modelVersion` and `TextAnalyticsBatchStatistics`. #8391
- [x] Implement a new `TextAnalyticsPagedFlux` class that takes `TextAnalyticsPagedResponse`. And  `TextAnalyticsPagedIterable` fot the synchronous APIs. #8391
- [x] Change all collection APIs to return `TextAnalyticsPagedFlux` for Async and `TextAnalyticsPagedIterable` for Sync APIs. #8391
- [x] Default value for `defaultCountryHint`.  "As an example, in .NET we use the default of the client and then give the option to the user to override the behavior and use None as default." Add an empty string means not using country hint at all. #8391
- [x] Rename `offset` and `length` to `graphemeLength` and `graphemeOffset` in SentenceSentiment,
CategorizedEntity, PiiEntity, LinkedEntityMatch and add a few tests. #8391
- [x] Rename showStatistics() to isStatisticsShown() in the `TextAnalyticsRequestOptions` #8391
- [x] Rename getErrorCodeValue() to getCode() #8391
- [x] Add an enum class `EntityCategory` as .NET has now. #8391

**Comment by maririos** [comment]
Consider also adding here: https://github.com/Azure/azure-sdk-for-net/issues/9985

**Comment by mssfang** [comment]
This issue addressed in #8391 and #8301
