### ISSUE TITLE
[SB Track2] Add createBatch and options with CreateBatchOptions

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#8769]
## Tasks
- [ ] Add ability to create ServiceBusMessageBatch. Add overload that accepts CreateBatchOption
  - [ ] Write unit tests
  - [ ] Write integration tests
