### ISSUE TITLE
Release Event Hubs April 2020 update for Java

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#8982]
This is a parent issue tracking the work planned for Event Hubs for the April update.
Code complete date: April 3rd, 2020

## API design 
- [ ] **In Progress** Propose smarter send APIs such that the user doesnt have to one by one fill the `EventDataBatch` to be able to send events
- [x] **In Progress** Propose API to receive in batches
- [ ] **In Progress** Propose API to control greedy claiming of partitions by the Event Processor

## Features
- [ ] Code sample showing how to convert IotHub connection string to an Event Hubs compatible one which points to the built-in Event Hubs endpoint
- [x] Code sample showing workaround needed for Event Hubs in Azure Stack
- [ ] Receiver Redirect feature
- [ ] Review current logging experience, come up with a plan to streamline and be consistent across languages for ease of customer support, tackle low hanging fruits

cc @conniey, @srnagar

**Comment by ramya-rao-a** [comment]
Other than the feature to receive in batches and the code sample showing workaround needed for Event Hubs in Azure Stack, rest of the work here is moved to the May 2020 milestone.

@srnagar Once released, paste the links to the released packages (the beta and the non beta ones) and close this issue with a note on what is going as part of the non beta release

**Comment by srnagar** [comment]
Maven releases:
[Beta EH](https://repo1.maven.org/maven2/com/azure/azure-messaging-eventhubs/5.1.0-beta.1/)
[Beta CheckpointStore](https://repo1.maven.org/maven2/com/azure/azure-messaging-eventhubs-checkpointstore-blob/1.1.0-beta.1/)

[EH 5.0.3](https://repo1.maven.org/maven2/com/azure/azure-messaging-eventhubs/5.0.3)
[Checkpoint store 1.0.3](https://repo1.maven.org/maven2/com/azure/azure-messaging-eventhubs-checkpointstore-blob/1.0.3)
