### ISSUE TITLE
Release Service Bus Track 2 Library Preview 2 for Java

### ISSUE THREAD

**Issue by conniey** [Azure/azure-sdk-for-java#9400]
This is a parent issue tracking the work planned for Service Bus to release the second preview following the [Java Azure SDK guidelines](https://azure.github.io/azure-sdk/java_introduction.html) 

Code complete date: May 3rd, 2020
Released: https://search.maven.org/artifact/com.azure/azure-messaging-servicebus/7.0.0-beta.2/jar

## Deliverables
- [x] Ensure all features for Queues work for Topics & Subscriptions as well
- [x] Receive & settle messages from session enabled queues & subscriptions. Include features like lock renewal, message auto complete & set/get session state
   - [x] Receive from a single session with user provided session id
   - [x] Receive from a single session, with the service picking the next available session
   - [ ] 🏃Receive from multiple sessions, with the ability to control the max number of concurrent sessions to receive from
- [ ] 🏃Add/remove/get rules features with support for filters and actions
- [ ] 🏃Address feedback from previous API reviews 
- [x] 🏃‍♂️ Increase test coverage
- [x] Schedule & cancel schedule for sync client

## Stretch Goals:
- [ ] Design for transaction support (design only)
- [x] 🏃‍♂️send() overload that takes multiple messages
