### ISSUE TITLE
Release Event Hubs May 2020 update for Java

### ISSUE THREAD

**Issue by ramya-rao-a** [Azure/azure-sdk-for-java#9973]
This is a parent issue tracking the work planned for Event Hubs for the May update.
Code complete date: May 3rd, 2020

## API design 
- [ ] **In Progress** Propose API to control greedy claiming of partitions by the Event Processor
- [ ] SharedKeyCredential

## Features
- [ ] Code sample showing how to convert IotHub connection string to an Event Hubs compatible one which points to the built-in Event Hubs endpoint
- [ ] Receiver Redirect feature
- [x] Smarter send APIs such that the user doesnt have to one by one fill the `EventDataBatch` to be able to send events
